'use client';

import {use,useEffect,useMemo,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {AppShell} from '@/components/app-shell';
import {HelpAside} from '@/components/product-guidance';
import {useToast} from '@/components/ui/toast';
import {api} from '@/lib/api';
import {statusLabel} from '@/lib/i18n';
import {localizeRequirementList,normalizeWorkspaceHref,workspaceOptionLabel} from '@/lib/workspace-localization';
import styles from '@/components/product-pages.module.css';

type Severity='info'|'warning'|'danger';
type StudioWarning={id:string;title:string;description:string;severity:Severity};
type StudioDraft={
 id:number|string;title:string;body:string;hook?:string;cta?:string;hashtags?:string;goal?:string;
 channel?:string;language?:string;content_type?:string;product_or_offer?:string;tone?:string;prompt?:string;
 status:'draft'|'in_review'|'approved'|'scheduled'|'published'|'archived';quality_score?:number|null;
 warnings?:StudioWarning[];compliance_result?:{status:'passed'|'warnings'|'blocked';summary:string;warnings:any[];suggestions:string[]}|null;updated_at?:string
};
type StudioOverview={
 user:{id:number;name:string;email:string};organization:{id:number;name:string}|null;
 brand:{id:number;name:string;primary_language?:string;industry?:string}|null;
 setup:{can_generate:boolean;missing_requirements:{id:string;title:string;description?:string;action_href:string}[]};drafts:StudioDraft[];
 brand_rules:{id:string;label:string;description:string;severity:Severity}[];
 recommended_action:{title:string;description:string;action_label:string;action_type:'generate'|'navigate'|'check'|'approval'|'schedule';action_href?:string};
 products?:string[];channels?:string[]
};

const blankDraft=(language='en'):StudioDraft=>({id:'',title:'',body:'',hook:'',cta:'',hashtags:'',goal:'',channel:'instagram',language,content_type:'post',product_or_offer:'',tone:'clear',prompt:'',status:'draft'});
const copies:any={
 en:{title:'Content Studio',sub:'Turn a real brief and Brand Pulse into a reviewable, platform-ready draft.',none:'No draft selected yet.',generate:'Generate draft',blank:'New blank draft',save:'Save',unsaved:'Unsaved changes',saved:'Saved',brief:'Brief',rules:'Brand rules',preview:'Platform preview',missing:'Complete these setup steps first',missingSub:'Open each item and finish it to unlock AI generation.',compliance:'Compliance check',complianceTitle:'Compliance',approval:'Send for approval',schedule:'Schedule',export:'Export assisted kit',archive:'Archive',recent:'Recent drafts',search:'Search drafts',goal:'Goal',channel:'Channel',language:'Language',type:'Content type',offer:'Product / offer',tone:'Tone',prompt:'Generation instruction',titleField:'Title',body:'Body',hook:'Hook',cta:'CTA',hashtags:'Hashtags',notChecked:'Not checked',completePulse:'Complete Brand Pulse to unlock brand rules.',readOnly:'Published drafts are read-only.',selectWarn:'Save or discard your unsaved changes before opening another draft.',scheduleApproved:'Approve this draft before scheduling it.',future:'Choose a future date and time.',emptySearch:'No drafts match this search.',retry:'Retry',saveFailed:'Could not save the draft.',required:'Goal, channel, and generation instruction are required.',generated:'Draft generated',generationFailed:'Could not generate the draft.',updated:'Draft updated.',transformFailed:'Could not update the draft.',complianceFailed:'Compliance check failed.',approvalSent:'Sent for approval',approvalFailed:'Connect an approval method before sending.',scheduled:'Draft scheduled.',schedulingFailed:'Could not schedule the draft.',exportFailed:'Could not export the kit.',archiveConfirm:'Archive this draft?',untitled:'Untitled draft',characters:'characters',notSaved:'Not saved',translate:'Translate',warning:'Warning',previewMeta:'Preview',copyAll:'Copy all',copied:'Copied',date:'Date',time:'Time',timezone:'Time zone',details:'Open details',closeDetails:'Close details'},
 fa:{title:'استودیوی محتوا',sub:'بریف واقعی و پالس برند را به یک پیش‌نویس آماده بررسی و انتشار تبدیل کنید.',none:'هنوز پیش‌نویسی انتخاب نشده است.',generate:'تولید پیش‌نویس',blank:'پیش‌نویس جدید',save:'ذخیره',unsaved:'ذخیره نشده',saved:'ذخیره شد',brief:'بریف محتوا',rules:'قوانین برند',preview:'پیش‌نمایش محتوا',missing:'ابتدا این مراحل را کامل کنید',missingSub:'برای فعال‌شدن تولید هوشمند، هر مورد را باز و تکمیل کنید.',compliance:'بررسی انطباق',complianceTitle:'وضعیت انطباق',approval:'ارسال برای تأیید',schedule:'زمان‌بندی',export:'خروجی بسته محتوا',archive:'آرشیو',recent:'پیش‌نویس‌های اخیر',search:'جست‌وجوی پیش‌نویس‌ها',goal:'هدف محتوا',channel:'کانال انتشار',language:'زبان محتوا',type:'قالب محتوا',offer:'محصول یا پیشنهاد',tone:'لحن',prompt:'توضیحی که باید بر اساس آن محتوا ساخته شود',titleField:'عنوان محتوا',body:'متن محتوا',hook:'شروع جذاب',cta:'دعوت به اقدام',hashtags:'هشتگ‌ها',notChecked:'هنوز بررسی نشده',completePulse:'برای فعال‌شدن قوانین برند، پالس برند را کامل کنید.',readOnly:'محتوای منتشرشده قابل ویرایش نیست.',selectWarn:'قبل از بازکردن پیش‌نویس دیگر، تغییرات را ذخیره یا لغو کنید.',scheduleApproved:'قبل از زمان‌بندی، پیش‌نویس را تأیید کنید.',future:'تاریخ و زمان آینده را انتخاب کنید.',emptySearch:'پیش‌نویسی با این جست‌وجو پیدا نشد.',retry:'تلاش دوباره',saveFailed:'ذخیره پیش‌نویس انجام نشد.',required:'هدف، کانال و توضیح تولید الزامی است.',generated:'پیش‌نویس ساخته شد',generationFailed:'تولید پیش‌نویس انجام نشد.',updated:'پیش‌نویس به‌روزرسانی شد.',transformFailed:'ویرایش پیش‌نویس انجام نشد.',complianceFailed:'بررسی انطباق انجام نشد.',approvalSent:'برای تأیید ارسال شد',approvalFailed:'ابتدا یک روش تأیید متصل کنید.',scheduled:'پیش‌نویس زمان‌بندی شد.',schedulingFailed:'زمان‌بندی انجام نشد.',exportFailed:'ساخت خروجی انجام نشد.',archiveConfirm:'این پیش‌نویس آرشیو شود؟',untitled:'پیش‌نویس بدون عنوان',characters:'نویسه',notSaved:'ذخیره نشده',translate:'ترجمه',warning:'هشدار',previewMeta:'پیش‌نمایش',copyAll:'کپی همه',copied:'کپی شد',date:'تاریخ',time:'زمان',timezone:'منطقه زمانی',details:'بازکردن جزئیات',closeDetails:'بستن جزئیات'},
 de:{title:'Content Studio',sub:'Verwandeln Sie ein echtes Briefing und Brand Pulse in einen prüfbaren, plattformfertigen Entwurf.',none:'Noch kein Entwurf ausgewählt.',generate:'Entwurf generieren',blank:'Neuer Entwurf',save:'Speichern',unsaved:'Nicht gespeichert',saved:'Gespeichert',brief:'Content-Briefing',rules:'Markenregeln',preview:'Content-Vorschau',missing:'Zuerst diese Schritte abschließen',missingSub:'Öffnen und vervollständigen Sie jeden Punkt, um die KI-Generierung freizuschalten.',compliance:'Compliance prüfen',complianceTitle:'Compliance-Status',approval:'Zur Freigabe senden',schedule:'Planen',export:'Content-Paket exportieren',archive:'Archivieren',recent:'Letzte Entwürfe',search:'Entwürfe suchen',goal:'Content-Ziel',channel:'Kanal',language:'Sprache',type:'Content-Format',offer:'Produkt oder Angebot',tone:'Tonalität',prompt:'Generierungsanweisung',titleField:'Titel',body:'Text',hook:'Einstieg',cta:'Handlungsaufforderung',hashtags:'Hashtags',notChecked:'Noch nicht geprüft',completePulse:'Vervollständigen Sie Brand Pulse, um Markenregeln zu aktivieren.',readOnly:'Veröffentlichte Entwürfe sind schreibgeschützt.',selectWarn:'Speichern oder verwerfen Sie Änderungen, bevor Sie einen anderen Entwurf öffnen.',scheduleApproved:'Geben Sie den Entwurf vor der Planung frei.',future:'Wählen Sie ein zukünftiges Datum und eine Uhrzeit.',emptySearch:'Keine Entwürfe entsprechen der Suche.',retry:'Erneut versuchen',saveFailed:'Der Entwurf konnte nicht gespeichert werden.',required:'Ziel, Kanal und Generierungsanweisung sind erforderlich.',generated:'Entwurf generiert',generationFailed:'Der Entwurf konnte nicht generiert werden.',updated:'Entwurf aktualisiert.',transformFailed:'Der Entwurf konnte nicht aktualisiert werden.',complianceFailed:'Compliance-Prüfung fehlgeschlagen.',approvalSent:'Zur Freigabe gesendet',approvalFailed:'Verbinden Sie zuerst eine Freigabemethode.',scheduled:'Entwurf geplant.',schedulingFailed:'Planung fehlgeschlagen.',exportFailed:'Export fehlgeschlagen.',archiveConfirm:'Diesen Entwurf archivieren?',untitled:'Unbenannter Entwurf',characters:'Zeichen',notSaved:'Nicht gespeichert',translate:'Übersetzen',warning:'Warnung',previewMeta:'Vorschau',copyAll:'Alles kopieren',copied:'Kopiert',date:'Datum',time:'Uhrzeit',timezone:'Zeitzone',details:'Details öffnen',closeDetails:'Details schließen'}
};

export default function Page({params}:{params:Promise<{locale:string}>}){
 const {locale}=use(params);
 return <AppShell locale={locale}><Studio locale={locale}/></AppShell>;
}

function Studio({locale}:{locale:string}){
 const c=copies[locale]||copies.en;const toast=useToast();const searchParams=useSearchParams();const router=useRouter();
 const [overview,setOverview]=useState<StudioOverview|null>(null);const [draft,setDraft]=useState<StudioDraft>(blankDraft(locale));const [dirty,setDirty]=useState(false);const [initialLoading,setInitialLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [kit,setKit]=useState('');const [scheduleOpen,setScheduleOpen]=useState(false);const [query,setQuery]=useState('');
 const dir=draft.language==='fa'||locale==='fa'?'rtl':'ltr';const readOnly=draft.status==='published';
 const fail=(e:any,fallback:string)=>locale==='en'?(e?.message||fallback):fallback;

 useEffect(()=>{load(true)},[]);
 useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save()}};window.addEventListener('beforeunload',handler);window.addEventListener('keydown',key);return()=>{window.removeEventListener('beforeunload',handler);window.removeEventListener('keydown',key)}},[dirty,draft]);

 async function load(first=false,preferredId?:number|string){
  if(first)setInitialLoading(true);setError('');
  try{const data=await api.get<StudioOverview>('/studio/overview');setOverview(data);const requested=preferredId||searchParams.get('draft');const forceNew=searchParams.get('new')==='1';if(forceNew){setDraft(blankDraft(data.brand?.primary_language||locale));setDirty(false)}else if(requested){const found=data.drafts.find(x=>String(x.id)===String(requested));setDraft(found||await api.get<StudioDraft>(`/studio/drafts/${requested}`));setDirty(false)}else if(!draft.id&&data.drafts[0]){setDraft(data.drafts[0]);setDirty(false)}}catch(e:any){setError(fail(e,c.retry))}finally{if(first)setInitialLoading(false)}
 }
 function update(key:keyof StudioDraft,value:any){if(readOnly)return toast(c.readOnly);setDraft(current=>({...current,[key]:value}));setDirty(true)}
 function payload(){return {title:draft.title,body:draft.body,hook:draft.hook,cta:draft.cta,hashtags:draft.hashtags,goal:draft.goal,channel:draft.channel,language:draft.language,content_type:draft.content_type,product_or_offer:draft.product_or_offer,tone:draft.tone,prompt:draft.prompt,status:draft.status}}
 function openDraft(next:StudioDraft){if(dirty&&!confirm(c.selectWarn))return;setDraft(next);setDirty(false);setError('');router.replace(`/${locale}/app/content-studio?draft=${next.id}`)}
 function newDraft(){if(dirty&&!confirm(c.selectWarn))return;setDraft(blankDraft(overview?.brand?.primary_language||locale));setDirty(true);router.replace(`/${locale}/app/content-studio?new=1`)}
 async function save(){if(readOnly)return toast(c.readOnly);setBusy('save');setError('');try{const result=draft.id?await api.patch<StudioDraft>(`/studio/drafts/${draft.id}`,payload()):await api.post<StudioDraft>('/studio/drafts',payload());setDraft(result);setDirty(false);toast(c.saved);router.replace(`/${locale}/app/content-studio?draft=${result.id}`);await load(false,result.id);return result}catch(e:any){const message=fail(e,c.saveFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function generate(){if(!overview?.setup.can_generate){toast(c.missing);return}if(!draft.goal?.trim()||!draft.channel||!draft.prompt?.trim()){toast(c.required);return}setBusy('generate');setError('');try{const result=await api.post<{draft:StudioDraft;provider:string}>('/studio/generate',payload());setDraft(result.draft);setDirty(false);toast(locale==='en'?`${c.generated} · ${result.provider}`:c.generated);router.replace(`/${locale}/app/content-studio?draft=${result.draft.id}`);await load(false,result.draft.id)}catch(e:any){const message=fail(e,c.generationFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function ensureSaved(){if(draft.id&&!dirty)return draft;return await save()}
 async function transform(action:string,target_language?:string){const saved=await ensureSaved();if(!saved)return;setBusy(action);setError('');try{const result=await api.post<StudioDraft>(`/studio/drafts/${saved.id}/transform`,{action,target_language});setDraft(result);setDirty(false);toast(c.updated);await load(false,result.id)}catch(e:any){const message=fail(e,c.transformFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function check(){const saved=await ensureSaved();if(!saved)return;setBusy('check');setError('');try{const result=await api.post<any>(`/studio/drafts/${saved.id}/compliance-check`,{});setDraft(result.draft);toast(statusLabel(locale,result.compliance_result.status));await load(false,saved.id)}catch(e:any){const message=fail(e,c.complianceFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function sendApproval(){const saved=await ensureSaved();if(!saved)return;setBusy('approval');setError('');try{const result=await api.post<any>(`/studio/drafts/${saved.id}/send-for-approval`,{});setDraft(result.draft);toast(`${c.approvalSent} #${result.approval_request_id}`);await load(false,saved.id)}catch(e:any){const message=fail(e,c.approvalFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function schedule(event:any){event.preventDefault();const saved=await ensureSaved();if(!saved)return;if(saved.status!=='approved'){toast(c.scheduleApproved);return}const data=new FormData(event.currentTarget);const date=String(data.get('date')||'');const time=String(data.get('time')||'');if(new Date(`${date}T${time}`).getTime()<=Date.now()){toast(c.future);return}setBusy('schedule');setError('');try{const result=await api.post<any>(`/studio/drafts/${saved.id}/schedule`,{date,time,timezone:data.get('timezone'),channel:saved.channel});setDraft(result.draft);setScheduleOpen(false);toast(locale==='en'&&result.warning?result.warning:c.scheduled);await load(false,saved.id)}catch(e:any){const message=fail(e,c.schedulingFailed);setError(message);toast(message)}finally{setBusy('')}}
 async function exportKit(){const saved=await ensureSaved();if(!saved)return;setBusy('export');try{const result=await api.post<any>(`/studio/drafts/${saved.id}/export-assisted-kit`,{});setKit(result.content||'')}catch(e:any){toast(fail(e,c.exportFailed))}finally{setBusy('')}}
 async function archive(){if(!draft.id||!confirm(c.archiveConfirm))return;setBusy('archive');try{await api.delete(`/studio/drafts/${draft.id}`);toast(c.archive);setDraft(blankDraft(overview?.brand?.primary_language||locale));setDirty(false);router.replace(`/${locale}/app/content-studio`);await load()}catch(e:any){toast(fail(e,c.archive))}finally{setBusy('')}}

 const channelOptions=Array.from(new Set([...(overview?.channels||[]),'instagram','telegram','bale','linkedin','google_business','email','blog']));
 const filteredDrafts=useMemo(()=>overview?.drafts.filter(x=>`${x.title} ${x.body} ${x.channel} ${x.status}`.toLowerCase().includes(query.toLowerCase()))||[],[overview,query]);
 const missing=localizeRequirementList(locale,overview?.setup.missing_requirements);
 const maxLength=draft.channel==='instagram'?2200:draft.channel==='linkedin'?3000:draft.channel==='telegram'||draft.channel==='bale'?4096:null;
 const transforms=['rewrite','shorten','more_formal','more_direct'];

 if(initialLoading)return <div className="grid gap-4 lg:grid-cols-3">{[1,2,3].map(item=><div className="panel h-80 animate-pulse" key={item}/>)}</div>;
 return <div className={`${styles.root} studio-page space-y-4 md:space-y-5`}>
  <section className="command-card studio-hero p-4 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end"><div className="min-w-0"><p className="badge max-w-full truncate">{overview?.organization?.name||'Smarbiz'} · {overview?.brand?.name||(locale==='fa'?'بدون برند':locale==='de'?'Keine Marke':'No brand')}</p><h1 className="mt-3 text-3xl font-black sm:text-4xl md:text-5xl">{c.title}</h1><p className="muted mt-2 max-w-3xl text-sm sm:text-base">{c.sub}</p></div><div className="studio-hero-actions lg:ms-auto"><span className={dirty?'badge badge-warn':'badge badge-success'}>{dirty?c.unsaved:c.saved}</span><button className="chip" onClick={newDraft}>{c.blank}</button><button className="btn" disabled={!!busy||readOnly} onClick={save}>{busy==='save'?'…':c.save}</button></div></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><span>{error}</span><button className="chip ms-3" onClick={()=>load()}>{c.retry}</button></div>}
  {!!missing.length&&<section className="studio-requirements"><div><h2 className="text-lg font-black">{c.missing}</h2><p className="muted mt-1 text-sm">{c.missingSub}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{missing.map((item,index)=><a className="studio-requirement-card" href={`/${locale}${normalizeWorkspaceHref(item.action_href)}`} key={item.id}><span className="studio-requirement-index">{index+1}</span><span className="min-w-0 flex-1"><b className="block text-sm">{item.title}</b>{item.description&&<span className="muted mt-1 block text-xs">{item.description}</span>}</span><span aria-hidden="true">←</span></a>)}</div></section>}

  <div className="studio-layout grid gap-4 xl:grid-cols-[22rem_minmax(0,1fr)_24rem]">
   <details className="panel studio-brief h-fit p-4 sm:p-5 xl:sticky xl:top-24" open><summary className="studio-summary"><span><b className="text-xl">{c.brief}</b><span className="muted mt-1 block text-xs">{c.goal}، {c.channel}، {c.prompt}</span></span><span className="summary-chevron">⌄</span></summary><div className="studio-details-body"><div className="mt-4 space-y-3"><Field label={c.goal} value={draft.goal} disabled={readOnly} onChange={(v:string)=>update('goal',v)}/><Select locale={locale} kind="channel" label={c.channel} value={draft.channel} disabled={readOnly} options={channelOptions} onChange={(v:string)=>update('channel',v)}/><Select locale={locale} kind="language" label={c.language} value={draft.language} disabled={readOnly} options={['en','fa','de']} onChange={(v:string)=>update('language',v)}/><Select locale={locale} kind="contentType" label={c.type} value={draft.content_type} disabled={readOnly} options={['post','reel','story','carousel','email','blog','google_update','telegram_post','bale_post']} onChange={(v:string)=>update('content_type',v)}/><Field label={c.offer} value={draft.product_or_offer} disabled={readOnly} list={overview?.products} onChange={(v:string)=>update('product_or_offer',v)}/><Select locale={locale} kind="tone" label={c.tone} value={draft.tone} disabled={readOnly} options={Array.from(new Set([draft.tone||'clear','clear','professional','friendly','formal','direct','playful']))} onChange={(v:string)=>update('tone',v)}/><TextArea label={c.prompt} value={draft.prompt} disabled={readOnly} onChange={(v:string)=>update('prompt',v)}/></div><button disabled={!!busy||readOnly||!overview?.setup.can_generate} className="btn mt-4 w-full disabled:cursor-not-allowed disabled:opacity-50" onClick={generate}>{busy==='generate'?'…':c.generate}</button><div className="mt-6 border-t border-slate-200 pt-5"><b>{c.recent}</b><input className="field my-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/><div className="max-h-72 space-y-2 overflow-auto">{filteredDrafts.length?filteredDrafts.map(item=><button className={`w-full rounded-xl border p-3 text-start ${String(item.id)===String(draft.id)?'border-blue-300 bg-blue-50':'border-slate-200 bg-white'}`} onClick={()=>openDraft(item)} key={item.id}><b className="block truncate">{item.title||c.untitled}</b><div className="mt-1 flex items-center justify-between gap-2"><span className="muted text-xs">{workspaceOptionLabel(locale,'channel',item.channel)}</span><span className="badge">{statusLabel(locale,item.status)}</span></div></button>):<p className="muted rounded-xl bg-slate-50 p-3 text-sm">{c.emptySearch}</p>}</div></div></div></details>

   <section className="panel studio-editor min-w-0 p-4 sm:p-5" dir={dir}>{!draft.id&&!dirty&&!draft.body?<div className="grid min-h-[24rem] place-items-center px-4 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-blue-50 text-3xl">✍️</div><h2 className="mt-5 text-2xl font-black">{c.none}</h2><p className="muted mt-2">{c.sub}</p><button className="btn mt-4" onClick={()=>document.getElementById('studio-prompt')?.focus()}>{c.generate}</button></div></div>:<><input className="field text-xl font-black" disabled={readOnly} placeholder={c.titleField} value={draft.title} onChange={e=>update('title',e.target.value)}/><textarea className="field mt-4 min-h-64 text-base leading-7 sm:min-h-80" disabled={readOnly} placeholder={c.body} value={draft.body} onChange={e=>update('body',e.target.value)}/><div className="muted mt-2 flex flex-wrap justify-between gap-2 text-xs"><span>{draft.body.length}{maxLength?` / ${maxLength}`:''} {c.characters}</span><span>{draft.updated_at?new Date(draft.updated_at).toLocaleString(locale):c.notSaved} · <b>{statusLabel(locale,draft.status)}</b></span></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label={c.hook} value={draft.hook} disabled={readOnly} onChange={(v:string)=>update('hook',v)}/><Field label={c.cta} value={draft.cta} disabled={readOnly} onChange={(v:string)=>update('cta',v)}/><Field label={c.hashtags} value={draft.hashtags} disabled={readOnly} onChange={(v:string)=>update('hashtags',v)}/></div><div className="studio-tools mt-5">{transforms.map(action=><button className="chip" disabled={!!busy||readOnly} onClick={()=>transform(action)} key={action}>{busy===action?'…':workspaceOptionLabel(locale,'transform',action)}</button>)}<select aria-label={c.translate} className="chip" disabled={!!busy||readOnly} defaultValue="" onChange={e=>{if(e.target.value)transform('translate',e.target.value);e.target.value=''}}><option value="">{c.translate}…</option>{['fa','en','de'].map(language=><option value={language} key={language}>{workspaceOptionLabel(locale,'language',language)}</option>)}</select><button className="chip" disabled={!!busy} onClick={check}>{busy==='check'?'…':c.compliance}</button><button className="chip" disabled={!!busy||readOnly||draft.status==='in_review'} onClick={sendApproval}>{busy==='approval'?'…':c.approval}</button><button className="chip" disabled={!!busy||readOnly} onClick={()=>draft.status==='approved'?setScheduleOpen(true):toast(c.scheduleApproved)}>{c.schedule}</button><button className="chip" disabled={!!busy} onClick={exportKit}>{c.export}</button>{draft.id&&draft.status!=='published'&&<button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={archive}>{c.archive}</button>}</div>{readOnly&&<p className="mt-4 rounded-2xl bg-slate-50 p-3 text-sm">{c.readOnly}</p>}</>}</section>

   <aside className="space-y-4"><details className="panel p-4 sm:p-5" open><summary className="studio-summary"><b>{c.rules}</b><span className="summary-chevron">⌄</span></summary><div className="studio-details-body">{overview?.brand_rules.length?overview.brand_rules.map(rule=><div className={`mt-3 rounded-xl p-3 text-sm ${rule.severity==='danger'?'bg-red-50 text-red-800':rule.severity==='warning'?'bg-amber-50 text-amber-900':'bg-slate-50'}`} key={rule.id}><b>{rule.label}</b><p className="mt-1">{rule.description}</p></div>):<p className="muted mt-3">{c.completePulse}</p>}<h3 className="mt-5 font-black">{c.complianceTitle}</h3><span className={`mt-2 ${draft.compliance_result?.status==='passed'?'badge badge-success':draft.compliance_result?.status==='blocked'?'badge border-red-200 bg-red-50 !text-red-700':'badge badge-warn'}`}>{draft.compliance_result?statusLabel(locale,draft.compliance_result.status):c.notChecked}</span>{(draft.compliance_result?.warnings||draft.warnings||[]).map((warning:any,index:number)=><p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800" key={warning.id||index}><b>{warning.title||c.warning}</b><br/>{warning.description||warning.message||String(warning)}</p>)}</div></details><details className="panel p-4 sm:p-5" open><summary className="studio-summary"><b>{c.preview}</b><span className="badge">{workspaceOptionLabel(locale,'channel',draft.channel)}</span></summary><div className="studio-details-body" dir={dir}><div className="mt-3 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-3 border-b border-slate-200 p-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-gradient-to-br from-blue-600 to-cyan-400 font-black text-white">{overview?.brand?.name?.slice(0,1)||'S'}</div><div><b className="text-sm">{overview?.brand?.name||(locale==='fa'?'برند':locale==='de'?'Marke':'Brand')}</b><p className="muted text-xs">{c.previewMeta} · {workspaceOptionLabel(locale,'channel',draft.channel)}</p></div></div><div className="whitespace-pre-wrap p-4 text-sm leading-6"><b>{draft.title||c.titleField}</b>{draft.hook&&<p className="mt-3 font-semibold">{draft.hook}</p>}<p className="mt-3">{draft.body||c.body}</p>{draft.cta&&<p className="mt-3 font-semibold">{draft.cta}</p>}{draft.hashtags&&<p className="mt-3 text-blue-700">{draft.hashtags}</p>}</div></div></div></details><HelpAside locale={locale} page="Content Studio"/></aside>
  </div>

  {scheduleOpen&&<Modal title={c.schedule} closeLabel={c.closeDetails} onClose={()=>setScheduleOpen(false)}><form onSubmit={schedule} className="space-y-3"><Field label={c.date} name="date" type="date" min={new Date().toISOString().slice(0,10)} required/><Field label={c.time} name="time" type="time" required/><Field label={c.timezone} name="timezone" defaultValue={Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC'} required/><button className="btn w-full" disabled={busy==='schedule'}>{busy==='schedule'?'…':c.schedule}</button></form></Modal>}
  {kit&&<Modal title={c.export} closeLabel={c.closeDetails} onClose={()=>setKit('')}><textarea className="field min-h-80" value={kit} readOnly/><button className="btn mt-3" onClick={async()=>{await navigator.clipboard.writeText(kit);toast(c.copied)}}>{c.copyAll}</button></Modal>}
 </div>;
}

function Field({label,value,onChange,list,disabled,...inputProps}:any){const id=`field-${String(label).replace(/\s/g,'-')}`;return <label className="block"><b className="text-sm">{label}</b>{list?.length?<><input className="field mt-1" disabled={disabled} list={id} value={value||''} onChange={e=>onChange(e.target.value)} {...inputProps}/><datalist id={id}>{list.map((x:string)=><option key={x}>{x}</option>)}</datalist></>:<input className="field mt-1" disabled={disabled} value={value} onChange={onChange?e=>onChange(e.target.value):undefined} {...inputProps}/>}</label>}
function TextArea({label,value,onChange,disabled}:any){return <label className="block"><b className="text-sm">{label}</b><textarea id="studio-prompt" className="field mt-1 min-h-28" disabled={disabled} value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function Select({locale,kind,label,value,onChange,options,disabled}:any){return <label className="block"><b className="text-sm">{label}</b><select className="field mt-1" disabled={disabled} value={value||''} onChange={e=>onChange(e.target.value)}>{options.map((x:string)=><option key={x} value={x}>{workspaceOptionLabel(locale,kind,x)}</option>)}</select></label>}
function Modal({title,onClose,closeLabel,children}:any){return <div className="fixed inset-0 z-[100] grid items-end bg-slate-900/40 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" onClick={onClose}><div className="panel max-h-[90dvh] w-full overflow-y-auto rounded-b-none p-5 sm:max-w-xl sm:rounded-[22px]" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><b>{title}</b><button aria-label={closeLabel} className="chip" onClick={onClose}>×</button></div>{children}</div></div>}
