export const locales = ['en', 'fa', 'de'] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (v?: string): v is Locale => locales.includes(v as Locale);
export const dir = (locale: string) => locale === 'fa' ? 'rtl' : 'ltr';
export function switchLocalePath(pathname: string, next: Locale) { const parts = pathname.split('/').filter(Boolean); if (isLocale(parts[0])) parts[0] = next; else parts.unshift(next); return '/' + parts.join('/'); }
const en = {
 common:{brand:'BrandFlow AI',organization:'Organization',demoBrand:'Nova Agency / Demo Brand',demo:'Demo',production:'Production',search:'Search campaigns, drafts, jobs, brands…',user:'Demo user',notifications:'Notifications reviewed',command:'Command palette opened'},
 actions:{open:'Open',save:'Save',test:'Test',connect:'Connect',settings:'Settings',viewGuide:'View guide',assisted:'Use assisted publishing',generate:'Generate',generateWeek:'Generate week',createDraft:'Create draft',connectChannel:'Connect channel',openGuide:'Open guide',approve:'Approve',reject:'Reject',requestChanges:'Request changes',next:'Next',back:'Back',skip:'Skip for now',finish:'Finish',goDashboard:'Go to dashboard',inviteApprover:'Invite client approver',sendApproval:'Send approval',schedule:'Schedule',export:'Export',addIdea:'Add idea',regenerate:'Regenerate',copyLink:'Copy public link',sendTelegram:'Send via Telegram',sendBale:'Send via Bale'},
 statuses:{connected:'Connected',mock:'Mock',needsSetup:'Needs setup',assistedOnly:'Assisted only',available:'Available',requiresCredentials:'Requires credentials',pending:'Pending',approved:'Approved',draftReady:'Draft ready',scheduled:'Scheduled',published:'Published',attention:'Needs attention',done:'Done',inProgress:'In progress',notStarted:'Not started',skipped:'Skipped'},
 navigation:{groups:[{title:'Operate',items:[['Dashboard','dashboard'],['Calendar','calendar'],['Content Studio','content-studio'],['Approvals','approvals']]},{title:'Grow',items:[['Campaigns','campaigns'],['Analytics','analytics'],['Reports','reports']]},{title:'Brand System',items:[['Brand DNA','brand-dna'],['Assets','assets'],['Integrations','integrations']]},{title:'Admin',items:[['Settings','settings'],['Super Admin','admin']]}]},
 landing:{nav:['Product','Workflow','Integrations','Use cases','Pricing','FAQ'],hero:'Your brand’s AI content operations cockpit',sub:'Plan, generate, approve, publish, analyze and learn from every content decision in one premium multilingual SaaS command center.',cta:'Start guided setup',login:'Login',cards:['Brandbook to calendar','AI drafts with guardrails','Client approvals','Publishing and insight loops']},
 auth:{loginTitle:'Welcome back to the cockpit',signupTitle:'Create your operations workspace',email:'Email',password:'Password',name:'Name',submitLogin:'Enter demo cockpit',submitSignup:'Create account'},
 onboarding:{title:'Build your AI content operating system',subtitle:'A guided journey that turns brand knowledge into calendars, drafts, approvals, publishing and learning.',steps:['Welcome','Organization setup','Brand basics','Brand voice','Content goals','Channels','Products and services','Compliance and approval','AI setup summary','Finish'],modes:['Business Owner','Agency','Local Business','Ecommerce','Regulated Brand','Persian Market with Telegram/Bale'],loop:['Brandbook','Calendar','Content','Approval','Publishing','Insights','Learning'],why:'Why this matters',whyText:'BrandFlow uses these answers to create safer drafts, better calendars and clearer setup recommendations.',fields:['Organization name','Team size','Market','Language preference','Timezone','Brand name','Website','Industry','Country','Primary language','Additional languages','Description','Tone','Sales intensity','Emoji usage','Formality','Examples you like','Words to avoid','CTA style','Weekly content frequency','Preferred content types'],summary:['Brand DNA preview','Suggested content pillars','Suggested first weekly calendar','Suggested connector checklist']},
 dashboard:{title:'AI Operations Cockpit',date:'Friday, July 3, 2026',greeting:'Good morning — your content system is ready to operate.',setup:'Setup completion',nextBest:'Next best action',nextBestText:'Connect one approval channel, then generate the next weekly calendar.',timeline:'Content operations timeline',kpis:['Drafts waiting approval','Calendar completion','Connected channels','AI credits','Engagement score','Conversion signals','Quality warnings','Learning notes'],approvals:'Approval queue',memory:'Brand Memory feed',health:'Channel health',insight:'Weekly insight recommendation',worked:'Telegram offer posts created the strongest conversion signal.',next:'Turn approval comments into Brand Memory and regenerate the week.'},
 checklist:{title:'Guided setup checklist',assistant:'Setup Assistant',assistantText:'The fastest path is to finish Brand DNA, connect Telegram or Google Business, then generate a first week.',items:['Create your first brand','Complete Brand DNA','Add products/services','Connect first publishing channel','Connect approval channel','Generate first weekly calendar','Generate first content draft','Send first approval','Publish or mark manual publish','View first insight report'],minutes:'min'},
 guides:{what:'What this section does',how:'How to use it',first:'What to do first',mistakes:'Common mistakes',workflow:'Example workflow',related:'Related setup steps',help:'Open Help Center'},
 calendar:{title:'Content Calendar',short:'BrandFlow turns your brand strategy into a weekly publishing plan.',views:['Week board','Month overview','Kanban pipeline','List table'],empty:'Generate your first content week',steps:['Choose your brand and channels.','Generate a week.','Review calendar items.','Generate drafts.','Send items for approval.','Schedule or publish.']},
 contentStudio:{title:'Content Studio',short:'A focused AI workspace for briefs, localized drafts, brand rules and channel previews.',brief:'Brief panel',canvas:'Generated content canvas',rules:'Brand rules and previews',fields:['Goal','Channel','Language','Content type','Product / offer','Tone','Prompt'],help:'How to create better content'},
 approvals:{title:'Approvals',short:'Review, explain and collect clear client decisions before anything goes live.',publicTitle:'Client approval preview',publicShort:'Review what will be published, where it will appear and what each decision means.',revision:'Prompt revision box',learning:'Save learning to memory'},
 integrations:{title:'Connectors',short:'Connect the platforms where BrandFlow publishes, notifies or collects insights.',important:'Some platforms allow direct publishing. Others use assisted publishing until API permissions are approved.',overview:['Direct publishing','Assisted publishing','Analytics','Approval messaging','Ecommerce attribution'],recommended:'Recommended setup path',requirements:'Requirements',works:'Works now',mocked:'Mocked',review:'Needs API review',difficulty:'Setup difficulty',security:'Credentials are stored securely. Demo mode never sends live messages.',modal:'Connector setup',fields:['API token','Account ID / chat_id','Webhook secret','Mock mode'],guides:{telegram:['Create a Telegram bot.','Get token from BotFather.','Add bot to channel/group.','Get chat_id.','Test message.','Enable webhook or polling.'],baleBot:['Create Bale bot / بازو.','Get token.','Add bot to channel/group.','Give permissions.','Add chat_id.','Test send message.','Enable callbacks/webhook or polling.'],baleSafir:['Requires Safir credentials.','Add api-access-key.','Add bot_id.','Confirm phone number consent.','Use for reminders/notifications, not unsolicited bulk messaging.']}},
 help:{title:'Help Center',search:'Search help topics',open:'Open related page',topics:['Getting started','Brand DNA','Calendar generation','Content Studio','Approval workflow','Publishing modes','Direct vs assisted publishing','Telegram setup','Bale Bot setup','Bale Safir setup','Instagram limitations','TikTok limitations','Google Business setup','WooCommerce setup','Analytics and UTM','Brand Memory','Agency workflow','Super Admin']},
 admin:{title:'Super Admin Control Tower',short:'Operate tenants, AI usage, connector health, queues, compliance and feature flags from one command surface.',tabs:['Overview','Organizations','Users','Brands','Plans','AI Usage','Connectors','Jobs','Compliance','Templates','Feature Flags','Audit Logs','System Settings'],health:'System health summary',queue:'Queue monitor'},
 modules:{campaigns:{title:'Campaigns',empty:'Create your first campaign'},assets:{title:'Assets',empty:'Upload your first brand asset'},analytics:{title:'Analytics',empty:'Connect analytics to see your first insight'},brandDna:{title:'Living Brand Brain',empty:'Complete Brand DNA to unlock safer AI drafts'},reports:{title:'Reports',empty:'Generate your first weekly report'},settings:{title:'Settings',empty:'Configure organization, roles and AI providers'}}
};
const fa:any = JSON.parse(JSON.stringify(en)); const de:any = JSON.parse(JSON.stringify(en));
Object.assign(fa.common,{organization:'سازمان',demo:'دمو',production:'تولید',search:'جستجوی کمپین، پیش‌نویس، کار و برند…',user:'کاربر دمو'});Object.assign(fa.landing,{hero:'کابین عملیات محتوای هوشمند برند شما',sub:'برنامه‌ریزی، تولید، تأیید، انتشار، تحلیل و یادگیری در یک مرکز فرماندهی چندزبانه و حرفه‌ای.',cta:'شروع راه‌اندازی راهنما',login:'ورود',nav:['محصول','جریان کار','یکپارچه‌سازی‌ها','کاربردها','قیمت','پرسش‌ها']});
Object.assign(fa.actions,{open:'باز کردن',save:'ذخیره',test:'آزمایش',connect:'اتصال',settings:'تنظیمات',viewGuide:'مشاهده راهنما',generate:'تولید',generateWeek:'تولید هفته',createDraft:'ساخت پیش‌نویس',connectChannel:'اتصال کانال',openGuide:'باز کردن راهنما',approve:'تأیید',reject:'رد',requestChanges:'درخواست تغییر',next:'بعدی',back:'قبلی',skip:'فعلاً رد کن',finish:'پایان',goDashboard:'رفتن به داشبورد'});Object.assign(fa.statuses,{connected:'متصل',mock:'دمو',needsSetup:'نیازمند تنظیم',assistedOnly:'فقط کمکی',available:'فعال',requiresCredentials:'نیازمند دسترسی',pending:'در انتظار',approved:'تأیید شده'});
fa.navigation.groups=[{title:'عملیات',items:[['داشبورد','dashboard'],['تقویم','calendar'],['استودیو محتوا','content-studio'],['تأییدها','approvals']]},{title:'رشد',items:[['کمپین‌ها','campaigns'],['تحلیل‌ها','analytics'],['گزارش‌ها','reports']]},{title:'سیستم برند',items:[['DNA برند','brand-dna'],['دارایی‌ها','assets'],['یکپارچه‌سازی‌ها','integrations']]},{title:'مدیریت',items:[['تنظیمات','settings'],['سوپر ادمین','admin']]}];
Object.assign(fa.dashboard,{title:'کابین عملیات هوش مصنوعی',greeting:'صبح بخیر — سیستم محتوای شما آماده عملیات است.',setup:'تکمیل راه‌اندازی',nextBest:'اقدام پیشنهادی بعدی',timeline:'خط زمانی عملیات محتوا',approvals:'صف تأیید',memory:'خوراک حافظه برند',health:'سلامت کانال‌ها'});Object.assign(fa.onboarding,{title:'سیستم عامل محتوای هوشمند خود را بسازید',subtitle:'یک مسیر راهنما که دانش برند را به تقویم، پیش‌نویس، تأیید، انتشار و یادگیری تبدیل می‌کند.'});
Object.assign(fa.integrations,{title:'اتصال‌دهنده‌ها',short:'پلتفرم‌هایی را وصل کنید که BrandFlow در آن‌ها منتشر می‌کند، پیام می‌فرستد یا بینش جمع‌آوری می‌کند.',important:'برخی پلتفرم‌ها انتشار مستقیم دارند؛ برخی تا زمان تأیید API به انتشار کمکی نیاز دارند.'});Object.assign(fa.help,{title:'مرکز راهنما',search:'جستجو در راهنما'});Object.assign(fa.admin,{title:'برج کنترل سوپر ادمین'});
Object.assign(de.landing,{hero:'KI-Operations-Cockpit für Ihre Marke',sub:'Planen, generieren, freigeben, veröffentlichen, analysieren und lernen in einer hochwertigen mehrsprachigen Kommandozentrale.',cta:'Geführtes Setup starten',login:'Anmelden',nav:['Produkt','Workflow','Integrationen','Use Cases','Preise','FAQ']});Object.assign(de.actions,{open:'Öffnen',save:'Speichern',test:'Testen',connect:'Verbinden',settings:'Einstellungen',viewGuide:'Guide ansehen',generate:'Generieren',generateWeek:'Woche generieren',createDraft:'Entwurf erstellen',connectChannel:'Kanal verbinden',openGuide:'Guide öffnen',approve:'Freigeben',reject:'Ablehnen',requestChanges:'Änderungen anfordern',next:'Weiter',back:'Zurück',skip:'Vorerst überspringen',finish:'Fertigstellen'});Object.assign(de.statuses,{connected:'Verbunden',mock:'Demo',needsSetup:'Einrichtung nötig',assistedOnly:'Nur assistiert',available:'Verfügbar',requiresCredentials:'Zugangsdaten nötig',pending:'Ausstehend',approved:'Freigegeben'});Object.assign(de.dashboard,{title:'KI-Operations-Cockpit'});Object.assign(de.admin,{title:'Super-Admin-Kontrollturm'});
export const dictionaries={en,fa,de} as const; export type Dictionary=typeof en;
export function getDictionary(locale:string):Dictionary{return (dictionaries as any)[isLocale(locale)?locale:'en']||en}
export function createTranslator(locale:string){const d:any=getDictionary(locale);return function tr(key:string,fallback=''){const val=key.split('.').reduce((a,k)=>a?.[k],d); if(val==null){if(typeof console!=='undefined')console.warn(`[i18n] Missing key: ${key}`);return fallback||key.split('.').pop()!.replace(/([A-Z])/g,' $1');} return val;}}
export function t(locale:string){return getDictionary(locale)}
