import type {HomeOverview} from './api';

export type ProductLocale='en'|'fa'|'de';
export const productLocale=(value:string):ProductLocale=>value==='fa'||value==='de'?value:'en';

const copy={
 en:{
  shell:{workspace:'Workspace',activation:'Activation',search:'Search pages and actions',next:'Continue setup',notifications:'Notifications',account:'Account',settings:'Settings',help:'Help',logout:'Log out',production:'Production',demo:'Demo',noAlerts:'You are all caught up.',nav:[['Start',[['Home','dashboard'],['Calendar','calendar'],['Content Studio','content-studio'],['Approvals','approvals']]],['Grow',[['Campaigns','campaigns'],['Insights','analytics'],['Reports','reports']]],['Brand system',[['Brand Pulse','brand-pulse'],['Assets','assets'],['Integrations','integrations']]],['Manage',[['Settings','settings'],['Help','help']]]]},
  activation:{eyebrow:'Guided activation',title:'Create your first useful output',subtitle:'Smarbiz becomes valuable after it knows your brand, your offer, where content will be used, and how it should be approved. Complete the next step and we will guide you to a ready-to-use draft.',time:'About 10 minutes to first value',progress:'Activation progress',nextTitle:'Your next best action',continue:'Continue',essentials:'Four essentials Smarbiz needs',essentialsSub:'These inputs keep generated content specific, usable, and safe.',journey:'Path to first value',journeySub:'Do not explore every module yet. Follow this path once.',complete:'Complete',current:'Current',locked:'Next',why:'Why this matters',readyTitle:'Your workspace is activated',readySub:'You now have enough context to plan, create, approve, and learn.',steps:['Teach Smarbiz your business','Generate the first content week','Create and approve the first draft'],stepText:['Brand, audience, offer, channels, and approval rules.','Turn your inputs into a practical weekly plan.','Produce something you can actually review, send, and use.'],welcome:'Setup saved successfully. Now let’s create the first result.'},
  dashboard:{title:'Content operations',subtitle:'What needs attention, what is moving, and what to do next.',activity:'Weekly activity',pipeline:'Content pipeline',recent:'Recent work',empty:'Nothing here yet',open:'Open',generated:'Generated · approved · published',setup:'Setup health',memory:'Brand memory',channels:'Channel health'},
  setup:{brand:{title:'Brand foundation',description:'Name, market, positioning, and business context.',why:'Without this, content stays generic.'},pulse:{title:'Audience and voice',description:'Audience, pain points, tone, and writing rules.',why:'This keeps every draft recognizably on-brand.'},offer:{title:'Product or service',description:'The real offer, benefits, proof, and objections.',why:'Useful content needs something concrete to communicate.'},channels:{title:'Content channels',description:'Choose where the content will be used.',why:'Format and constraints change by channel.'},approval:{title:'Approval method',description:'Decide who reviews content and how decisions are recorded.',why:'This turns drafts into an operational workflow.'},week:{title:'First content week',description:'Generate a practical seven-day plan.',why:'This is the bridge from setup to actual work.'},draft:{title:'First usable draft',description:'Create content from your brand and offer.',why:'This is the first visible product result.'},review:{title:'First approval',description:'Send the draft and record a decision.',why:'Approval closes the collaboration loop.'},publish:{title:'First publication',description:'Publish directly or use an assisted kit.',why:'This completes the operating loop.'},insight:{title:'First learning',description:'Review results and improve the next week.',why:'Smarbiz gets better when outcomes return to the system.'}},
 },
 fa:{
  shell:{workspace:'فضای کاری',activation:'فعال‌سازی',search:'جست‌وجوی صفحه یا عملیات',next:'ادامه راه‌اندازی',notifications:'اعلان‌ها',account:'حساب کاربری',settings:'تنظیمات',help:'راهنما',logout:'خروج',production:'نسخه واقعی',demo:'نسخه نمایشی',noAlerts:'همه‌چیز مرتب است.',nav:[['شروع',[['خانه','dashboard'],['تقویم محتوا','calendar'],['استودیوی محتوا','content-studio'],['تأیید محتوا','approvals']]],['رشد',[['کمپین‌ها','campaigns'],['بینش‌ها','analytics'],['گزارش‌ها','reports']]],['هویت برند',[['پالس برند','brand-pulse'],['فایل‌ها و دارایی‌ها','assets'],['اتصال‌ها','integrations']]],['مدیریت',[['تنظیمات','settings'],['راهنما','help']]]]},
  activation:{eyebrow:'مسیر فعال‌سازی',title:'اولین خروجی قابل استفاده را بساز',subtitle:'اسماربیز زمانی ارزش واقعی می‌سازد که کسب‌وکار، پیشنهاد، کانال‌های محتوا و روش تأیید شما را بشناسد. فقط قدم بعدی را انجام بده؛ سیستم تا رسیدن به یک محتوای آماده استفاده راهنمایی‌ات می‌کند.',time:'حدود ۱۰ دقیقه تا اولین نتیجه',progress:'پیشرفت فعال‌سازی',nextTitle:'بهترین اقدام بعدی',continue:'ادامه این مرحله',essentials:'چهار ورودی کلیدی اسماربیز',essentialsSub:'این اطلاعات باعث می‌شوند خروجی‌ها عمومی، مبهم یا غیرقابل استفاده نباشند.',journey:'مسیر رسیدن به ارزش محصول',journeySub:'فعلاً لازم نیست همه بخش‌ها را بگردی؛ این مسیر را یک‌بار تا انتها برو.',complete:'انجام شده',current:'مرحله فعلی',locked:'مرحله بعد',why:'چرا لازم است؟',readyTitle:'فضای کاری آماده استفاده است',readySub:'حالا اطلاعات کافی برای برنامه‌ریزی، تولید، تأیید و یادگیری محتوا وجود دارد.',steps:['شناساندن کسب‌وکار به اسماربیز','ساخت برنامه محتوای هفته اول','ساخت و تأیید اولین محتوا'],stepText:['برند، مخاطب، پیشنهاد، کانال‌ها و قواعد تأیید.','تبدیل اطلاعات شما به یک برنامه هفتگی عملیاتی.','تولید چیزی که واقعاً بتوانید بررسی، ارسال و استفاده کنید.'],welcome:'اطلاعات اولیه ذخیره شد؛ حالا اولین نتیجه را می‌سازیم.'},
  dashboard:{title:'عملیات محتوا',subtitle:'چه چیزی نیاز به توجه دارد، چه کاری جلو رفته و قدم بعدی چیست.',activity:'فعالیت هفتگی',pipeline:'جریان محتوا',recent:'کارهای اخیر',empty:'هنوز موردی وجود ندارد',open:'باز کردن',generated:'تولید · تأیید · انتشار',setup:'سلامت راه‌اندازی',memory:'حافظه برند',channels:'وضعیت کانال‌ها'},
  setup:{brand:{title:'پایه‌های برند',description:'نام، بازار، جایگاه و زمینه کسب‌وکار.',why:'بدون این اطلاعات، محتوا عمومی و شبیه همه می‌شود.'},pulse:{title:'مخاطب و لحن',description:'مخاطب، مسئله‌ها، لحن و قواعد نوشتاری.',why:'این بخش باعث می‌شود خروجی واقعاً متعلق به برند شما باشد.'},offer:{title:'محصول یا خدمت',description:'پیشنهاد واقعی، مزایا، شواهد و اعتراض‌های مشتری.',why:'محتوای کاربردی باید درباره یک پیشنهاد مشخص حرف بزند.'},channels:{title:'کانال‌های محتوا',description:'مشخص کنید محتوا کجا استفاده می‌شود.',why:'قالب و محدودیت هر کانال متفاوت است.'},approval:{title:'روش تأیید محتوا',description:'مشخص کنید چه کسی و چگونه محتوا را بررسی می‌کند.',why:'این مرحله پیش‌نویس را به یک فرایند واقعی تیمی تبدیل می‌کند.'},week:{title:'برنامه هفته اول',description:'یک برنامه عملیاتی هفت‌روزه بسازید.',why:'این پل بین تنظیمات و کار واقعی است.'},draft:{title:'اولین محتوای قابل استفاده',description:'بر اساس برند و پیشنهادتان محتوا بسازید.',why:'اینجا اولین ارزش قابل مشاهده محصول شکل می‌گیرد.'},review:{title:'اولین تأیید',description:'محتوا را ارسال کنید و تصمیم را ثبت کنید.',why:'تأیید، حلقه همکاری را کامل می‌کند.'},publish:{title:'اولین انتشار',description:'مستقیم منتشر کنید یا بسته انتشار بگیرید.',why:'این کار حلقه عملیاتی را می‌بندد.'},insight:{title:'اولین یادگیری',description:'نتیجه را بررسی و هفته بعد را بهتر کنید.',why:'اسماربیز با بازگشت نتیجه‌ها هوشمندتر می‌شود.'}},
 },
 de:{
  shell:{workspace:'Workspace',activation:'Aktivierung',search:'Seiten und Aktionen suchen',next:'Setup fortsetzen',notifications:'Benachrichtigungen',account:'Konto',settings:'Einstellungen',help:'Hilfe',logout:'Abmelden',production:'Produktion',demo:'Demo',noAlerts:'Alles erledigt.',nav:[['Start',[['Startseite','dashboard'],['Kalender','calendar'],['Content Studio','content-studio'],['Freigaben','approvals']]],['Wachstum',[['Kampagnen','campaigns'],['Einblicke','analytics'],['Berichte','reports']]],['Markensystem',[['Brand Pulse','brand-pulse'],['Assets','assets'],['Integrationen','integrations']]],['Verwalten',[['Einstellungen','settings'],['Hilfe','help']]]]},
  activation:{eyebrow:'Geführte Aktivierung',title:'Erstellen Sie das erste nutzbare Ergebnis',subtitle:'Smarbiz liefert Wert, wenn Marke, Angebot, Kanäle und Freigabeprozess bekannt sind. Erledigen Sie den nächsten Schritt; wir führen Sie bis zu einem einsatzbereiten Entwurf.',time:'Etwa 10 Minuten bis zum ersten Nutzen',progress:'Aktivierungsfortschritt',nextTitle:'Nächste beste Aktion',continue:'Fortfahren',essentials:'Vier wichtige Grundlagen',essentialsSub:'Damit Inhalte konkret, nutzbar und sicher werden.',journey:'Weg zum ersten Nutzen',journeySub:'Erkunden Sie noch nicht jedes Modul. Folgen Sie zuerst diesem Weg.',complete:'Erledigt',current:'Aktuell',locked:'Danach',why:'Warum wichtig?',readyTitle:'Workspace ist aktiviert',readySub:'Sie können jetzt planen, erstellen, freigeben und lernen.',steps:['Smarbiz Ihr Geschäft erklären','Erste Content-Woche erzeugen','Ersten Entwurf erstellen und freigeben'],stepText:['Marke, Zielgruppe, Angebot, Kanäle und Freigaberegeln.','Ihre Eingaben werden zu einem praktischen Wochenplan.','Erstellen Sie etwas, das wirklich geprüft und verwendet werden kann.'],welcome:'Setup gespeichert. Jetzt erstellen wir das erste Ergebnis.'},
  dashboard:{title:'Content Operations',subtitle:'Was Aufmerksamkeit braucht, was vorankommt und was als Nächstes zu tun ist.',activity:'Wöchentliche Aktivität',pipeline:'Content-Pipeline',recent:'Aktuelle Arbeit',empty:'Noch keine Einträge',open:'Öffnen',generated:'Erstellt · freigegeben · veröffentlicht',setup:'Setup-Status',memory:'Markengedächtnis',channels:'Kanalstatus'},
  setup:{brand:{title:'Markengrundlage',description:'Name, Markt, Positionierung und Geschäftskontext.',why:'Ohne diese Daten bleiben Inhalte allgemein.'},pulse:{title:'Zielgruppe und Ton',description:'Zielgruppe, Probleme, Ton und Schreibregeln.',why:'So bleibt jeder Entwurf erkennbar markengerecht.'},offer:{title:'Produkt oder Dienstleistung',description:'Reales Angebot, Nutzen, Belege und Einwände.',why:'Nützlicher Content braucht ein konkretes Angebot.'},channels:{title:'Content-Kanäle',description:'Wählen Sie, wo Inhalte eingesetzt werden.',why:'Format und Einschränkungen unterscheiden sich je Kanal.'},approval:{title:'Freigabemethode',description:'Legen Sie fest, wer Inhalte wie prüft.',why:'So wird aus Entwürfen ein echter Workflow.'},week:{title:'Erste Content-Woche',description:'Erstellen Sie einen praktischen Sieben-Tage-Plan.',why:'Die Brücke vom Setup zur echten Arbeit.'},draft:{title:'Erster nutzbarer Entwurf',description:'Erstellen Sie Content aus Marke und Angebot.',why:'Der erste sichtbare Produktnutzen.'},review:{title:'Erste Freigabe',description:'Senden Sie den Entwurf und erfassen Sie die Entscheidung.',why:'Die Freigabe schließt den Kollaborationskreislauf.'},publish:{title:'Erste Veröffentlichung',description:'Direkt oder mit assistiertem Paket veröffentlichen.',why:'Vervollständigt den operativen Kreislauf.'},insight:{title:'Erste Erkenntnis',description:'Ergebnisse prüfen und die nächste Woche verbessern.',why:'Smarbiz lernt aus zurückgespielten Ergebnissen.'}},
 }
} as const;

export const productCopy=(locale:string)=>copy[productLocale(locale)];

type SetupKey=keyof typeof copy.en.setup;
const setupKey=(step:{id?:string;action_href?:string;title?:string}):SetupKey=>{
 const haystack=`${step.id||''} ${step.action_href||''} ${step.title||''}`.toLowerCase();
 if(/insight|learn|analytics/.test(haystack))return 'insight';
 if(/publish/.test(haystack))return 'publish';
 if(/approval|review|approv/.test(haystack))return /send|first approval|request/.test(haystack)?'review':'approval';
 if(/draft|studio/.test(haystack))return 'draft';
 if(/week|calendar/.test(haystack))return 'week';
 if(/channel|integration/.test(haystack))return 'channels';
 if(/product|service|offer/.test(haystack))return 'offer';
 if(/pulse|audience|voice|dna/.test(haystack))return 'pulse';
 return 'brand';
};

const actionLabel=(locale:ProductLocale,key:SetupKey)=>{
 const labels={en:{brand:'Complete brand setup',pulse:'Complete audience and voice',offer:'Add your offer',channels:'Choose channels',approval:'Set approval method',week:'Generate first week',draft:'Create first draft',review:'Send for approval',publish:'Open publishing',insight:'Review insights'},fa:{brand:'تکمیل اطلاعات برند',pulse:'تکمیل مخاطب و لحن',offer:'ثبت محصول یا خدمت',channels:'انتخاب کانال‌ها',approval:'تنظیم روش تأیید',week:'ساخت برنامه هفته اول',draft:'ساخت اولین محتوا',review:'ارسال برای تأیید',publish:'رفتن به انتشار',insight:'بررسی نتیجه‌ها'},de:{brand:'Marken-Setup abschließen',pulse:'Zielgruppe und Ton ergänzen',offer:'Angebot hinzufügen',channels:'Kanäle wählen',approval:'Freigabe einrichten',week:'Erste Woche erzeugen',draft:'Ersten Entwurf erstellen',review:'Zur Freigabe senden',publish:'Veröffentlichung öffnen',insight:'Einblicke prüfen'}} as const;
 return labels[locale][key];
};

export function localizeHomeOverview(localeValue:string,data:HomeOverview):HomeOverview{
 const locale=productLocale(localeValue);const c=copy[locale];
 const steps=data.setup.steps.map(step=>{const key=setupKey(step);const text=c.setup[key];return {...step,title:text.title,description:text.description,action_label:actionLabel(locale,key)};});
 const current=steps.find(step=>step.id===data.setup.first_incomplete_step_id)||steps.find(step=>step.status!=='done');
 const recKey=setupKey(current||data.recommended_action);
 const recommendation={...data.recommended_action,title:c.setup[recKey].title,description:c.setup[recKey].description,action_label:actionLabel(locale,recKey),missing_requirements:(data.recommended_action.missing_requirements||[]).map(item=>translateKnown(locale,item))};
 const pipeline=data.pipeline.map(column=>({...column,label:statusText(locale,column.status,column.label)}));
 const kpis=data.kpis.map(kpi=>({...kpi,label:kpiText(locale,kpi.id,kpi.label),helper:translateKnown(locale,kpi.helper||'')}));
 const alerts=data.alerts.map(alert=>({...alert,title:translateKnown(locale,alert.title),description:translateKnown(locale,alert.description)}));
 return {...data,setup:{...data.setup,steps},recommended_action:recommendation,pipeline,kpis,alerts,memory_summary:data.memory_summary?{...data.memory_summary,title:c.dashboard.memory,description:translateKnown(locale,data.memory_summary.description)}:data.memory_summary,channel_health:data.channel_health?{...data.channel_health,title:c.dashboard.channels,description:translateKnown(locale,data.channel_health.description)}:data.channel_health};
}

function statusText(locale:ProductLocale,status:string,fallback:string){const labels:any={en:{idea:'Ideas',draft:'Drafts',in_review:'In review',approved:'Approved',scheduled:'Scheduled',published:'Published',learned:'Learned'},fa:{idea:'ایده‌ها',draft:'پیش‌نویس‌ها',in_review:'در حال تأیید',approved:'تأییدشده',scheduled:'زمان‌بندی‌شده',published:'منتشرشده',learned:'یادگیری'},de:{idea:'Ideen',draft:'Entwürfe',in_review:'In Freigabe',approved:'Freigegeben',scheduled:'Geplant',published:'Veröffentlicht',learned:'Gelernt'}};return labels[locale][status]||translateKnown(locale,fallback)}
function kpiText(locale:ProductLocale,id:string,fallback:string){const labels:any={en:{drafts:'Drafts',approvals:'Pending approvals',scheduled:'Scheduled',published:'Published',channels:'Connected channels',warnings:'Quality warnings'},fa:{drafts:'پیش‌نویس‌ها',approvals:'تأییدهای منتظر',scheduled:'زمان‌بندی‌شده',published:'منتشرشده',channels:'کانال‌های متصل',warnings:'هشدارهای کیفی'},de:{drafts:'Entwürfe',approvals:'Offene Freigaben',scheduled:'Geplant',published:'Veröffentlicht',channels:'Verbundene Kanäle',warnings:'Qualitätswarnungen'}};const key=Object.keys(labels.en).find(item=>id.toLowerCase().includes(item));return key?labels[locale][key]:translateKnown(locale,fallback)}

const phraseFa:Record<string,string>={
 'Brand Pulse not completed':'پالس برند کامل نشده است','No product/service added':'هنوز محصول یا خدمتی ثبت نشده است','No channels selected':'کانالی انتخاب نشده است','No approval method connected':'روش تأیید محتوا تنظیم نشده است','No publishing connector connected':'کانال انتشار متصل نیست','No analytics connector connected':'منبع داده تحلیلی متصل نیست','Connect analytics or add manual metrics':'یک منبع تحلیل متصل کنید یا شاخص‌ها را دستی وارد کنید','Not enough performance data yet':'هنوز داده عملکرد کافی وجود ندارد','Complete your brand setup':'اطلاعات برند را کامل کنید','Create your first draft':'اولین محتوا را بسازید','Generate your first week':'برنامه هفته اول را بسازید','Connect an approval method':'روش تأیید محتوا را مشخص کنید','No content activity yet.':'هنوز فعالیت محتوایی ثبت نشده است.','No items yet':'هنوز موردی وجود ندارد','Brand setup incomplete':'اطلاعات برند کامل نیست'};
const phraseDe:Record<string,string>={'Brand Pulse not completed':'Brand Pulse ist unvollständig','No product/service added':'Kein Produkt oder Service hinzugefügt','No channels selected':'Keine Kanäle ausgewählt','No approval method connected':'Keine Freigabemethode verbunden','No publishing connector connected':'Kein Veröffentlichungskanal verbunden','No analytics connector connected':'Keine Analytics-Quelle verbunden','Not enough performance data yet':'Noch nicht genügend Leistungsdaten'};
export function translateKnown(locale:ProductLocale,value:string){if(!value)return value;if(locale==='fa')return phraseFa[value]||value;if(locale==='de')return phraseDe[value]||value;return value;}
