'use client';

import {useEffect, useMemo, useRef, useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {statusLabel} from '@/lib/i18n';
import {useToast} from './ui/toast';

type Asset = {id:number;title:string;filename:string;original_filename:string;mime_type:string;asset_type:string;size_bytes:number;status:string;tags:string[];download_url:string;created_at?:string|null;description?:string;alt_text?:string;source?:string};
type AssetOverview = {organization:{id:number;name:string};brand:{id:number;name:string};summary:{total_assets:number;approved_assets:number;draft_assets:number;rejected_assets:number;images_count:number;videos_count:number;documents_count:number;storage_used_bytes:number};assets:Asset[];filters:{asset_types:{id:string;label:string;count:number}[];statuses:{id:string;label:string;count:number}[];tags:{id:string;label:string;count:number}[]};recommended_action:any;alerts:any[]};

const copies:any={
 en:{title:'Asset Library',sub:'Keep approved logos, images, videos, documents, and reusable brand files in one searchable workspace.',upload:'Upload asset',review:'Review drafts',search:'Search by name, filename, description, or tag',allTypes:'All types',allStatuses:'All statuses',newest:'Newest first',oldest:'Oldest first',name:'Name',size:'File size',empty:'No assets yet',emptySub:'Upload the first logo, product image, video, or reference document.',noMatch:'No assets match the current filters.',approve:'Approve',reject:'Reject',archive:'Archive',duplicate:'Duplicate metadata',copy:'Copy protected API path',edit:'Edit details',save:'Save changes',cancel:'Cancel',choose:'Choose a file',uploading:'Uploading…',selected:'Selected file',drafts:'Drafts',approved:'Approved',storage:'Storage',total:'Total',downloadUnavailable:'Direct file delivery is not connected yet. The asset is safely stored, but the current backend download route returns metadata instead of file bytes.',clear:'Clear filters'},
 fa:{title:'کتابخانه دارایی‌ها',sub:'لوگو، تصویر، ویدئو، سند و فایل‌های قابل استفاده برند را در یک فضای قابل جست‌وجو نگه دارید.',upload:'آپلود فایل',review:'بررسی پیش‌نویس‌ها',search:'جست‌وجو با نام، فایل، توضیح یا برچسب',allTypes:'همه نوع‌ها',allStatuses:'همه وضعیت‌ها',newest:'جدیدترین',oldest:'قدیمی‌ترین',name:'نام',size:'حجم فایل',empty:'هنوز فایلی وجود ندارد',emptySub:'اولین لوگو، تصویر محصول، ویدئو یا سند مرجع را آپلود کنید.',noMatch:'فایلی با فیلترهای فعلی پیدا نشد.',approve:'تأیید',reject:'رد',archive:'آرشیو',duplicate:'تکثیر متادیتا',copy:'کپی مسیر محافظت‌شده API',edit:'ویرایش مشخصات',save:'ذخیره تغییرات',cancel:'انصراف',choose:'انتخاب فایل',uploading:'در حال آپلود…',selected:'فایل انتخاب‌شده',drafts:'پیش‌نویس',approved:'تأییدشده',storage:'فضای مصرف‌شده',total:'مجموع',downloadUnavailable:'ارسال مستقیم فایل هنوز در backend متصل نشده است. فایل ذخیره شده، اما مسیر Download فعلی به‌جای بایت فایل فقط متادیتا برمی‌گرداند.',clear:'پاک‌کردن فیلترها'},
 de:{title:'Asset-Bibliothek',sub:'Verwalten Sie freigegebene Logos, Bilder, Videos, Dokumente und wiederverwendbare Markendateien in einem durchsuchbaren Workspace.',upload:'Asset hochladen',review:'Entwürfe prüfen',search:'Nach Name, Datei, Beschreibung oder Tag suchen',allTypes:'Alle Typen',allStatuses:'Alle Status',newest:'Neueste zuerst',oldest:'Älteste zuerst',name:'Name',size:'Dateigröße',empty:'Noch keine Assets',emptySub:'Laden Sie das erste Logo, Produktbild, Video oder Referenzdokument hoch.',noMatch:'Keine Assets entsprechen den aktuellen Filtern.',approve:'Freigeben',reject:'Ablehnen',archive:'Archivieren',duplicate:'Metadaten duplizieren',copy:'Geschützten API-Pfad kopieren',edit:'Details bearbeiten',save:'Änderungen speichern',cancel:'Abbrechen',choose:'Datei auswählen',uploading:'Wird hochgeladen…',selected:'Ausgewählte Datei',drafts:'Entwürfe',approved:'Freigegeben',storage:'Speicher',total:'Gesamt',downloadUnavailable:'Die direkte Dateiauslieferung ist noch nicht verbunden. Das Asset ist gespeichert, aber die aktuelle Download-Route liefert Metadaten statt Dateibytes.',clear:'Filter löschen'}
};
const formatBytes=(bytes:number)=>{if(!bytes)return '0 B';const units=['B','KB','MB','GB'];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return `${(bytes/Math.pow(1024,index)).toFixed(index?1:0)} ${units[index]}`};

export function AssetsPage({locale}:{locale:string}){
 const c=copies[locale]||copies.en;const toast=useToast();const fileInput=useRef<HTMLInputElement>(null);
 const [data,setData]=useState<AssetOverview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [query,setQuery]=useState('');const [type,setType]=useState('');const [status,setStatus]=useState('');const [sort,setSort]=useState('newest');
 const [uploadOpen,setUploadOpen]=useState(false);const [edit,setEdit]=useState<Asset|null>(null);const [file,setFile]=useState<File|null>(null);const [uploadForm,setUploadForm]=useState({title:'',description:'',tags:'',alt_text:'',status:'draft'});const [busy,setBusy]=useState('');
 async function load(){setLoading(true);setError('');try{setData(await api.get<AssetOverview>('/assets/overview'))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const assets=useMemo(()=>{let rows=[...(data?.assets||[])].filter(asset=>{const haystack=`${asset.title} ${asset.filename} ${asset.original_filename} ${asset.description||''} ${(asset.tags||[]).join(' ')}`.toLowerCase();return (!query||haystack.includes(query.toLowerCase()))&&(!type||asset.asset_type===type)&&(!status||asset.status===status)});rows.sort((a,b)=>sort==='oldest'?(a.created_at||'').localeCompare(b.created_at||''):sort==='name'?a.title.localeCompare(b.title):sort==='size'?b.size_bytes-a.size_bytes:(b.created_at||'').localeCompare(a.created_at||''));return rows},[data,query,type,status,sort]);
 function resetUpload(){setFile(null);setUploadForm({title:'',description:'',tags:'',alt_text:'',status:'draft'});if(fileInput.current)fileInput.current.value=''}
 async function upload(){if(!file){toast(c.choose);return}setBusy('upload');try{const body=new FormData();body.set('file',file);body.set('title',uploadForm.title.trim()||file.name);body.set('description',uploadForm.description.trim());body.set('tags',uploadForm.tags);body.set('alt_text',uploadForm.alt_text.trim());body.set('status',uploadForm.status);await api.post('/assets/upload',body);toast(c.upload);setUploadOpen(false);resetUpload();await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function action(asset:Asset,path:string){setBusy(`${path}-${asset.id}`);try{await api.post(`/assets/${asset.id}/${path}`,{});toast(statusLabel(locale,path));await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function saveEdit(){if(!edit)return;setBusy('edit');try{await api.patch(`/assets/${edit.id}`,{title:edit.title,description:edit.description,asset_type:edit.asset_type,tags:edit.tags,alt_text:edit.alt_text,status:edit.status});toast(c.save);setEdit(null);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function copyPath(asset:Asset){try{const result=await api.post<any>(`/assets/${asset.id}/copy-url`,{});await navigator.clipboard.writeText(`${api.baseUrl}${result.url}`);toast(c.copy)}catch(e:any){toast(e?.message||String(e))}}
 if(loading&&!data)return <div className="grid gap-4 md:grid-cols-3">{[1,2,3,4,5,6].map(x=><div key={x} className="card h-56 animate-pulse"/>)}</div>;
 if(error&&!data)return <div className="panel p-8"><h1 className="text-3xl font-black">{c.title}</h1><p className="muted mt-2">{error}</p><button className="btn mt-5" onClick={load}>Retry</button></div>;
 const reviewMode=status==='draft';
 return <div className="space-y-6">
  <section className="command-card p-6"><div className="flex flex-wrap items-start gap-3"><div><p className="badge">{data?.organization.name} · {data?.brand.name}</p><h1 className="mt-3 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-2 max-w-3xl">{c.sub}</p></div><div className="ms-auto flex flex-wrap gap-2"><button className={reviewMode?'btn':'chip'} onClick={()=>setStatus(reviewMode?'':'draft')}>{c.review} {data?.summary.draft_assets?`(${data.summary.draft_assets})`:''}</button><button className="btn" onClick={()=>setUploadOpen(true)}>{c.upload}</button></div></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label={c.total} value={data?.summary.total_assets||0}/><Stat label={c.approved} value={data?.summary.approved_assets||0}/><Stat label={c.drafts} value={data?.summary.draft_assets||0}/><Stat label={c.storage} value={formatBytes(data?.summary.storage_used_bytes||0)}/></section>
  <section className="panel p-4"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_12rem_12rem_auto]"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search}/><select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="">{c.allTypes}</option>{data?.filters.asset_types.filter(x=>x.count).map(x=><option key={x.id} value={x.id}>{x.label} ({x.count})</option>)}</select><select className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="">{c.allStatuses}</option>{data?.filters.statuses.map(x=><option key={x.id} value={x.id}>{statusLabel(locale,x.id)} ({x.count})</option>)}</select><select className="field" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">{c.newest}</option><option value="oldest">{c.oldest}</option><option value="name">{c.name}</option><option value="size">{c.size}</option></select><button className="chip" onClick={()=>{setQuery('');setType('');setStatus('');setSort('newest')}}>{c.clear}</button></div></section>
  {!data?.assets.length?<section className="panel p-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-blue-50 text-3xl">🖼️</div><h2 className="mt-5 text-3xl font-black">{c.empty}</h2><p className="muted mt-2">{c.emptySub}</p><button className="btn mt-5" onClick={()=>setUploadOpen(true)}>{c.upload}</button></section>:!assets.length?<section className="panel p-10 text-center"><h2 className="text-2xl font-black">{c.noMatch}</h2><button className="chip mt-4" onClick={()=>{setQuery('');setType('');setStatus('')}}>{c.clear}</button></section>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.map(asset=><article className="card overflow-hidden p-4" key={asset.id}><div className="grid h-36 place-items-center rounded-2xl bg-slate-50 text-5xl">{asset.asset_type==='image'||asset.asset_type==='logo'?'🖼️':asset.asset_type==='video'?'🎬':asset.asset_type==='audio'?'🎵':'📄'}</div><div className="mt-4 flex items-start gap-3"><div className="min-w-0"><h3 className="truncate font-black">{asset.title}</h3><p className="muted truncate text-xs">{asset.original_filename}</p></div><span className={`ms-auto ${asset.status==='approved'?'badge badge-success':asset.status==='rejected'?'badge border-red-200 bg-red-50 !text-red-700':asset.status==='draft'?'badge badge-warn':'badge'}`}>{statusLabel(locale,asset.status)}</span></div><p className="muted mt-3 line-clamp-2 min-h-12 text-sm">{asset.description||asset.alt_text||asset.mime_type}</p><div className="mt-3 flex flex-wrap gap-1"><span className="badge">{asset.asset_type}</span><span className="badge">{formatBytes(asset.size_bytes)}</span>{asset.tags?.slice(0,3).map(tag=><span className="badge" key={tag}>{tag}</span>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button className="chip" onClick={()=>setEdit({...asset,tags:[...(asset.tags||[])]})}>{c.edit}</button><button className="chip" onClick={()=>copyPath(asset)}>{c.copy}</button>{asset.status!=='approved'&&<button className="chip" disabled={!!busy} onClick={()=>action(asset,'approve')}>{c.approve}</button>}{asset.status!=='rejected'&&<button className="chip" disabled={!!busy} onClick={()=>action(asset,'reject')}>{c.reject}</button>}<button className="chip" disabled={!!busy} onClick={()=>action(asset,'duplicate-metadata')}>{c.duplicate}</button>{asset.status!=='archived'&&<button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={()=>action(asset,'archive')}>{c.archive}</button>}</div><details className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><summary className="cursor-pointer font-bold">Download status</summary><p className="mt-2">{c.downloadUnavailable}</p></details></article>)}</section>}
  <div className="flex justify-center"><Link className="chip" href={`/${locale}/app/content-studio`}>Open Content Studio</Link></div>
  {uploadOpen&&<Modal title={c.upload} onClose={()=>{setUploadOpen(false);resetUpload()}}><div className="space-y-4"><input ref={fileInput} className="field" type="file" accept="image/*,video/*,audio/*,.pdf,.docx,.txt,.md" onChange={e=>{const next=e.target.files?.[0]||null;setFile(next);if(next&&!uploadForm.title)setUploadForm(current=>({...current,title:next.name}))}}/>{file&&<p className="rounded-xl bg-blue-50 p-3 text-sm"><b>{c.selected}:</b> {file.name} · {formatBytes(file.size)}</p>}<Field label="Title" value={uploadForm.title} onChange={(value:string)=>setUploadForm({...uploadForm,title:value})}/><TextArea label="Description" value={uploadForm.description} onChange={(value:string)=>setUploadForm({...uploadForm,description:value})}/><Field label="Tags (comma separated)" value={uploadForm.tags} onChange={(value:string)=>setUploadForm({...uploadForm,tags:value})}/><Field label="Alt text" value={uploadForm.alt_text} onChange={(value:string)=>setUploadForm({...uploadForm,alt_text:value})}/><select className="field" value={uploadForm.status} onChange={e=>setUploadForm({...uploadForm,status:e.target.value})}><option value="draft">Draft</option><option value="approved">Approved</option></select><button className="btn w-full" disabled={!file||busy==='upload'} onClick={upload}>{busy==='upload'?c.uploading:c.upload}</button></div></Modal>}
  {edit&&<Modal title={c.edit} onClose={()=>setEdit(null)}><div className="space-y-4"><Field label="Title" value={edit.title} onChange={(value:string)=>setEdit({...edit,title:value})}/><TextArea label="Description" value={edit.description||''} onChange={(value:string)=>setEdit({...edit,description:value})}/><Field label="Alt text" value={edit.alt_text||''} onChange={(value:string)=>setEdit({...edit,alt_text:value})}/><Field label="Tags" value={(edit.tags||[]).join(', ')} onChange={(value:string)=>setEdit({...edit,tags:value.split(',').map(x=>x.trim()).filter(Boolean)})}/><select className="field" value={edit.asset_type} onChange={e=>setEdit({...edit,asset_type:e.target.value})}>{['image','logo','video','audio','document','other'].map(x=><option key={x}>{x}</option>)}</select><select className="field" value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{['draft','approved','rejected','archived'].map(x=><option key={x}>{x}</option>)}</select><div className="flex justify-end gap-2"><button className="chip" onClick={()=>setEdit(null)}>{c.cancel}</button><button className="btn" disabled={busy==='edit'} onClick={saveEdit}>{c.save}</button></div></div></Modal>}
 </div>
}
function Stat({label,value}:any){return <div className="card p-4"><p className="muted text-sm">{label}</p><b className="mt-2 block text-3xl">{value}</b></div>}
function Field({label,value,onChange}:any){return <label className="block text-sm font-bold">{label}<input className="field mt-2" value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange}:any){return <label className="block text-sm font-bold">{label}<textarea className="field mt-2 min-h-24" value={value||''} onChange={e=>onChange(e.target.value)}/></label>}
function Modal({title,onClose,children}:any){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/35 p-4" onClick={onClose}><section className="panel max-h-[92vh] w-full max-w-xl overflow-auto p-5" onClick={e=>e.stopPropagation()}><div className="mb-5 flex items-center"><h2 className="text-2xl font-black">{title}</h2><button className="chip ms-auto" onClick={onClose}>×</button></div>{children}</section></div>}
