'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {api,getToken} from '@/lib/api';
import {statusLabel} from '@/lib/i18n';
import {useToast} from './ui/toast';

type Asset={id:number;title:string;filename:string;original_filename:string;mime_type:string;asset_type:string;size_bytes:number;status:string;tags:string[];download_url:string;created_at?:string|null;description?:string;alt_text?:string};
type Overview={organization:{name:string};brand:{name:string};summary:{total_assets:number;approved_assets:number;draft_assets:number;storage_used_bytes:number};assets:Asset[];filters:{asset_types:{id:string;label:string;count:number}[];statuses:{id:string;label:string;count:number}[]}};
type EditState={title:string;description:string;alt_text:string;asset_type:string;status:string;tags:string};

const copy:any={
 en:{title:'Asset Library',sub:'Store, review, download, and reuse approved brand files in one searchable workspace.',upload:'Upload asset',review:'Review drafts',search:'Search name, filename, description, or tag',types:'All types',statuses:'All statuses',newest:'Newest first',oldest:'Oldest first',name:'Name',size:'File size',total:'Total',approved:'Approved',drafts:'Drafts',storage:'Storage',empty:'No assets yet',emptySub:'Upload the first logo, product image, video, audio file, or document.',noMatch:'No assets match the filters.',download:'Download',downloading:'Downloading…',edit:'Edit details',approve:'Approve',reject:'Reject',archive:'Archive',duplicate:'Duplicate metadata',save:'Save changes',cancel:'Cancel',clear:'Clear filters',selected:'Selected file',choose:'Choose a file first.',uploading:'Uploading…',downloaded:'Download started.',retry:'Retry',studio:'Open Content Studio',titleField:'Title',description:'Description',tags:'Tags',alt:'Alt text',draft:'Draft',modalClose:'Close',typeLabels:{image:'Image',logo:'Logo',video:'Video',audio:'Audio',document:'Document',other:'Other'}},
 fa:{title:'کتابخانه دارایی‌ها',sub:'فایل‌های برند را در یک فضای قابل جست‌وجو ذخیره، بررسی، دانلود و دوباره استفاده کنید.',upload:'بارگذاری دارایی',review:'بررسی پیش‌نویس‌ها',search:'جست‌وجو با نام، نام فایل، توضیح یا برچسب',types:'همه نوع‌ها',statuses:'همه وضعیت‌ها',newest:'جدیدترین',oldest:'قدیمی‌ترین',name:'نام',size:'حجم فایل',total:'مجموع',approved:'تأییدشده',drafts:'پیش‌نویس',storage:'فضای مصرف‌شده',empty:'هنوز دارایی‌ای وجود ندارد',emptySub:'اولین لوگو، تصویر محصول، ویدئو، صدا یا سند را بارگذاری کنید.',noMatch:'دارایی‌ای با فیلترهای فعلی پیدا نشد.',download:'دانلود',downloading:'در حال دانلود…',edit:'ویرایش مشخصات',approve:'تأیید',reject:'رد',archive:'بایگانی',duplicate:'تکثیر متادیتا',save:'ذخیره تغییرات',cancel:'انصراف',clear:'پاک‌کردن فیلترها',selected:'فایل انتخاب‌شده',choose:'ابتدا یک فایل انتخاب کنید.',uploading:'در حال بارگذاری…',downloaded:'دانلود شروع شد.',retry:'تلاش دوباره',studio:'باز کردن استودیوی محتوا',titleField:'عنوان',description:'توضیحات',tags:'برچسب‌ها',alt:'متن جایگزین تصویر',draft:'پیش‌نویس',modalClose:'بستن',typeLabels:{image:'تصویر',logo:'لوگو',video:'ویدئو',audio:'صدا',document:'سند',other:'سایر'}},
 de:{title:'Asset-Bibliothek',sub:'Speichern, prüfen, laden und verwenden Sie Markendateien in einem durchsuchbaren Workspace.',upload:'Asset hochladen',review:'Entwürfe prüfen',search:'Nach Name, Datei, Beschreibung oder Tag suchen',types:'Alle Typen',statuses:'Alle Status',newest:'Neueste zuerst',oldest:'Älteste zuerst',name:'Name',size:'Dateigröße',total:'Gesamt',approved:'Freigegeben',drafts:'Entwürfe',storage:'Speicher',empty:'Noch keine Assets',emptySub:'Laden Sie das erste Logo, Produktbild, Video, Audio oder Dokument hoch.',noMatch:'Keine Assets entsprechen den Filtern.',download:'Herunterladen',downloading:'Wird geladen…',edit:'Details bearbeiten',approve:'Freigeben',reject:'Ablehnen',archive:'Archivieren',duplicate:'Metadaten duplizieren',save:'Änderungen speichern',cancel:'Abbrechen',clear:'Filter löschen',selected:'Ausgewählte Datei',choose:'Wählen Sie zuerst eine Datei.',uploading:'Wird hochgeladen…',downloaded:'Download gestartet.',retry:'Erneut versuchen',studio:'Content Studio öffnen',titleField:'Titel',description:'Beschreibung',tags:'Tags',alt:'Alternativtext',draft:'Entwurf',modalClose:'Schließen',typeLabels:{image:'Bild',logo:'Logo',video:'Video',audio:'Audio',document:'Dokument',other:'Andere'}}
};

const emptyEdit:EditState={title:'',description:'',alt_text:'',asset_type:'other',status:'draft',tags:''};
const formatBytes=(value:number)=>{if(!value)return'0 B';const units=['B','KB','MB','GB'];const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return`${(value/1024**index).toFixed(index?1:0)} ${units[index]}`};

export function AssetsLibraryV2({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const toast=useToast();const fileInput=useRef<HTMLInputElement>(null);
 const [data,setData]=useState<Overview|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
 const [query,setQuery]=useState('');const [type,setType]=useState('');const [status,setStatus]=useState('');const [sort,setSort]=useState('newest');
 const [uploadOpen,setUploadOpen]=useState(false);const [file,setFile]=useState<File|null>(null);const [upload,setUpload]=useState({title:'',description:'',tags:'',alt_text:'',status:'draft'});
 const [editing,setEditing]=useState<Asset|null>(null);const [edit,setEdit]=useState<EditState>(emptyEdit);

 async function load(){setLoading(true);setError('');try{setData(await api.get<Overview>('/assets/overview'))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{const rows=(data?.assets||[]).filter(asset=>{const haystack=`${asset.title} ${asset.original_filename} ${asset.description||''} ${(asset.tags||[]).join(' ')}`.toLowerCase();return(!query||haystack.includes(query.toLowerCase()))&&(!type||asset.asset_type===type)&&(!status||asset.status===status)});return rows.sort((a,b)=>sort==='oldest'?String(a.created_at||'').localeCompare(String(b.created_at||'')):sort==='name'?a.title.localeCompare(b.title):sort==='size'?b.size_bytes-a.size_bytes:String(b.created_at||'').localeCompare(String(a.created_at||'')))},[data,query,type,status,sort]);
 function resetUpload(){setFile(null);setUpload({title:'',description:'',tags:'',alt_text:'',status:'draft'});if(fileInput.current)fileInput.current.value=''}
 async function submitUpload(){if(!file){toast(c.choose);return}setBusy('upload');try{const body=new FormData();body.set('file',file);body.set('title',upload.title.trim()||file.name);body.set('description',upload.description.trim());body.set('tags',upload.tags);body.set('alt_text',upload.alt_text.trim());body.set('status',upload.status);await api.post('/assets/upload',body);toast(c.upload);setUploadOpen(false);resetUpload();await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function mutate(asset:Asset,action:string){setBusy(`${action}-${asset.id}`);try{await api.post(`/assets/${asset.id}/${action}`,{});toast(statusLabel(locale,action));await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 function startEdit(asset:Asset){setEditing(asset);setEdit({title:asset.title,description:asset.description||'',alt_text:asset.alt_text||'',asset_type:asset.asset_type,status:asset.status,tags:(asset.tags||[]).join(', ')})}
 async function saveEdit(){if(!editing)return;setBusy('edit');try{await api.patch(`/assets/${editing.id}`,{...edit,tags:edit.tags.split(',').map(item=>item.trim()).filter(Boolean)});toast(c.save);setEditing(null);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function download(asset:Asset){setBusy(`download-${asset.id}`);try{const response=await fetch(`${api.baseUrl}/assets/${asset.id}/download`,{headers:{Authorization:`Bearer ${getToken()}`}});if(!response.ok)throw new Error(`${c.download} (${response.status})`);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=asset.original_filename||asset.filename||asset.title;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);toast(c.downloaded)}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}

 if(loading&&!data)return <div className="grid gap-4 md:grid-cols-3">{[1,2,3,4,5,6].map(item=><div className="card h-56 animate-pulse" key={item}/>)}</div>;
 if(error&&!data)return <section className="panel p-8"><h1 className="text-3xl font-black">{c.title}</h1><p className="mt-3 text-red-700">{error}</p><button className="btn mt-5" onClick={load}>{c.retry}</button></section>;
 const review=status==='draft';
 return <div className="space-y-6">
  <section className="command-card p-6"><div className="flex flex-wrap items-start gap-3"><div><p className="badge">{data?.organization.name} · {data?.brand.name}</p><h1 className="mt-3 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-2 max-w-3xl">{c.sub}</p></div><div className="ms-auto flex gap-2"><button className={review?'btn':'chip'} onClick={()=>setStatus(review?'':'draft')}>{c.review}{data?.summary.draft_assets?` (${data.summary.draft_assets})`:''}</button><button className="btn" onClick={()=>setUploadOpen(true)}>{c.upload}</button></div></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label={c.total} value={data?.summary.total_assets||0}/><Stat label={c.approved} value={data?.summary.approved_assets||0}/><Stat label={c.drafts} value={data?.summary.draft_assets||0}/><Stat label={c.storage} value={formatBytes(data?.summary.storage_used_bytes||0)}/></section>
  <section className="panel p-4"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_12rem_12rem_auto]"><input className="field" value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.search}/><select className="field" value={type} onChange={event=>setType(event.target.value)}><option value="">{c.types}</option>{data?.filters.asset_types.filter(item=>item.count).map(item=><option value={item.id} key={item.id}>{c.typeLabels[item.id]||item.label} ({item.count})</option>)}</select><select className="field" value={status} onChange={event=>setStatus(event.target.value)}><option value="">{c.statuses}</option>{data?.filters.statuses.map(item=><option value={item.id} key={item.id}>{statusLabel(locale,item.id)} ({item.count})</option>)}</select><select className="field" value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">{c.newest}</option><option value="oldest">{c.oldest}</option><option value="name">{c.name}</option><option value="size">{c.size}</option></select><button className="chip" onClick={()=>{setQuery('');setType('');setStatus('');setSort('newest')}}>{c.clear}</button></div></section>
  {!data?.assets.length?<Empty c={c} action={()=>setUploadOpen(true)}/>:!visible.length?<section className="panel p-10 text-center"><h2 className="text-2xl font-black">{c.noMatch}</h2><button className="chip mt-4" onClick={()=>{setQuery('');setType('');setStatus('')}}>{c.clear}</button></section>:<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map(asset=><article className="card p-4" key={asset.id}><div className="grid h-36 place-items-center rounded-2xl bg-slate-50 text-5xl">{assetIcon(asset.asset_type)}</div><div className="mt-4 flex items-start gap-3"><div className="min-w-0"><h3 className="truncate font-black">{asset.title}</h3><p className="muted truncate text-xs">{asset.original_filename}</p></div><span className="badge ms-auto">{statusLabel(locale,asset.status)}</span></div><p className="muted mt-3 line-clamp-2 min-h-12 text-sm">{asset.description||asset.alt_text||asset.mime_type}</p><div className="mt-3 flex flex-wrap gap-1"><span className="badge">{c.typeLabels[asset.asset_type]||asset.asset_type}</span><span className="badge">{formatBytes(asset.size_bytes)}</span>{asset.tags?.slice(0,3).map(tag=><span className="badge" key={tag}>{tag}</span>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button className="btn" disabled={!!busy} onClick={()=>download(asset)}>{busy===`download-${asset.id}`?c.downloading:c.download}</button><button className="chip" onClick={()=>startEdit(asset)}>{c.edit}</button>{asset.status!=='approved'&&<button className="chip" disabled={!!busy} onClick={()=>mutate(asset,'approve')}>{c.approve}</button>}{asset.status!=='rejected'&&<button className="chip" disabled={!!busy} onClick={()=>mutate(asset,'reject')}>{c.reject}</button>}<button className="chip" disabled={!!busy} onClick={()=>mutate(asset,'duplicate-metadata')}>{c.duplicate}</button>{asset.status!=='archived'&&<button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={()=>mutate(asset,'archive')}>{c.archive}</button>}</div></article>)}</section>}
  <div className="flex justify-center"><Link className="chip" href={`/${locale}/app/content-studio`}>{c.studio}</Link></div>
  {uploadOpen&&<Modal title={c.upload} close={()=>{setUploadOpen(false);resetUpload()}} closeLabel={c.modalClose}><div className="space-y-4"><input ref={fileInput} className="field" type="file" accept="image/*,video/*,audio/*,.pdf,.docx,.txt,.md" onChange={event=>{const selected=event.target.files?.[0]||null;setFile(selected);if(selected&&!upload.title)setUpload(current=>({...current,title:selected.name}))}}/>{file&&<p className="rounded-xl bg-blue-50 p-3 text-sm"><b>{c.selected}:</b> {file.name} · {formatBytes(file.size)}</p>}<Field label={c.titleField} value={upload.title} onChange={(value:string)=>setUpload({...upload,title:value})}/><Area label={c.description} value={upload.description} onChange={(value:string)=>setUpload({...upload,description:value})}/><Field label={c.tags} value={upload.tags} onChange={(value:string)=>setUpload({...upload,tags:value})}/><Field label={c.alt} value={upload.alt_text} onChange={(value:string)=>setUpload({...upload,alt_text:value})}/><select className="field" value={upload.status} onChange={event=>setUpload({...upload,status:event.target.value})}><option value="draft">{statusLabel(locale,'draft')}</option><option value="approved">{statusLabel(locale,'approved')}</option></select><button className="btn w-full" disabled={!file||busy==='upload'} onClick={submitUpload}>{busy==='upload'?c.uploading:c.upload}</button></div></Modal>}
  {editing&&<Modal title={c.edit} close={()=>setEditing(null)} closeLabel={c.modalClose}><div className="space-y-4"><Field label={c.titleField} value={edit.title} onChange={(value:string)=>setEdit({...edit,title:value})}/><Area label={c.description} value={edit.description} onChange={(value:string)=>setEdit({...edit,description:value})}/><Field label={c.alt} value={edit.alt_text} onChange={(value:string)=>setEdit({...edit,alt_text:value})}/><Field label={c.tags} value={edit.tags} onChange={(value:string)=>setEdit({...edit,tags:value})}/><select className="field" value={edit.asset_type} onChange={event=>setEdit({...edit,asset_type:event.target.value})}>{['image','logo','video','audio','document','other'].map(value=><option value={value} key={value}>{c.typeLabels[value]||value}</option>)}</select><select className="field" value={edit.status} onChange={event=>setEdit({...edit,status:event.target.value})}>{['draft','approved','rejected','archived'].map(value=><option value={value} key={value}>{statusLabel(locale,value)}</option>)}</select><div className="flex justify-end gap-2"><button className="chip" onClick={()=>setEditing(null)}>{c.cancel}</button><button className="btn" disabled={busy==='edit'} onClick={saveEdit}>{c.save}</button></div></div></Modal>}
 </div>;
}

function assetIcon(type:string){return type==='image'||type==='logo'?'🖼️':type==='video'?'🎬':type==='audio'?'🎵':'📄'}
function Stat({label,value}:any){return <div className="card p-4"><p className="muted text-sm">{label}</p><b className="mt-2 block text-3xl">{value}</b></div>}
function Empty({c,action}:any){return <section className="panel p-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-blue-50 text-3xl">🖼️</div><h2 className="mt-5 text-3xl font-black">{c.empty}</h2><p className="muted mt-2">{c.emptySub}</p><button className="btn mt-5" onClick={action}>{c.upload}</button></section>}
function Field({label,value,onChange}:any){return <label className="block text-sm font-bold">{label}<input className="field mt-2" value={value||''} onChange={event=>onChange(event.target.value)}/></label>}
function Area({label,value,onChange}:any){return <label className="block text-sm font-bold">{label}<textarea className="field mt-2 min-h-24" value={value||''} onChange={event=>onChange(event.target.value)}/></label>}
function Modal({title,close,closeLabel,children}:any){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4" onClick={close}><section role="dialog" aria-modal="true" aria-label={title} className="panel max-h-[92vh] w-full max-w-xl overflow-auto p-5" onClick={event=>event.stopPropagation()}><div className="mb-5 flex items-center"><h2 className="text-2xl font-black">{title}</h2><button aria-label={closeLabel} className="chip ms-auto" onClick={close}>×</button></div>{children}</section></div>}
