'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {useToast} from './ui/toast';
import {statusLabel} from '@/lib/i18n';
import {brandPulseFieldLabel,brandPulseGroupLabel,brandPulseStatic,localizeBrandPulseAction} from '@/lib/brand-pulse-localization';
import {localizeRequirementList,normalizeWorkspaceHref,workspaceOptionLabel} from '@/lib/workspace-localization';

type Kind='product'|'persona'|'rule'|'memory';
type Overview={organization:any;brand:any;pulse:any;products:any[];personas:any[];rules:any[];memory:any[];setup:{completion_percent:number;missing_requirements:any[]};recommended_action:any;alerts:any[]};
type Editor={kind:Kind;id?:number;values:Record<string,any>};
type FieldDef={key:string;label:string;type?:'select'|'boolean';options?:string[];wide?:boolean;optionKind?:'language'|'channel'};

const multiple=new Set(['audience_pain_points','desired_outcomes','buyer_objections','do_say','dont_say','content_pillars','value_propositions','competitors','proof_points','cta_preferences','hashtags_keywords','forbidden_claims','required_disclaimers','channel_notes','benefits','objections','pains','desires','preferred_channels','tags']);
const pulseGroups=[['Brand basics',['brand_name','website_url','industry','country','primary_language','timezone','brand_summary','mission','positioning']],['Audience',['target_audience','audience_pain_points','desired_outcomes','buyer_objections']],['Voice and style',['tone_of_voice','writing_style','do_say','dont_say','cta_preferences','hashtags_keywords']],['Offer and positioning',['value_propositions','differentiation','competitors','proof_points']],['Rules and compliance',['forbidden_claims','required_disclaimers','approval_preferences','channel_notes']],['Content pillars',['content_pillars']]] as const;

const copy:any={
 en:{title:'Brand Pulse',sub:'Keep the living knowledge base that guides every draft, campaign, approval, insight, and report.',save:'Save Brand Pulse',saving:'Saving…',product:'Products and services',persona:'Personas',rule:'Brand rules',memory:'Memory notes',add:'Add',edit:'Edit',delete:'Delete',deleteConfirm:'Delete this item?',archiveConfirm:'Archive this product or service?',export:'Export JSON',import:'Import JSON',importInvalid:'The selected file is not valid Brand Pulse JSON.',imported:'Brand Pulse imported.',exported:'Brand Pulse exported.',saved:'Brand Pulse saved.',empty:'No items yet.',completion:'Completion',manualSite:'Website analysis is not connected yet. Enter verified information manually instead of generating unverified claims.',starter:'Use starter suggestions',starterConfirm:'This can replace some fields with generic starter suggestions. Continue?',nameRequired:'Name or text is required.',active:'Active',archived:'Archived',openStudio:'Open Content Studio',missing:'Complete these setup steps',missingSub:'Finishing them improves generation quality across the workspace.',retry:'Retry',knowledgeSub:'Open each section and add only information that is true for this brand.',guide:'Recommended next step',searchPlaceholder:'Search products, personas, rules, and memories',cancel:'Cancel',close:'Close',saveItem:'Save item',loadingError:'Brand Pulse could not be loaded.',saveError:'Brand Pulse could not be saved.',itemError:'The item could not be saved.',removeError:'The item could not be removed.',sectionComplete:'section',fields:'fields',builder:'Brand knowledge builder'},
 fa:{title:'پالس برند',sub:'پایگاه دانشی را کامل نگه دارید که همه پیش‌نویس‌ها، کمپین‌ها، تأییدها، بینش‌ها و گزارش‌ها از آن استفاده می‌کنند.',save:'ذخیره پالس برند',saving:'در حال ذخیره…',product:'محصول‌ها و خدمات',persona:'پرسوناها',rule:'قوانین برند',memory:'یادداشت‌های حافظه',add:'افزودن',edit:'ویرایش',delete:'حذف',deleteConfirm:'این مورد حذف شود؟',archiveConfirm:'این محصول یا خدمت آرشیو شود؟',export:'دریافت فایل JSON',import:'ورود فایل JSON',importInvalid:'فایل انتخاب‌شده JSON معتبر پالس برند نیست.',imported:'پالس برند وارد شد.',exported:'فایل پالس برند ساخته شد.',saved:'پالس برند ذخیره شد.',empty:'هنوز موردی ثبت نشده است.',completion:'درصد تکمیل',manualSite:'تحلیل خودکار وب‌سایت هنوز متصل نیست. اطلاعات واقعی و تأییدشده را دستی وارد کنید.',starter:'پیشنهادهای اولیه',starterConfirm:'این کار ممکن است بعضی فیلدها را با پیشنهادهای عمومی جایگزین کند. ادامه می‌دهید؟',nameRequired:'نام یا متن الزامی است.',active:'فعال',archived:'آرشیو شد',openStudio:'بازکردن استودیوی محتوا',missing:'این مراحل را کامل کنید',missingSub:'تکمیل این موارد، دقت تولید محتوا در تمام بخش‌ها را بهتر می‌کند.',retry:'تلاش دوباره',knowledgeSub:'هر بخش را باز کنید و فقط اطلاعات واقعی همین برند را وارد کنید.',guide:'پیشنهاد مرحله بعد',searchPlaceholder:'جست‌وجو میان محصول‌ها، پرسوناها، قوانین و حافظه',cancel:'انصراف',close:'بستن',saveItem:'ذخیره مورد',loadingError:'پالس برند بارگذاری نشد.',saveError:'ذخیره پالس برند انجام نشد.',itemError:'ذخیره این مورد انجام نشد.',removeError:'حذف این مورد انجام نشد.',sectionComplete:'بخش',fields:'فیلد',builder:'سازنده دانش برند'},
 de:{title:'Brand Pulse',sub:'Pflegen Sie die Wissensbasis, die alle Entwürfe, Kampagnen, Freigaben, Insights und Berichte steuert.',save:'Brand Pulse speichern',saving:'Wird gespeichert…',product:'Produkte und Services',persona:'Personas',rule:'Markenregeln',memory:'Memory-Notizen',add:'Hinzufügen',edit:'Bearbeiten',delete:'Löschen',deleteConfirm:'Dieses Element löschen?',archiveConfirm:'Dieses Produkt oder diesen Service archivieren?',export:'JSON exportieren',import:'JSON importieren',importInvalid:'Die ausgewählte Datei enthält kein gültiges Brand-Pulse-JSON.',imported:'Brand Pulse importiert.',exported:'Brand Pulse exportiert.',saved:'Brand Pulse gespeichert.',empty:'Noch keine Einträge.',completion:'Fortschritt',manualSite:'Die Website-Analyse ist noch nicht verbunden. Tragen Sie nur verifizierte Informationen manuell ein.',starter:'Starter-Vorschläge',starterConfirm:'Einige Felder können durch allgemeine Vorschläge ersetzt werden. Fortfahren?',nameRequired:'Name oder Text ist erforderlich.',active:'Aktiv',archived:'Archiviert',openStudio:'Content Studio öffnen',missing:'Diese Schritte abschließen',missingSub:'Dadurch wird die Generierungsqualität im gesamten Workspace verbessert.',retry:'Erneut versuchen',knowledgeSub:'Öffnen Sie jeden Bereich und tragen Sie nur echte Markeninformationen ein.',guide:'Empfohlener nächster Schritt',searchPlaceholder:'Produkte, Personas, Regeln und Erinnerungen durchsuchen',cancel:'Abbrechen',close:'Schließen',saveItem:'Element speichern',loadingError:'Brand Pulse konnte nicht geladen werden.',saveError:'Brand Pulse konnte nicht gespeichert werden.',itemError:'Das Element konnte nicht gespeichert werden.',removeError:'Das Element konnte nicht entfernt werden.',sectionComplete:'Bereich',fields:'Felder',builder:'Markenwissen aufbauen'}
};

const editorLabels:any={
 en:{name:'Name',type:'Type',status:'Status',price_text:'Price',description:'Description',benefits:'Benefits',audience:'Audience',objections:'Objections',proof_points:'Proof points',segment:'Segment',language:'Language',pains:'Pain points',desires:'Desired outcomes',preferred_channels:'Preferred channels',title:'Title',category:'Category',severity:'Severity',applies_to_channel:'Channel',is_active:'Active',text:'Memory text',source:'Source',tags:'Tags',product:'Product',service:'Service',offer:'Offer',draft:'Draft',voice:'Voice',compliance:'Compliance',visual:'Visual',channel:'Channel',approval:'Approval',info:'Information',warning:'Warning',danger:'Critical'},
 fa:{name:'نام',type:'نوع',status:'وضعیت',price_text:'قیمت',description:'توضیحات',benefits:'مزایا',audience:'مخاطب',objections:'تردیدها و اعتراض‌ها',proof_points:'شواهد و نقاط اثبات',segment:'بخش مخاطب',language:'زبان',pains:'مسئله‌ها و دردها',desires:'نتیجه‌های مطلوب',preferred_channels:'کانال‌های ترجیحی',title:'عنوان',category:'دسته قانون',severity:'اهمیت',applies_to_channel:'کانال مرتبط',is_active:'فعال باشد',text:'متن حافظه',source:'منبع',tags:'برچسب‌ها',product:'محصول',service:'خدمت',offer:'پیشنهاد',draft:'پیش‌نویس',voice:'لحن و صدا',compliance:'الزامات',visual:'هویت بصری',channel:'کانال',approval:'تأیید',info:'اطلاع‌رسانی',warning:'هشدار',danger:'حیاتی'},
 de:{name:'Name',type:'Typ',status:'Status',price_text:'Preis',description:'Beschreibung',benefits:'Vorteile',audience:'Zielgruppe',objections:'Einwände',proof_points:'Nachweise',segment:'Segment',language:'Sprache',pains:'Probleme',desires:'Ziele',preferred_channels:'Bevorzugte Kanäle',title:'Titel',category:'Kategorie',severity:'Priorität',applies_to_channel:'Kanal',is_active:'Aktiv',text:'Memory-Text',source:'Quelle',tags:'Tags',product:'Produkt',service:'Service',offer:'Angebot',draft:'Entwurf',voice:'Tonalität',compliance:'Compliance',visual:'Visuell',channel:'Kanal',approval:'Freigabe',info:'Information',warning:'Warnung',danger:'Kritisch'}
};

export function BrandPulseWorkspace({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const toast=useToast();const inputRef=useRef<HTMLInputElement>(null);
 const [data,setData]=useState<Overview|null>(null);const [form,setForm]=useState<Record<string,any>>({});const [editor,setEditor]=useState<Editor|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [query,setQuery]=useState('');
 const fail=(e:any,fallback:string)=>locale==='en'?(e?.message||fallback):fallback;
 async function load(){setLoading(true);setError('');try{const result=await api.get<Overview>('/brand-pulse/overview');setData(result);setForm(result.pulse||{brand_name:result.brand?.name||'',website_url:result.brand?.website_url||'',industry:result.brand?.industry||'',country:result.brand?.country||'',primary_language:result.brand?.primary_language||locale,timezone:result.brand?.timezone||'UTC'})}catch(e:any){setError(fail(e,c.loadingError))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function setField(key:string,value:any){setForm(current=>({...current,[key]:value}))}
 async function savePulse(){setBusy('pulse');try{await api.patch('/brand-pulse',form);toast(c.saved);await load()}catch(e:any){toast(fail(e,c.saveError))}finally{setBusy('')}}
 async function starter(){if(!confirm(c.starterConfirm))return;setBusy('starter');try{const result=await api.post<Overview>('/brand-pulse/generate-from-answers',{});setData(result);setForm(result.pulse||{});toast(c.saved)}catch(e:any){toast(fail(e,c.saveError))}finally{setBusy('starter')}}
 function start(kind:Kind,item?:any){const values=item?{...item}:{...defaults(kind)};if(kind==='memory'&&values.note&&!values.text)values.text=values.note;setEditor({kind,id:item?.id,values})}
 async function saveItem(){if(!editor)return;const key=editor.kind==='memory'?'text':'name';if(!String(editor.values[key]||editor.values.title||'').trim()){toast(c.nameRequired);return}setBusy('item');try{const root=pathFor(editor.kind);const payload=normalize(editor.kind,editor.values);if(editor.id)await api.patch(`${root}/${editor.id}`,payload);else await api.post(root,payload);toast(c.saved);setEditor(null);await load()}catch(e:any){toast(fail(e,c.itemError))}finally{setBusy('')}}
 async function remove(kind:Kind,item:any){const archived=kind==='product';if(!confirm(archived?c.archiveConfirm:c.deleteConfirm))return;setBusy(`delete-${kind}-${item.id}`);try{await api.delete(`${pathFor(kind)}/${item.id}`);toast(archived?c.archived:c.delete);await load()}catch(e:any){toast(fail(e,c.removeError))}finally{setBusy('')}}
 async function exportJson(){setBusy('export');try{const result=await api.post<any>('/brand-pulse/export',{});const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${slug(data?.brand?.name||'brand')}-brand-pulse.json`;link.click();URL.revokeObjectURL(url);toast(c.exported)}catch(e:any){toast(fail(e,c.exported))}finally{setBusy('')}}
 async function importJson(file:File|null){if(!file)return;setBusy('import');try{const parsed=JSON.parse(await file.text());const payload=parsed.pulse||parsed;if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error(c.importInvalid);await api.post('/brand-pulse/import',payload);toast(c.imported);await load()}catch(e:any){toast(locale==='en'?(e?.message||c.importInvalid):c.importInvalid)}finally{setBusy('');if(inputRef.current)inputRef.current.value=''}}

 const collections=useMemo(()=>({product:data?.products||[],persona:data?.personas||[],rule:data?.rules||[],memory:data?.memory||[]}),[data]);
 const missing=localizeRequirementList(locale,data?.setup.missing_requirements);
 const recommended=localizeBrandPulseAction(locale,data?.recommended_action);
 if(loading&&!data)return <div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map(item=><div className="panel h-64 animate-pulse" key={item}/>)}</div>;
 if(error&&!data)return <section className="panel p-8"><h1 className="text-3xl font-black">{c.title}</h1><p className="mt-3 text-red-700">{error}</p><button className="btn mt-5" onClick={load}>{c.retry}</button></section>;

 return <div className="brand-pulse-page space-y-4 md:space-y-5">
  <section className="command-card brand-pulse-hero p-4 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end"><div className="min-w-0"><p className="badge max-w-full truncate">{data?.organization?.name} · {data?.brand?.name}</p><h1 className="mt-3 text-3xl font-black sm:text-4xl md:text-5xl">{c.title}</h1><p className="muted mt-2 max-w-4xl text-sm sm:text-base">{c.sub}</p></div><div className="brand-pulse-actions lg:ms-auto"><button className="btn" disabled={busy==='pulse'} onClick={savePulse}>{busy==='pulse'?c.saving:c.save}</button><button className="chip" disabled={!!busy} onClick={exportJson}>{c.export}</button><label className="chip cursor-pointer">{c.import}<input ref={inputRef} className="hidden" type="file" accept="application/json,.json" onChange={event=>importJson(event.target.files?.[0]||null)}/></label></div></div><div className="mt-5 flex items-center gap-3"><div className="progress-track min-w-0 flex-1"><div className="progress-fill" style={{width:`${data?.setup.completion_percent||0}%`}}/></div><span className="badge badge-warn shrink-0">{data?.setup.completion_percent||0}%</span></div></section>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
  {!!missing.length&&<section className="brand-pulse-missing"><div><h2 className="text-lg font-black">{c.missing}</h2><p className="muted mt-1 text-sm">{c.missingSub}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{missing.map((item,index)=><Link className="studio-requirement-card" href={`/${locale}${normalizeWorkspaceHref(item.action_href)}`} key={item.id}><span className="studio-requirement-index">{index+1}</span><span className="min-w-0 flex-1"><b className="block text-sm">{item.title}</b>{item.description&&<span className="muted mt-1 block text-xs">{item.description}</span>}</span><span aria-hidden="true">←</span></Link>)}</div></section>}

  <div className="brand-pulse-layout grid gap-4 xl:grid-cols-[minmax(0,1fr)_21rem]">
   <main className="space-y-4"><section className="panel brand-pulse-builder p-4 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div><p className="badge">{c.builder}</p><h2 className="mt-2 text-2xl font-black">{brandPulseStatic(locale,'knowledge')}</h2><p className="muted mt-1 text-sm">{c.knowledgeSub}</p></div><button className="chip sm:ms-auto" disabled={!!busy} onClick={starter}>{c.starter}</button></div><p className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{c.manualSite}</p><div className="brand-pulse-groups mt-4 grid gap-3">{pulseGroups.map(([title,fields],index)=><details className="brand-pulse-group" key={title} open={index===0}><summary><span><b>{brandPulseGroupLabel(locale,title)}</b><span className="muted mt-1 block text-xs">{fields.length} {c.fields}</span></span><span className="summary-chevron">⌄</span></summary><div className="grid gap-x-4 sm:grid-cols-2">{fields.map(field=><PulseField key={field} locale={locale} field={field} value={form[field]} onChange={(value:string)=>setField(field,value)}/>)}</div></details>)}</div><button className="btn mt-5 w-full sm:w-auto" disabled={busy==='pulse'} onClick={savePulse}>{busy==='pulse'?c.saving:c.save}</button></section>

    {(['product','persona','rule','memory'] as Kind[]).map(kind=><Collection key={kind} kind={kind} title={c[kind]} items={collections[kind]} query={query} locale={locale} c={c} start={start} remove={remove}/>)}</main>

   <aside className="order-first space-y-4 xl:order-none xl:sticky xl:top-24 xl:h-fit"><section className="learning-card p-4 sm:p-5"><p className="badge">{c.guide}</p><h2 className="mt-3 text-xl font-black">{recommended?.title||c.openStudio}</h2><p className="muted mt-2 text-sm">{recommended?.description}</p><Link className="btn mt-4 w-full" href={`/${locale}${normalizeWorkspaceHref(recommended?.action_href||'/app/content-studio')}`}>{recommended?.action_label||c.openStudio}</Link><div className="mt-4 grid grid-cols-2 gap-2"><Mini label={c.product} value={data?.products.length||0}/><Mini label={c.persona} value={data?.personas.length||0}/><Mini label={c.rule} value={data?.rules.length||0}/><Mini label={c.memory} value={data?.memory.length||0}/></div></section><section className="panel p-4 sm:p-5"><label className="text-sm font-bold">{brandPulseStatic(locale,'search')}<input className="field mt-2" value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.searchPlaceholder}/></label></section></aside>
  </div>
  {editor&&<EditorModal locale={locale} editor={editor} setEditor={setEditor} c={c} save={saveItem} busy={busy==='item'}/>} 
 </div>;
}

function PulseField({locale,field,value,onChange}:any){const list=multiple.has(field);return <label className="mt-3 block text-xs font-bold">{brandPulseFieldLabel(locale,field)}<textarea dir="auto" className="field mt-1 min-h-20" value={list?(Array.isArray(value)?value.join('\n'):value||''):value||''} onChange={event=>onChange(list?event.target.value.split(/\n|,/).map(item=>item.trim()).filter(Boolean):event.target.value)}/></label>}
function Collection({kind,title,items,query,locale,c,start,remove}:any){const visible=items.filter((item:any)=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));return <section className="panel p-4 sm:p-5"><div className="flex items-center gap-3"><div className="min-w-0"><h2 className="text-xl font-black">{title}</h2><p className="muted text-sm">{items.length} {brandPulseStatic(locale,'items')}</p></div><button className="btn ms-auto" onClick={()=>start(kind)}>＋ {c.add}</button></div>{visible.length?<div className="mt-4 grid gap-3 md:grid-cols-2">{visible.map((item:any)=><article className="brand-pulse-item" key={item.id}><div className="flex items-start gap-2"><div className="min-w-0"><b className="block truncate">{item.name||item.title||item.text}</b><p className="muted mt-1 line-clamp-2 text-sm">{item.description||item.segment||item.category||item.source||'—'}</p></div>{(item.status||item.severity)&&<span className="badge ms-auto">{statusLabel(locale,item.status||item.severity)}</span>}</div><div className="mt-4 flex gap-2"><button className="chip flex-1" onClick={()=>start(kind,item)}>{c.edit}</button><button className="chip flex-1 border-red-200 !text-red-700" onClick={()=>remove(kind,item)}>{kind==='product'?c.archiveConfirm.replace(/[؟?]/g,''):c.delete}</button></div></article>)}</div>:<p className="muted mt-4 rounded-2xl bg-slate-50 p-5 text-center">{c.empty}</p>}</section>}
function EditorModal({locale,editor,setEditor,c,save,busy}:any){const fields=fieldsFor(editor.kind,locale);function set(key:string,value:any){setEditor({...editor,values:{...editor.values,[key]:value}})}return <div className="fixed inset-0 z-[100] grid items-end bg-slate-950/40 p-0 backdrop-blur-sm sm:place-items-center sm:p-4" onClick={()=>setEditor(null)}><section className="panel max-h-[90dvh] w-full overflow-auto rounded-b-none p-5 sm:max-w-2xl sm:rounded-[22px]" role="dialog" aria-modal="true" aria-label={`${editor.id?c.edit:c.add} ${c[editor.kind]}`} onClick={event=>event.stopPropagation()}><div className="flex items-center gap-3"><h2 className="text-xl font-black sm:text-2xl">{editor.id?c.edit:c.add} {c[editor.kind]}</h2><button aria-label={c.close} className="chip ms-auto" onClick={()=>setEditor(null)}>×</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{fields.map((field:FieldDef)=>field.type==='boolean'?<label className="flex min-h-14 items-center gap-3 rounded-2xl border border-slate-200 p-4" key={field.key}><input type="checkbox" checked={Boolean(editor.values[field.key])} onChange={event=>set(field.key,event.target.checked)}/><b>{field.label}</b></label>:field.type==='select'?<label className="text-sm font-bold" key={field.key}>{field.label}<select className="field mt-2" value={editor.values[field.key]||field.options?.[0]} onChange={event=>set(field.key,event.target.value)}>{field.options?.map((option:string)=><option value={option} key={option}>{field.optionKind?workspaceOptionLabel(locale,field.optionKind,option):(editorLabels[locale]||editorLabels.en)[option]||option}</option>)}</select></label>:<label className={`${field.wide?'md:col-span-2':''} text-sm font-bold`} key={field.key}>{field.label}<textarea dir="auto" className="field mt-2 min-h-20" value={multiple.has(field.key)?(Array.isArray(editor.values[field.key])?editor.values[field.key].join('\n'):editor.values[field.key]||''):editor.values[field.key]||''} onChange={event=>set(field.key,multiple.has(field.key)?event.target.value.split(/\n|,/).map(item=>item.trim()).filter(Boolean):event.target.value)}/></label>)}</div><div className="mt-5 grid grid-cols-2 gap-2"><button className="chip" onClick={()=>setEditor(null)}>{c.cancel}</button><button className="btn" disabled={busy} onClick={save}>{busy?'…':c.saveItem}</button></div></section></div>}
function fieldsFor(kind:Kind,locale:string):FieldDef[]{const l=editorLabels[locale]||editorLabels.en;const f=(key:string,rest:Partial<FieldDef>={}):FieldDef=>({key,label:l[key]||key,...rest});if(kind==='product')return[f('name'),f('type',{type:'select',options:['product','service','offer']}),f('status',{type:'select',options:['active','draft','archived']}),f('price_text'),f('description',{wide:true}),f('benefits'),f('audience'),f('objections'),f('proof_points')];if(kind==='persona')return[f('name'),f('segment'),f('language',{type:'select',options:['en','fa','de'],optionKind:'language'}),f('description',{wide:true}),f('pains'),f('desires'),f('objections'),f('preferred_channels')];if(kind==='rule')return[f('title'),f('category',{type:'select',options:['voice','compliance','visual','channel','approval']}),f('severity',{type:'select',options:['info','warning','danger']}),f('applies_to_channel'),f('description',{wide:true}),f('is_active',{type:'boolean'})];return[f('text',{wide:true}),f('source'),f('tags')]}
function defaults(kind:Kind){if(kind==='product')return{type:'service',status:'active',benefits:[],objections:[],proof_points:[]};if(kind==='persona')return{language:'en',pains:[],desires:[],objections:[],preferred_channels:[]};if(kind==='rule')return{category:'voice',severity:'info',is_active:true};return{source:'manual',tags:[]}}
function normalize(kind:Kind,values:Record<string,any>){if(kind==='memory')return{text:values.text,source:values.source||'manual',tags:values.tags||[]};return values}
function pathFor(kind:Kind){return `/brand-pulse/${kind==='product'?'products':kind==='persona'?'personas':kind==='rule'?'rules':'memory'}`}
function Mini({label,value}:any){return <div className="rounded-2xl bg-white/75 p-3 shadow-sm"><b className="block text-2xl">{value}</b><span className="muted line-clamp-1 text-xs">{label}</span></div>}
function slug(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'brand'}
