'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {LanguageSwitcher} from './language-switcher';
import {api,SESSION_MESSAGE_KEY,TOKEN_KEY} from '@/lib/api';

type LoginResult={access_token:string;user:{email:string;name?:string;is_super_admin:boolean}};
const copy:any={en:{title:'Welcome back',sub:'Sign in to continue your brand content operations.',email:'Email',password:'Password',show:'Show',hide:'Hide',submit:'Sign in',loading:'Signing in…',new:'New to Smarbiz?',create:'Create account',invalid:'Enter a valid email and password.',demo:'Demo workspaces',demoHelp:'These shortcuts appear only when the server is explicitly running in demo mode.',secure:'Secure workspace login'},fa:{title:'خوش برگشتی',sub:'برای ادامه مدیریت عملیات محتوای برند وارد شوید.',email:'ایمیل',password:'رمز عبور',show:'نمایش',hide:'پنهان',submit:'ورود',loading:'در حال ورود…',new:'حساب اسماربیز ندارید؟',create:'ساخت حساب',invalid:'ایمیل و رمز عبور معتبر وارد کنید.',demo:'فضاهای نمایشی',demoHelp:'این میان‌بُرها فقط زمانی نمایش داده می‌شوند که سرور صریحاً در حالت Demo باشد.',secure:'ورود امن به فضای کاری'},de:{title:'Willkommen zurück',sub:'Melden Sie sich an, um Ihre Content-Operations fortzusetzen.',email:'E-Mail',password:'Passwort',show:'Anzeigen',hide:'Ausblenden',submit:'Anmelden',loading:'Anmeldung…',new:'Neu bei Smarbiz?',create:'Konto erstellen',invalid:'Geben Sie eine gültige E-Mail-Adresse und ein Passwort ein.',demo:'Demo-Workspaces',demoHelp:'Diese Schnellzugriffe werden nur angezeigt, wenn der Server ausdrücklich im Demo-Modus läuft.',secure:'Sicherer Workspace-Login'}};
const demos=[{label:'Super Admin',email:'admin@smarbiz.sbs'},{label:'Workspace owner',email:'owner@demo.com'},{label:'Client approver',email:'client@demo.com'}];

export function LoginScreen({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [demoMode,setDemoMode]=useState(false);
 useEffect(()=>{const token=localStorage.getItem(TOKEN_KEY);if(token){router.replace(`/${locale}/app/dashboard`);return}const message=localStorage.getItem(SESSION_MESSAGE_KEY);if(message){setNotice(message);localStorage.removeItem(SESSION_MESSAGE_KEY)}api.get<any>('/environment',{mockFallback:{mode:'production'}}).then(result=>setDemoMode(String(result?.mode||'').toLowerCase().includes('demo'))).catch(()=>setDemoMode(false))},[locale,router]);
 async function submit(event?:React.FormEvent,overrideEmail?:string){event?.preventDefault();const loginEmail=(overrideEmail||email).trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(loginEmail)||!password){setError(c.invalid);return}setLoading(true);setError('');try{const result=await api.post<LoginResult>('/auth/login',{email:loginEmail,password});if(!result.access_token)throw new Error('Login response did not include a session token.');localStorage.setItem(TOKEN_KEY,result.access_token);localStorage.setItem('smarbiz_email',result.user.email);localStorage.setItem('smarbiz_role',result.user.is_super_admin?'super_admin':'owner');router.replace(`/${locale}/app/${result.user.is_super_admin?'admin':'dashboard'}`)}catch(e:any){setError(e?.message||'Login failed. Check your credentials.')}finally{setLoading(false)}}
 async function demo(email:string){setEmail(email);setPassword('password123');setLoading(true);setError('');try{const result=await api.post<LoginResult>('/auth/login',{email,password:'password123'});localStorage.setItem(TOKEN_KEY,result.access_token);localStorage.setItem('smarbiz_email',result.user.email);localStorage.setItem('smarbiz_role',result.user.is_super_admin?'super_admin':'owner');router.replace(`/${locale}/app/${result.user.is_super_admin?'admin':'dashboard'}`)}catch(e:any){setError(e?.message||'Demo login failed. Seed demo accounts first.')}finally{setLoading(false)}}
 return <main className="auth-page grid min-h-screen place-items-center p-5" dir={locale==='fa'?'rtl':'ltr'}><div className="absolute end-5 top-5"><LanguageSwitcher locale={locale}/></div><section className="grid w-full max-w-5xl gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="command-card p-8"><Link href={`/${locale}`} className="flex items-center gap-3"><span className="logo-mark">S</span><b>Smarbiz</b></Link><span className="badge mt-8">{c.secure}</span><h1 className="mt-5 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-3 max-w-lg">{c.sub}</p>{demoMode&&<div className="mt-8"><h2 className="font-black">{c.demo}</h2><p className="muted mt-1 text-sm">{c.demoHelp}</p><div className="mt-4 space-y-2">{demos.map(item=><button className="chip w-full justify-between" disabled={loading} key={item.email} onClick={()=>demo(item.email)}><span>{item.label}</span><span>{item.email}</span></button>)}</div></div>} {!demoMode&&<div className="mt-8 grid gap-3 sm:grid-cols-3"><Feature icon="◇" title="Brand-aware"/><Feature icon="✓" title="Approval-ready"/><Feature icon="⌁" title="Measured"/></div>}</div><form onSubmit={submit} className="card p-7 md:p-8"><div className="flex items-center gap-3"><h2 className="text-2xl font-black">{c.submit}</h2><span className="badge ms-auto">HTTPS</span></div>{notice&&<p className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{notice}</p>}{error&&<p role="alert" className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<label className="mt-6 block text-sm font-bold">{c.email}<input className="field mt-2" type="email" autoComplete="email" inputMode="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label className="mt-4 block text-sm font-bold">{c.password}<div className="mt-2 flex gap-2"><input className="field" type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={event=>setPassword(event.target.value)}/><button type="button" className="chip" onClick={()=>setShow(value=>!value)}>{show?c.hide:c.show}</button></div></label><button className="btn mt-6 w-full" disabled={loading}>{loading?c.loading:c.submit}</button><p className="muted mt-5 text-center text-sm">{c.new} <Link className="font-bold text-blue-700" href={`/${locale}/auth/signup`}>{c.create}</Link></p></form></section></main>
}
function Feature({icon,title}:any){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="text-2xl">{icon}</span><b className="mt-3 block">{title}</b></div>}
