'use client';

import {useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {LanguageSwitcher} from './language-switcher';
import {api} from '@/lib/api';

type Locale='en'|'fa'|'de';
type FormState={organization_name:string;workspace_mode:'owner'|'agency';brand_name:string;website_url:string;industry:string;country:string;timezone:string;primary_language:Locale;brand_summary:string;target_audience:string;audience_pain_points:string;desired_outcomes:string;tone_of_voice:string;writing_style:string;content_pillars:string;value_propositions:string;forbidden_claims:string;product_name:string;product_description:string;channels:string[];approval_method:'public_link'|'telegram'|'bale'|'internal';generate_first_week:boolean};
const base=(locale:Locale):FormState=>({organization_name:'',workspace_mode:'owner',brand_name:'',website_url:'',industry:'',country:locale==='fa'?'IR':'DE',timezone:locale==='fa'?'Asia/Tehran':'Europe/Berlin',primary_language:locale,brand_summary:'',target_audience:'',audience_pain_points:'',desired_outcomes:'',tone_of_voice:'',writing_style:'',content_pillars:'',value_propositions:'',forbidden_claims:'',product_name:'',product_description:'',channels:['instagram'],approval_method:'public_link',generate_first_week:true});
const channelIds=['instagram','telegram','bale','linkedin','google_business','email','blog'];
const storageKey='smarbiz_onboarding_draft_v4';
const list=(value:string)=>value.split(/\n|,/).map(item=>item.trim()).filter(Boolean);

const copy={
 en:{title:'Teach Smarbiz how your business works',sub:'We only ask for information that changes the quality of planning and content. You can edit everything later.',steps:['Workspace','Brand','Audience & voice','Offer','Channels & approval','Ready'],save:'Save progress',saving:'Saving…',next:'Continue',back:'Back',finish:'Start creating the first result',required:'Complete the required fields before continuing.',failed:'We could not save the setup. Your entries are still saved on this device.',saved:'Progress saved.',loading:'Loading your workspace…',progress:'Setup progress',why:'Why we ask',whyText:['Defines who owns the workflow.','Keeps generated content specific to your market.','Makes copy sound like your brand and speak to the right people.','Gives the system a real product or service to communicate.','Defines format, publishing limits, and how decisions are recorded.','Turns setup into a practical first content week.'],preview:'What Smarbiz knows',readyTitle:'You are ready to create the first useful output',readyText:'Smarbiz will use this context to generate a first-week plan and guide you to a reviewable draft.',labels:{organization:'Workspace name',mode:'How will you use Smarbiz?',owner:'For my own business',ownerHelp:'One brand and a simple weekly content workflow.',agency:'For clients / agency',agencyHelp:'Multiple brands, reviewers, and approval paths.',brand:'Brand name',website:'Website',industry:'Industry',country:'Country',language:'Primary content language',timezone:'Timezone',summary:'What does the business do?',audience:'Who should the content persuade?',pains:'Audience pains or questions',outcomes:'What outcome do they want?',tone:'Tone of voice',style:'Writing style',product:'Main product or service',productDescription:'Describe the offer',pillars:'Content pillars',value:'Key benefits or value propositions',forbidden:'Claims or phrases to avoid',channels:'Where will content be used?',approval:'How should content be approved?',firstWeek:'Generate the first content week after setup'},placeholders:{summary:'Example: We help local clinics attract qualified consultations.',audience:'Example: Clinic owners in Germany who need consistent local marketing.',pains:'One item per line',outcomes:'One item per line',tone:'Example: Clear, calm, expert, not salesy',style:'Example: Short sentences, concrete examples, one CTA',product:'Example: Monthly content management',productDescription:'What is included, for whom, and why it matters',pillars:'Education\nTrust\nOffer clarity',value:'Fast setup\nConsistent quality\nClear approvals',forbidden:'Guaranteed results\nAbsolute medical claims'},approval:{public_link:'Public approval link',telegram:'Telegram',bale:'Bale',internal:'Internal approval only'},channels:{instagram:'Instagram',telegram:'Telegram',bale:'Bale',linkedin:'LinkedIn',google_business:'Google Business',email:'Email',blog:'Blog'}},
 fa:{title:'نحوه کار کسب‌وکارت را به اسماربیز یاد بده',sub:'فقط اطلاعاتی را می‌پرسیم که کیفیت برنامه و محتوا را واقعاً تغییر می‌دهند. همه چیز بعداً قابل ویرایش است.',steps:['فضای کاری','برند','مخاطب و لحن','پیشنهاد','کانال و تأیید','آماده شروع'],save:'ذخیره پیشرفت',saving:'در حال ذخیره…',next:'ادامه',back:'قبلی',finish:'شروع ساخت اولین نتیجه',required:'فیلدهای ضروری را کامل کن و بعد ادامه بده.',failed:'ذخیره روی سرور انجام نشد؛ اطلاعات روی همین دستگاه محفوظ است.',saved:'پیشرفت ذخیره شد.',loading:'در حال دریافت فضای کاری…',progress:'پیشرفت راه‌اندازی',why:'چرا این را می‌پرسیم؟',whyText:['مشخص می‌کند این فرایند برای یک کسب‌وکار است یا چند مشتری.','باعث می‌شود محتوا برای بازار شما مشخص و واقعی باشد.','کمک می‌کند متن‌ها با لحن برند و برای آدم درست نوشته شوند.','یک محصول یا خدمت واقعی به سیستم می‌دهد تا درباره‌اش محتوا بسازد.','قالب محتوا، محدودیت انتشار و روش ثبت تصمیم را مشخص می‌کند.','تنظیمات را به یک برنامه محتوایی عملی تبدیل می‌کند.'],preview:'آنچه اسماربیز از شما می‌داند',readyTitle:'برای ساخت اولین خروجی مفید آماده‌ای',readyText:'اسماربیز از این اطلاعات برای ساخت برنامه هفته اول و هدایت تو تا یک محتوای قابل بررسی استفاده می‌کند.',labels:{organization:'نام فضای کاری',mode:'چطور از اسماربیز استفاده می‌کنی؟',owner:'برای کسب‌وکار خودم',ownerHelp:'یک برند و یک جریان ساده هفتگی محتوا.',agency:'برای مشتری‌ها / آژانس',agencyHelp:'چند برند، چند بررسی‌کننده و مسیرهای تأیید.',brand:'نام برند',website:'وب‌سایت',industry:'حوزه فعالیت',country:'کشور',language:'زبان اصلی محتوا',timezone:'منطقه زمانی',summary:'کسب‌وکار دقیقاً چه کاری انجام می‌دهد؟',audience:'محتوا باید چه کسی را متقاعد کند؟',pains:'مسئله‌ها و سؤال‌های مخاطب',outcomes:'مخاطب دنبال چه نتیجه‌ای است؟',tone:'لحن برند',style:'سبک نوشتن',product:'محصول یا خدمت اصلی',productDescription:'پیشنهاد را توضیح بده',pillars:'ستون‌های محتوا',value:'مزایا یا ارزش‌های کلیدی',forbidden:'ادعاها یا عبارت‌های ممنوع',channels:'محتوا کجا استفاده می‌شود؟',approval:'محتوا چطور تأیید شود؟',firstWeek:'بعد از راه‌اندازی، برنامه هفته اول ساخته شود'},placeholders:{summary:'مثال: به کلینیک‌های محلی کمک می‌کنیم مشاوره‌های باکیفیت بیشتری جذب کنند.',audience:'مثال: مدیران کلینیک در آلمان که بازاریابی منظم محلی می‌خواهند.',pains:'هر مورد در یک خط',outcomes:'هر مورد در یک خط',tone:'مثال: شفاف، آرام و متخصص؛ بدون لحن فروش تهاجمی',style:'مثال: جمله‌های کوتاه، مثال مشخص و یک دعوت به اقدام',product:'مثال: مدیریت ماهانه محتوا',productDescription:'شامل چه چیزی است، برای چه کسی و چرا مهم است؟',pillars:'آموزش\nاعتمادسازی\nشفاف‌کردن پیشنهاد',value:'راه‌اندازی سریع\nکیفیت یکدست\nتأیید شفاف',forbidden:'نتیجه تضمینی\nادعاهای قطعی پزشکی'},approval:{public_link:'لینک عمومی تأیید',telegram:'تلگرام',bale:'بله',internal:'تأیید داخلی'},channels:{instagram:'اینستاگرام',telegram:'تلگرام',bale:'بله',linkedin:'لینکدین',google_business:'گوگل بیزنس',email:'ایمیل',blog:'وبلاگ'}},
 de:{title:'Zeigen Sie Smarbiz, wie Ihr Geschäft funktioniert',sub:'Wir fragen nur Informationen ab, die Planung und Inhalte wirklich verbessern. Alles bleibt später bearbeitbar.',steps:['Workspace','Marke','Zielgruppe & Ton','Angebot','Kanäle & Freigabe','Bereit'],save:'Fortschritt speichern',saving:'Wird gespeichert…',next:'Weiter',back:'Zurück',finish:'Erstes Ergebnis erstellen',required:'Bitte füllen Sie die Pflichtfelder aus.',failed:'Das Setup konnte nicht gespeichert werden. Die Eingaben bleiben auf diesem Gerät.',saved:'Fortschritt gespeichert.',loading:'Workspace wird geladen…',progress:'Setup-Fortschritt',why:'Warum wir fragen',whyText:['Definiert, wem der Workflow gehört.','Macht Inhalte spezifisch für Ihren Markt.','Sorgt für die richtige Markenstimme und Zielgruppe.','Gibt dem System ein echtes Angebot für die Kommunikation.','Definiert Formate, Grenzen und Freigaben.','Verwandelt das Setup in eine praktische erste Woche.'],preview:'Was Smarbiz weiß',readyTitle:'Bereit für das erste nützliche Ergebnis',readyText:'Smarbiz nutzt diesen Kontext für den ersten Wochenplan und führt Sie zu einem prüfbaren Entwurf.',labels:{organization:'Workspace-Name',mode:'Wie nutzen Sie Smarbiz?',owner:'Für mein Unternehmen',ownerHelp:'Eine Marke und ein einfacher wöchentlicher Workflow.',agency:'Für Kunden / Agentur',agencyHelp:'Mehrere Marken, Prüfer und Freigabewege.',brand:'Markenname',website:'Website',industry:'Branche',country:'Land',language:'Hauptsprache',timezone:'Zeitzone',summary:'Was macht das Unternehmen?',audience:'Wen soll der Content überzeugen?',pains:'Probleme oder Fragen der Zielgruppe',outcomes:'Gewünschte Ergebnisse',tone:'Ton der Marke',style:'Schreibstil',product:'Hauptprodukt oder Dienstleistung',productDescription:'Angebot beschreiben',pillars:'Content-Säulen',value:'Wichtigste Vorteile',forbidden:'Zu vermeidende Aussagen',channels:'Wo wird Content eingesetzt?',approval:'Wie wird Content freigegeben?',firstWeek:'Erste Content-Woche nach Setup erzeugen'},placeholders:{summary:'Beispiel: Wir helfen lokalen Praxen, qualifizierte Beratungen zu gewinnen.',audience:'Beispiel: Praxisinhaber in Deutschland mit Bedarf an lokalem Marketing.',pains:'Ein Punkt pro Zeile',outcomes:'Ein Punkt pro Zeile',tone:'Beispiel: Klar, ruhig und kompetent',style:'Kurze Sätze, konkrete Beispiele, ein CTA',product:'Beispiel: Monatliches Content-Management',productDescription:'Leistung, Zielgruppe und Nutzen',pillars:'Bildung\nVertrauen\nAngebotsklarheit',value:'Schnelles Setup\nKonstante Qualität\nKlare Freigaben',forbidden:'Garantierte Ergebnisse\nAbsolute medizinische Aussagen'},approval:{public_link:'Öffentlicher Freigabelink',telegram:'Telegram',bale:'Bale',internal:'Nur interne Freigabe'},channels:{instagram:'Instagram',telegram:'Telegram',bale:'Bale',linkedin:'LinkedIn',google_business:'Google Business',email:'E-Mail',blog:'Blog'}}
} as const;

export function OnboardingWizard({locale:raw}:{locale:string}){
 const locale:Locale=raw==='fa'||raw==='de'?raw:'en';const c=copy[locale];const router=useRouter();
 const [step,setStep]=useState(0);const [form,setForm]=useState<FormState>(()=>base(locale));const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [server,setServer]=useState<any>({pulse:null,integrations:null});
 useEffect(()=>{let alive=true;Promise.all([api.get<any>('/settings/overview'),api.get<any>('/brand-pulse/overview'),api.get<any>('/integrations/overview').catch(()=>null)]).then(([settings,pulse,integrations])=>{if(!alive)return;const p=pulse?.pulse||{};let local:any={};try{local=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{}const connected=(integrations?.catalog||[]).filter((item:any)=>item.connection_id&&channelIds.includes(item.provider)).map((item:any)=>item.provider);setServer({pulse,integrations});setForm({...base(locale),organization_name:settings?.organization?.name||'',workspace_mode:settings?.organization?.mode==='agency'?'agency':'owner',brand_name:p.brand_name||settings?.brand?.name||'',website_url:p.website_url||'',industry:p.industry||settings?.brand?.industry||'',country:p.country||settings?.brand?.country||base(locale).country,timezone:p.timezone||settings?.brand?.timezone||settings?.preferences?.default_timezone||base(locale).timezone,primary_language:p.primary_language||settings?.brand?.primary_language||locale,brand_summary:p.brand_summary||'',target_audience:p.target_audience||'',audience_pain_points:Array.isArray(p.audience_pain_points)?p.audience_pain_points.join('\n'):p.audience_pain_points||'',desired_outcomes:Array.isArray(p.desired_outcomes)?p.desired_outcomes.join('\n'):p.desired_outcomes||'',tone_of_voice:p.tone_of_voice||'',writing_style:p.writing_style||'',content_pillars:Array.isArray(p.content_pillars)?p.content_pillars.join('\n'):p.content_pillars||'',value_propositions:Array.isArray(p.value_propositions)?p.value_propositions.join('\n'):p.value_propositions||'',forbidden_claims:Array.isArray(p.forbidden_claims)?p.forbidden_claims.join('\n'):p.forbidden_claims||'',product_name:pulse?.products?.[0]?.name||'',product_description:pulse?.products?.[0]?.description||'',channels:connected.length?connected:['instagram'],approval_method:approvalFrom(integrations),...local})}).catch((e:any)=>setError(e?.message||c.failed)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[locale]);
 useEffect(()=>{if(!loading)localStorage.setItem(storageKey,JSON.stringify(form))},[form,loading]);
 const valid=useMemo(()=>step===0?!!form.organization_name.trim():step===1?!!form.brand_name.trim()&&!!form.industry.trim()&&!!form.country.trim()&&!!form.timezone.trim():step===2?!!form.brand_summary.trim()&&!!form.target_audience.trim()&&!!form.tone_of_voice.trim():step===3?!!form.product_name.trim()&&!!form.product_description.trim():step===4?form.channels.length>0&&!!form.approval_method:true,[step,form]);
 function set<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}));setError('');setMessage('')}
 async function save(final=false){setSaving(true);setError('');setMessage('');try{await api.patch('/settings/organization',{name:form.organization_name.trim(),mode:form.workspace_mode});await api.patch('/settings/brand-defaults',{name:form.brand_name.trim(),industry:form.industry.trim(),country:form.country.trim(),timezone:form.timezone.trim(),primary_language:form.primary_language});await api.patch('/settings/profile',{locale:form.primary_language,timezone:form.timezone.trim()});await api.patch('/brand-pulse',{brand_name:form.brand_name.trim(),website_url:form.website_url.trim(),industry:form.industry.trim(),country:form.country.trim(),timezone:form.timezone.trim(),primary_language:form.primary_language,brand_summary:form.brand_summary.trim(),target_audience:form.target_audience.trim(),audience_pain_points:list(form.audience_pain_points),desired_outcomes:list(form.desired_outcomes),tone_of_voice:form.tone_of_voice.trim(),writing_style:form.writing_style.trim(),content_pillars:list(form.content_pillars),value_propositions:list(form.value_propositions),forbidden_claims:list(form.forbidden_claims),channel_notes:form.channels,approval_preferences:form.approval_method});const exists=(server.pulse?.products||[]).some((item:any)=>item.name?.trim().toLowerCase()===form.product_name.trim().toLowerCase());if(form.product_name.trim()&&!exists)await api.post('/brand-pulse/products',{name:form.product_name.trim(),type:'service',description:form.product_description.trim(),benefits:list(form.value_propositions),audience:form.target_audience.trim(),status:'active'});if(final){const provider=form.approval_method==='public_link'?'approval_link':form.approval_method;const connected=(server.integrations?.catalog||[]).some((item:any)=>item.provider===provider&&item.connection_id);if(!connected&&provider!=='internal')await api.post('/integrations/connections',{provider,display_name:c.approval[form.approval_method],config:{}}).catch(()=>null);if(form.generate_first_week)await api.post('/calendar/generate-week',{week_start:new Date().toISOString()}).catch(()=>null);localStorage.removeItem(storageKey)}setMessage(c.saved);return true}catch(e:any){setError(e?.message||c.failed);return false}finally{setSaving(false)}}
 async function next(){if(!valid){setError(c.required);return}if(await save())setStep(value=>Math.min(c.steps.length-1,value+1))}
 async function finish(){if(!valid){setError(c.required);return}if(await save(true))router.push(`/${locale}/app/dashboard?activation=1`)}
 if(loading)return <main className="grid min-h-screen place-items-center"><div className="text-center"><div className="mx-auto h-11 w-11 animate-spin rounded-full border-[3px] border-slate-200 border-t-indigo-600"/><p className="muted mt-4">{c.loading}</p></div></main>;
 const progress=Math.round((step+1)/c.steps.length*100);
 return <main className="min-h-screen p-4 md:p-6" dir={locale==='fa'?'rtl':'ltr'}><div className="mx-auto max-w-7xl"><header className="flex items-center gap-3 px-1"><span className="logo-mark">S</span><span><b className="block text-lg">Smarbiz</b><span className="muted text-xs">{c.progress}</span></span><div className="ms-auto"><LanguageSwitcher locale={locale}/></div></header>
  <section className="activation-hero mt-5 animate-enter p-6 md:p-8"><div className="relative z-10 flex flex-wrap items-start gap-5"><div className="max-w-4xl"><span className="badge">{progress}%</span><h1 className="text-balance mt-4 text-4xl md:text-6xl">{c.title}</h1><p className="muted text-balance mt-4 max-w-3xl text-base md:text-lg">{c.sub}</p></div><button className="chip ms-auto" disabled={saving} onClick={()=>save()}>{saving?c.saving:c.save}</button></div><div className="progress-track relative z-10 mt-7"><div className="progress-fill" style={{width:`${progress}%`}}/></div></section>
  {(error||message)&&<div className={`mt-4 animate-enter rounded-2xl border p-4 text-sm ${error?'border-rose-200 bg-rose-50 text-rose-800':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error||message}</div>}
  <div className="mt-5 grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)_300px]"><nav className="panel h-fit p-3 lg:sticky lg:top-4">{c.steps.map((label,index)=><button type="button" key={label} onClick={()=>setStep(index)} className={`mb-1 flex w-full items-center gap-3 rounded-xl p-3 text-start transition ${index===step?'bg-indigo-50 text-indigo-800 ring-1 ring-indigo-100':'hover:bg-slate-50'}`}><span className={`activation-dot ${index<step?'!bg-emerald-100 !text-emerald-700':index===step?'!bg-indigo-600 !text-white':''}`}>{index<step?'✓':index+1}</span><b className="text-sm">{label}</b></button>)}</nav>
   <section className="panel min-h-[35rem] animate-enter p-5 md:p-7"><div className="flex items-start justify-between gap-3"><div><span className="badge">{step+1} / {c.steps.length}</span><h2 className="mt-3 text-3xl">{c.steps[step]}</h2></div></div><div className="mt-6">{renderStep(step,form,set,c,locale)}</div><div className="mt-8 flex gap-2 border-t border-slate-100 pt-5"><button className="chip" disabled={step===0||saving} onClick={()=>setStep(value=>Math.max(0,value-1))}>{c.back}</button>{step<c.steps.length-1?<button className="btn ms-auto" disabled={saving} onClick={next}>{saving?c.saving:c.next}</button>:<button className="btn ms-auto" disabled={saving} onClick={finish}>{saving?c.saving:c.finish}</button>}</div></section>
   <aside className="space-y-4 lg:sticky lg:top-4 lg:h-fit"><section className="panel p-5"><span className="badge">{c.why}</span><p className="mt-4 text-sm">{c.whyText[step]}</p></section><section className="panel p-5"><h3>{c.preview}</h3><div className="mt-4 space-y-3 text-sm"><Summary label={c.labels.brand} value={form.brand_name}/><Summary label={c.labels.audience} value={form.target_audience}/><Summary label={c.labels.product} value={form.product_name}/><Summary label={c.labels.channels} value={form.channels.map(item=>c.channels[item as keyof typeof c.channels]).join('، ')}/><Summary label={c.labels.approval} value={c.approval[form.approval_method]}/></div></section></aside>
  </div></div></main>;
}

function approvalFrom(integrations:any):FormState['approval_method']{const item=(integrations?.catalog||[]).find((row:any)=>['approval_link','telegram','bale'].includes(row.provider)&&row.connection_id);return item?.provider==='approval_link'?'public_link':item?.provider||'public_link'}
function renderStep(step:number,form:FormState,set:any,c:any,locale:Locale){
 if(step===0)return <div className="space-y-5"><Field label={`${c.labels.organization} *`} value={form.organization_name} onChange={(value:string)=>set('organization_name',value)}/><div className="grid gap-3 md:grid-cols-2"><Choice selected={form.workspace_mode==='owner'} title={c.labels.owner} description={c.labels.ownerHelp} onClick={()=>set('workspace_mode','owner')}/><Choice selected={form.workspace_mode==='agency'} title={c.labels.agency} description={c.labels.agencyHelp} onClick={()=>set('workspace_mode','agency')}/></div></div>;
 if(step===1)return <div className="grid gap-4 md:grid-cols-2"><Field label={`${c.labels.brand} *`} value={form.brand_name} onChange={(value:string)=>set('brand_name',value)}/><Field label={c.labels.website} type="url" value={form.website_url} onChange={(value:string)=>set('website_url',value)}/><Field label={`${c.labels.industry} *`} value={form.industry} onChange={(value:string)=>set('industry',value)}/><Field label={`${c.labels.country} *`} value={form.country} onChange={(value:string)=>set('country',value)}/><Select label={c.labels.language} value={form.primary_language} options={[['fa','فارسی'],['en','English'],['de','Deutsch']]} onChange={(value:string)=>set('primary_language',value)}/><Field label={`${c.labels.timezone} *`} value={form.timezone} onChange={(value:string)=>set('timezone',value)}/></div>;
 if(step===2)return <div className="space-y-4"><Area label={`${c.labels.summary} *`} placeholder={c.placeholders.summary} value={form.brand_summary} onChange={(value:string)=>set('brand_summary',value)}/><Area label={`${c.labels.audience} *`} placeholder={c.placeholders.audience} value={form.target_audience} onChange={(value:string)=>set('target_audience',value)}/><div className="grid gap-4 md:grid-cols-2"><Area label={c.labels.pains} placeholder={c.placeholders.pains} value={form.audience_pain_points} onChange={(value:string)=>set('audience_pain_points',value)}/><Area label={c.labels.outcomes} placeholder={c.placeholders.outcomes} value={form.desired_outcomes} onChange={(value:string)=>set('desired_outcomes',value)}/></div><div className="grid gap-4 md:grid-cols-2"><Field label={`${c.labels.tone} *`} placeholder={c.placeholders.tone} value={form.tone_of_voice} onChange={(value:string)=>set('tone_of_voice',value)}/><Field label={c.labels.style} placeholder={c.placeholders.style} value={form.writing_style} onChange={(value:string)=>set('writing_style',value)}/></div></div>;
 if(step===3)return <div className="space-y-4"><Field label={`${c.labels.product} *`} placeholder={c.placeholders.product} value={form.product_name} onChange={(value:string)=>set('product_name',value)}/><Area label={`${c.labels.productDescription} *`} placeholder={c.placeholders.productDescription} value={form.product_description} onChange={(value:string)=>set('product_description',value)}/><div className="grid gap-4 md:grid-cols-2"><Area label={c.labels.pillars} placeholder={c.placeholders.pillars} value={form.content_pillars} onChange={(value:string)=>set('content_pillars',value)}/><Area label={c.labels.value} placeholder={c.placeholders.value} value={form.value_propositions} onChange={(value:string)=>set('value_propositions',value)}/></div><Area label={c.labels.forbidden} placeholder={c.placeholders.forbidden} value={form.forbidden_claims} onChange={(value:string)=>set('forbidden_claims',value)}/></div>;
 if(step===4)return <div className="space-y-6"><div><Label>{c.labels.channels}</Label><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{channelIds.map(id=><button type="button" key={id} onClick={()=>set('channels',form.channels.includes(id)?form.channels.filter(item=>item!==id):[...form.channels,id])} className={`activation-step flex items-center gap-3 text-start ${form.channels.includes(id)?'current':''}`}><span className="activation-dot">{form.channels.includes(id)?'✓':'+'}</span><b>{c.channels[id as keyof typeof c.channels]}</b></button>)}</div></div><div><Label>{c.labels.approval}</Label><div className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(c.approval).map(([id,label])=><Choice key={id} selected={form.approval_method===id} title={String(label)} description="" onClick={()=>set('approval_method',id)}/>)}</div></div><Toggle checked={form.generate_first_week} label={c.labels.firstWeek} onChange={(value:boolean)=>set('generate_first_week',value)}/></div>;
 return <div className="grid min-h-[27rem] place-items-center text-center"><div className="max-w-xl"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-100 text-3xl text-emerald-700">✓</span><h2 className="mt-5 text-3xl">{c.readyTitle}</h2><p className="muted mt-3 text-base">{c.readyText}</p><div className="mt-6 grid gap-3 text-start sm:grid-cols-2"><Summary label={c.labels.brand} value={form.brand_name}/><Summary label={c.labels.product} value={form.product_name}/><Summary label={c.labels.channels} value={form.channels.map(item=>c.channels[item as keyof typeof c.channels]).join('، ')}/><Summary label={c.labels.approval} value={c.approval[form.approval_method]}/></div></div></div>;
}
function Label({children}:{children:React.ReactNode}){return <span className="text-sm font-bold text-slate-700">{children}</span>}
function Field({label,value,onChange,type='text',placeholder=''}:any){return <label className="block"><Label>{label}</Label><input className="field mt-2" type={type} value={value} placeholder={placeholder} onChange={event=>onChange(event.target.value)}/></label>}
function Area({label,value,onChange,placeholder=''}:any){return <label className="block"><Label>{label}</Label><textarea className="field mt-2 min-h-28 resize-y" value={value} placeholder={placeholder} onChange={event=>onChange(event.target.value)}/></label>}
function Select({label,value,onChange,options}:any){return <label className="block"><Label>{label}</Label><select className="field mt-2" value={value} onChange={event=>onChange(event.target.value)}>{options.map(([id,name]:[string,string])=><option value={id} key={id}>{name}</option>)}</select></label>}
function Choice({selected,title,description,onClick}:any){return <button type="button" onClick={onClick} className={`activation-step text-start ${selected?'current':''}`}><div className="flex items-start gap-3"><span className="activation-dot">{selected?'✓':'○'}</span><span><b className="block">{title}</b>{description&&<span className="muted mt-1 block text-sm">{description}</span>}</span></div></button>}
function Toggle({checked,label,onChange}:any){return <label className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><button type="button" aria-pressed={checked} onClick={()=>onChange(!checked)} className={`relative h-7 w-12 rounded-full transition ${checked?'bg-indigo-600':'bg-slate-300'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition-all ${checked?'end-1':'start-1'}`}/></button><b className="text-sm">{label}</b></label>}
function Summary({label,value}:any){return <div className="rounded-xl bg-slate-50 p-3"><span className="muted block text-[11px]">{label}</span><b className="mt-1 block truncate text-sm">{value||'—'}</b></div>}
