'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/api';
import {statusLabel} from '@/lib/i18n';

type ApprovalData={closed?:boolean;message?:string;approval?:{id:number;status:string;due_at?:string|null;expires_at?:string|null};draft?:{title:string;body:string;hook?:string;cta?:string;hashtags?:string;channel?:string;content_type?:string;language?:string};brand?:{name:string};reviewer?:string|null};
const copy:any={en:{loading:'Opening approval request…',invalid:'This approval link is invalid, expired, or no longer available.',retry:'Retry',title:'Content review',sub:'Review the final draft and record one clear decision.',reviewer:'Your name',comment:'Comment or requested change',approve:'Approve',changes:'Request changes',reject:'Reject',sending:'Sending decision…',requiredName:'Enter your name before submitting a decision.',requiredComment:'Explain the requested changes or rejection.',confirmReject:'Reject this draft?',done:'Decision recorded',doneSub:'You can close this page. The Smarbiz workspace has been updated.',closed:'This approval request is closed.',due:'Due',powered:'Powered by Smarbiz',back:'Open Smarbiz'},fa:{loading:'در حال بازکردن درخواست تأیید…',invalid:'این لینک تأیید نامعتبر، منقضی یا دیگر در دسترس نیست.',retry:'تلاش دوباره',title:'بررسی محتوا',sub:'نسخه نهایی را بررسی و یک تصمیم روشن ثبت کنید.',reviewer:'نام شما',comment:'نظر یا تغییر درخواستی',approve:'تأیید',changes:'درخواست تغییر',reject:'رد',sending:'در حال ثبت تصمیم…',requiredName:'قبل از ثبت تصمیم، نام خود را وارد کنید.',requiredComment:'تغییرات درخواستی یا دلیل رد را توضیح دهید.',confirmReject:'این پیش‌نویس رد شود؟',done:'تصمیم ثبت شد',doneSub:'می‌توانید این صفحه را ببندید. فضای کاری اسماربیز به‌روزرسانی شد.',closed:'این درخواست تأیید بسته شده است.',due:'مهلت',powered:'با اسماربیز',back:'باز کردن اسماربیز'},de:{loading:'Freigabeanfrage wird geöffnet…',invalid:'Dieser Freigabelink ist ungültig, abgelaufen oder nicht mehr verfügbar.',retry:'Erneut versuchen',title:'Content-Prüfung',sub:'Prüfen Sie den finalen Entwurf und erfassen Sie eine eindeutige Entscheidung.',reviewer:'Ihr Name',comment:'Kommentar oder gewünschte Änderung',approve:'Freigeben',changes:'Änderungen anfordern',reject:'Ablehnen',sending:'Entscheidung wird gesendet…',requiredName:'Geben Sie Ihren Namen ein.',requiredComment:'Beschreiben Sie die gewünschten Änderungen oder den Ablehnungsgrund.',confirmReject:'Diesen Entwurf ablehnen?',done:'Entscheidung erfasst',doneSub:'Sie können diese Seite schließen. Der Smarbiz-Workspace wurde aktualisiert.',closed:'Diese Freigabeanfrage ist geschlossen.',due:'Fällig',powered:'Powered by Smarbiz',back:'Smarbiz öffnen'}};

export function PublicApprovalPage({locale,token}:{locale:string;token:string}){
 const c=copy[locale]||copy.en;const [data,setData]=useState<ApprovalData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [reviewer,setReviewer]=useState('');const [comment,setComment]=useState('');const [busy,setBusy]=useState('');const [complete,setComplete]=useState(false);
 async function load(){setLoading(true);setError('');try{const result=await api.get<ApprovalData>(`/public/approvals/${encodeURIComponent(token)}`);setData(result);if(result.reviewer)setReviewer(result.reviewer)}catch(e:any){setError(e?.message||c.invalid)}finally{setLoading(false)}}
 useEffect(()=>{load()},[token]);
 async function decide(action:'approve'|'request_changes'|'reject'){if(!reviewer.trim()){setError(c.requiredName);return}if(action!=='approve'&&!comment.trim()){setError(c.requiredComment);return}if(action==='reject'&&!confirm(c.confirmReject))return;setBusy(action);setError('');try{const result=await api.post<any>(`/public/approvals/${encodeURIComponent(token)}/decision`,{action,reviewer_name:reviewer.trim(),comment:comment.trim()||null,revision_prompt:action==='request_changes'?comment.trim():null,save_to_memory:true});setData(current=>({...current,approval:result.approval||result,closed:true}));setComplete(true)}catch(e:any){setError(e?.message||c.invalid)}finally{setBusy('')}}
 if(loading)return <main className="grid min-h-screen place-items-center bg-app p-5"><div className="text-center"><div className="mx-auto h-12 w-12 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"/><p className="muted mt-4">{c.loading}</p></div></main>;
 if(error&&!data)return <main className="grid min-h-screen place-items-center bg-app p-5"><section className="panel max-w-lg p-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-red-50 text-3xl">!</div><h1 className="mt-5 text-3xl font-black">{c.invalid}</h1><p className="mt-3 text-red-700">{error}</p><button className="btn mt-5" onClick={load}>{c.retry}</button></section></main>;
 if(complete||data?.closed)return <main className="grid min-h-screen place-items-center bg-app p-5" dir={locale==='fa'?'rtl':'ltr'}><section className="panel max-w-xl p-8 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-green-100 text-3xl text-green-700">✓</div><h1 className="mt-5 text-3xl font-black">{complete?c.done:c.closed}</h1><p className="muted mt-3">{data?.message||c.doneSub}</p>{data?.approval?.status&&<span className="badge badge-success mt-5">{statusLabel(locale,data.approval.status)}</span>}<div className="mt-6"><Link className="chip" href={`/${locale}`}>{c.back}</Link></div></section></main>;
 const draft=data?.draft;const rtl=draft?.language==='fa'||/[؀-ۿ]/.test(draft?.body||'');const due=data?.approval?.due_at||data?.approval?.expires_at;
 return <main className="min-h-screen bg-app p-4 md:p-6" dir={locale==='fa'?'rtl':'ltr'}><div className="mx-auto max-w-6xl"><header className="flex items-center gap-3 py-2"><span className="logo-mark">S</span><div><b>{data?.brand?.name||'Smarbiz'}</b><p className="muted text-xs">{c.powered}</p></div>{data?.approval?.status&&<span className="badge ms-auto">{statusLabel(locale,data.approval.status)}</span>}</header><section className="command-card mt-5 p-5 md:p-7"><span className="badge">{draft?.channel||'content'} · {draft?.content_type||'draft'}</span><h1 className="mt-4 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-2">{c.sub}</p>{due&&<p className="mt-3 text-sm font-bold">{c.due}: {new Date(due).toLocaleString(locale)}</p>}</section>{error&&<p role="alert" className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_22rem]"><article className="panel p-5 md:p-7" dir={rtl?'rtl':'ltr'}><h2 className="text-3xl font-black">{draft?.title||'Untitled content'}</h2>{draft?.hook&&<p className="mt-5 rounded-2xl bg-blue-50 p-4 font-bold">{draft.hook}</p>}<p className="mt-6 whitespace-pre-wrap text-base leading-8">{draft?.body}</p>{draft?.cta&&<p className="mt-5 font-bold">{draft.cta}</p>}{draft?.hashtags&&<p className="mt-4 text-blue-700">{draft.hashtags}</p>}</article><aside className="panel h-fit p-5 lg:sticky lg:top-5"><label className="block text-sm font-bold">{c.reviewer}<input className="field mt-2" value={reviewer} onChange={event=>setReviewer(event.target.value)}/></label><label className="mt-4 block text-sm font-bold">{c.comment}<textarea className="field mt-2 min-h-32" value={comment} onChange={event=>setComment(event.target.value)}/></label><div className="mt-5 grid gap-2"><button className="btn" disabled={!!busy} onClick={()=>decide('approve')}>{busy==='approve'?c.sending:c.approve}</button><button className="chip" disabled={!!busy} onClick={()=>decide('request_changes')}>{busy==='request_changes'?c.sending:c.changes}</button><button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={()=>decide('reject')}>{busy==='reject'?c.sending:c.reject}</button></div><p className="muted mt-4 text-xs">Your reviewer name, decision, and comment will be stored in the approval history.</p></aside></div></div></main>
}
