'use client';

import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {useToast} from './ui/toast';
import {statusLabel} from '@/lib/i18n';
import {deepLocalizeKnownCopy,localizeKnownText,localizeMetricLabel,localizeWorkspacePayload} from '@/lib/known-copy-localization';

type ReportSummary={id:number;title:string;period_start:string;period_end:string;status:string;highlights_count:number;recommendations_count:number;created_at:string};
type ReportDetail={id:number;title:string;period_start:string;period_end:string;status:string;summary:string;highlights:string[];metrics:Record<string,any>;recommendations:{items?:string[];next_week?:string[]};created_at:string};
type Overview={organization:any;brand:any;summary:any;reports:ReportSummary[];alerts?:any[]};

const copy:any={
 en:{title:'Reports',sub:'Generate factual reports from drafts, approvals, campaigns and measured performance.',generate:'Generate report',custom:'Custom period',start:'Period start',end:'Period end',language:'Language',audience:'Audience',internal:'Internal team',client:'Client / stakeholder',save:'Generate',generating:'Generating…',total:'Total reports',month:'This month',week:'Generated this week',ready:'Available reports',last:'Last report',empty:'No reports yet',emptySub:'Generate the first report from real Smarbiz workflow data.',open:'Open',regenerate:'Regenerate',edit:'Edit title',delete:'Delete',deleteConfirm:'Delete this report?',copy:'Copy summary',markdown:'Markdown',pdf:'PDF',email:'Send email',downloaded:'Report downloaded.',copied:'Summary copied.',summary:'Executive summary',highlights:'Highlights',metrics:'Workflow metrics',recommendations:'Recommendations',editTitle:'Report title',retry:'Retry',invalidDates:'End date cannot be before start date.',recipient:'Recipient email',brevo:'Email delivery requires a connected Brevo account.'},
 fa:{title:'گزارش‌ها',sub:'از پیش‌نویس‌ها، تأییدها، کمپین‌ها و عملکرد اندازه‌گیری‌شده گزارش واقعی بسازید.',generate:'ساخت گزارش',custom:'بازه سفارشی',start:'شروع بازه',end:'پایان بازه',language:'زبان',audience:'مخاطب گزارش',internal:'تیم داخلی',client:'مشتری / ذی‌نفع',save:'تولید گزارش',generating:'در حال تولید…',total:'مجموع گزارش‌ها',month:'این ماه',week:'ساخته‌شده این هفته',ready:'گزارش‌های آماده',last:'آخرین گزارش',empty:'هنوز گزارشی وجود ندارد',emptySub:'اولین گزارش را از داده واقعی اسماربیز بسازید.',open:'باز کردن',regenerate:'تولید مجدد',edit:'ویرایش عنوان',delete:'حذف',deleteConfirm:'این گزارش حذف شود؟',copy:'کپی خلاصه',markdown:'Markdown',pdf:'PDF',email:'ارسال ایمیل',downloaded:'گزارش دانلود شد.',copied:'خلاصه کپی شد.',summary:'خلاصه اجرایی',highlights:'نکات مهم',metrics:'متریک‌های جریان کاری',recommendations:'پیشنهادها',editTitle:'عنوان گزارش',retry:'تلاش دوباره',invalidDates:'تاریخ پایان نمی‌تواند قبل از شروع باشد.',recipient:'ایمیل گیرنده',brevo:'ارسال ایمیل نیاز به اتصال واقعی Brevo دارد.'},
 de:{title:'Berichte',sub:'Erstellen Sie sachliche Berichte aus Entwürfen, Freigaben, Kampagnen und gemessener Performance.',generate:'Bericht generieren',custom:'Benutzerdefinierter Zeitraum',start:'Zeitraumbeginn',end:'Zeitraumende',language:'Sprache',audience:'Zielgruppe',internal:'Internes Team',client:'Kunde / Stakeholder',save:'Generieren',generating:'Wird generiert…',total:'Berichte gesamt',month:'Diesen Monat',week:'Diese Woche erstellt',ready:'Verfügbare Berichte',last:'Letzter Bericht',empty:'Noch keine Berichte',emptySub:'Erstellen Sie den ersten Bericht aus echten Smarbiz-Daten.',open:'Öffnen',regenerate:'Neu generieren',edit:'Titel bearbeiten',delete:'Löschen',deleteConfirm:'Diesen Bericht löschen?',copy:'Zusammenfassung kopieren',markdown:'Markdown',pdf:'PDF',email:'E-Mail senden',downloaded:'Bericht heruntergeladen.',copied:'Zusammenfassung kopiert.',summary:'Executive Summary',highlights:'Highlights',metrics:'Workflow-Metriken',recommendations:'Empfehlungen',editTitle:'Berichtstitel',retry:'Erneut versuchen',invalidDates:'Das Enddatum darf nicht vor dem Startdatum liegen.',recipient:'Empfänger-E-Mail',brevo:'Für E-Mail-Versand ist eine verbundene Brevo-Integration erforderlich.'}
};

const monday=()=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const dateOnly=(d:Date)=>d.toISOString().slice(0,10);
const downloadBlob=(blob:Blob,filename:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),100)};
const base64Bytes=(value:string)=>{const raw=atob(value);const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes};

export function ReportsPage({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const toast=useToast();
 const [data,setData]=useState<Overview|null>(null);const [detail,setDetail]=useState<ReportDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');const [query,setQuery]=useState('');const [showGenerate,setShowGenerate]=useState(false);
 const start=monday();const [form,setForm]=useState({period_start:dateOnly(start),period_end:dateOnly(new Date(start.getTime()+6*86400000)),language:locale,audience:'internal'});
 async function load(){setLoading(true);setError('');try{setData(localizeWorkspacePayload(locale,await api.get<Overview>('/reports/overview')))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const reports=useMemo(()=>data?.reports.filter(r=>`${r.title} ${r.period_start} ${r.period_end}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query]);
 async function open(id:number){setBusy(`open-${id}`);try{setDetail(deepLocalizeKnownCopy(locale,await api.get<ReportDetail>(`/reports/${id}`)))}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function generate(){if(form.period_end<form.period_start){toast(c.invalidDates);return}setBusy('generate');try{const result=deepLocalizeKnownCopy(locale,await api.post<ReportDetail>('/reports/generate-weekly',form));setDetail(result);setShowGenerate(false);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function regenerate(){if(!detail)return;setBusy('regenerate');try{setDetail(deepLocalizeKnownCopy(locale,await api.post<ReportDetail>(`/reports/${detail.id}/regenerate`,{})));await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function remove(){if(!detail||!confirm(c.deleteConfirm))return;setBusy('delete');try{await api.delete(`/reports/${detail.id}`);setDetail(null);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function copySummary(){if(!detail)return;try{const result=await api.post<any>(`/reports/${detail.id}/copy-summary`,{});await navigator.clipboard.writeText(result.text||detail.summary);toast(c.copied)}catch(e:any){toast(e?.message||String(e))}}
 async function exportReport(format:'markdown'|'pdf'){if(!detail)return;setBusy(`export-${format}`);try{const result=await api.post<any>(`/reports/${detail.id}/export`,{format});if(!result.available)throw new Error(result.message||'Export unavailable');if(format==='pdf'){downloadBlob(new Blob([base64Bytes(result.content_base64)],{type:'application/pdf'}),result.filename||`smarbiz-report-${detail.id}.pdf`)}else{downloadBlob(new Blob([result.content],{type:'text/markdown;charset=utf-8'}),result.filename||`smarbiz-report-${detail.id}.md`)}toast(c.downloaded)}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function sendEmail(){if(!detail)return;const recipient=window.prompt(c.recipient);if(!recipient)return;setBusy('email');try{await api.post(`/reports/${detail.id}/send-email`,{recipient_email:recipient});toast(c.email)}catch(e:any){toast(`${e?.message||String(e)} — ${c.brevo}`)}finally{setBusy('')}}
 async function editTitle(){if(!detail)return;const title=window.prompt(c.editTitle,detail.title);if(!title?.trim())return;setBusy('edit');try{setDetail(await api.patch<ReportDetail>(`/reports/${detail.id}`,{title:title.trim()}));await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 if(loading&&!data)return <div className="grid gap-4 md:grid-cols-3">{[1,2,3,4,5,6].map(x=><div className="card h-44 animate-pulse" key={x}/>)}</div>;
 if(error&&!data)return <div className="panel p-8"><h1 className="text-3xl font-black">{c.title}</h1><p className="muted mt-3">{error}</p><button className="btn mt-5" onClick={load}>{c.retry}</button></div>;
 return <div className="space-y-6">
  <section className="command-card p-6"><div className="flex flex-wrap items-start gap-3"><div><p className="badge">{data?.organization?.name} · {data?.brand?.name}</p><h1 className="mt-3 text-4xl font-black">{c.title}</h1><p className="muted mt-2 max-w-4xl">{c.sub}</p></div><button className="btn ms-auto" onClick={()=>setShowGenerate(v=>!v)}>{c.generate}</button></div>
   {showGenerate&&<div className="mt-5 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5"><label className="text-sm font-bold">{c.start}<input className="field mt-1" type="date" value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})}/></label><label className="text-sm font-bold">{c.end}<input className="field mt-1" type="date" value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})}/></label><label className="text-sm font-bold">{c.language}<select className="field mt-1" value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option value="fa">فارسی</option><option value="de">Deutsch</option><option value="en">English</option></select></label><label className="text-sm font-bold">{c.audience}<select className="field mt-1" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}><option value="internal">{c.internal}</option><option value="client">{c.client}</option></select></label><button className="btn self-end" disabled={busy==='generate'} onClick={generate}>{busy==='generate'?c.generating:c.save}</button></div>}
  </section>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label={c.total} value={data?.summary?.total_reports||0}/><Metric label={c.month} value={data?.summary?.reports_this_month||0}/><Metric label={c.week} value={data?.summary?.generated_this_week?'✓':'—'}/><Metric label={c.ready} value={data?.summary?.send_ready_count||0}/><Metric label={c.last} value={data?.summary?.last_report_date?new Date(data.summary.last_report_date).toLocaleDateString(locale):'—'}/></section>
  <div className="grid gap-6 xl:grid-cols-[21rem_minmax(0,1fr)]"><aside className="panel h-fit p-4"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder={localizeKnownText(locale,'Search reports')}/><div className="mt-4 max-h-[65vh] space-y-2 overflow-auto">{reports.map(r=><button key={r.id} className={`w-full rounded-2xl border p-4 text-start ${detail?.id===r.id?'border-blue-300 bg-blue-50':'border-slate-200'}`} onClick={()=>open(r.id)}><b>{r.title}</b><p className="muted mt-1 text-xs">{r.period_start} → {r.period_end}</p><span className="badge mt-2">{statusLabel(locale,r.status)}</span></button>)}{!reports.length&&<p className="muted p-3">{c.empty}</p>}</div></aside>
   <section className="panel min-w-0 p-5 md:p-7">{detail?<><div className="flex flex-wrap items-start gap-3"><div><span className="badge">{statusLabel(locale,detail.status)}</span><h2 className="mt-3 text-3xl font-black">{detail.title}</h2><p className="muted mt-2">{detail.period_start} → {detail.period_end}</p></div><div className="ms-auto flex flex-wrap gap-2"><button className="chip" onClick={copySummary}>{c.copy}</button><button className="chip" disabled={!!busy} onClick={()=>exportReport('markdown')}>{c.markdown}</button><button className="chip" disabled={!!busy} onClick={()=>exportReport('pdf')}>{c.pdf}</button><button className="chip" disabled={!!busy} onClick={sendEmail}>{c.email}</button><button className="chip" onClick={editTitle}>{c.edit}</button></div></div>
    <Block title={c.summary}><p className="whitespace-pre-wrap leading-8">{detail.summary}</p></Block>
    <Block title={c.metrics}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(detail.metrics||{}).map(([k,v])=><Metric key={k} label={localizeMetricLabel(locale,k)} value={typeof v==='object'?JSON.stringify(v):String(v)}/>)}</div></Block>
    <Block title={c.highlights}>{detail.highlights?.length?<ul className="space-y-2">{detail.highlights.map((x,i)=><li className="rounded-2xl bg-blue-50 p-4" key={i}>{x}</li>)}</ul>:<p className="muted">—</p>}</Block>
    <Block title={c.recommendations}><ul className="space-y-2">{(detail.recommendations?.items||detail.recommendations?.next_week||[]).map((x,i)=><li className="rounded-2xl bg-slate-50 p-4" key={i}>{x}</li>)}</ul></Block>
    <div className="mt-8 flex gap-2 border-t pt-5"><button className="btn" disabled={!!busy} onClick={regenerate}>{c.regenerate}</button><button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={remove}>{c.delete}</button></div></>:<div className="grid min-h-[32rem] place-items-center text-center"><div><h2 className="text-3xl font-black">{c.empty}</h2><p className="muted mt-2">{c.emptySub}</p><button className="btn mt-5" onClick={()=>setShowGenerate(true)}>{c.generate}</button></div></div>}</section>
  </div>
 </div>
}
function Metric({label,value}:{label:string;value:any}){return <div className="card p-4"><p className="muted text-xs font-bold">{label}</p><p className="mt-2 break-words text-xl font-black">{value}</p></div>}
function Block({title,children}:{title:string;children:any}){return <section className="mt-7"><h3 className="mb-3 text-xl font-black">{title}</h3>{children}</section>}
