'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {api} from '@/lib/api';
import {statusLabel} from '@/lib/i18n';
import {useToast} from './ui/toast';
import {localizeRequirementList,normalizeWorkspaceHref} from '@/lib/workspace-localization';
import {deepLocalizeKnownCopy,localizeWorkspacePayload} from '@/lib/known-copy-localization';

type Tab='account'|'organization'|'brand'|'team'|'setup'|'ai'|'usage'|'security';
type Member={id:number;name?:string;email:string;role:string;status:string;user_id?:number};
type Role={id:string;label:string};
type Overview={user:any;organization:any;brand:any;team:Member[];roles:Role[];setup:any;usage:any;ai_provider:any;preferences:any;alerts:any[];permissions:{can_manage_team:boolean}};
type FormState={name:string;locale:string;timezone:string;organization_name:string;organization_mode:string;brand_name:string;industry:string;country:string;brand_timezone:string;primary_language:string;provider:string;model:string;temporary_key:string;invite_email:string;invite_role:string;current_password:string;new_password:string;confirm_password:string};

const empty:FormState={name:'',locale:'en',timezone:'UTC',organization_name:'',organization_mode:'owner',brand_name:'',industry:'',country:'',brand_timezone:'UTC',primary_language:'en',provider:'mock',model:'',temporary_key:'',invite_email:'',invite_role:'viewer',current_password:'',new_password:'',confirm_password:''};
const tabs:Tab[]=['account','organization','brand','team','setup','ai','usage','security'];
const copy:any={
 en:{title:'Settings',sub:'Manage your account, workspace defaults, people, AI, usage, and security.',account:'Account',organization:'Organization',brand:'Brand defaults',team:'Team & roles',setup:'Setup checklist',ai:'AI provider',usage:'Usage',security:'Security',save:'Save changes',saving:'Saving…',name:'Name',email:'Email',language:'Language',timezone:'Timezone',orgName:'Organization name',mode:'Workspace mode',owner:'Single brand / owner',agency:'Agency / multiple brands',brandName:'Brand name',industry:'Industry',country:'Country',invite:'Invite member',role:'Role',status:'Status',disable:'Disable',enable:'Enable',password:'Change password',current:'Current password',nextPassword:'New password',confirm:'Confirm new password',change:'Update password',providerHelp:'Provider credentials are managed on the server. A key entered here is used only for this test and is not stored.',test:'Test configuration',export:'Request data export',delete:'Request workspace deletion',manual:'This operation is recorded as a manual request and is not immediate.',saved:'Settings saved.',invited:'Invitation created.',mismatch:'New passwords do not match.',loading:'Loading settings…',retry:'Retry',billing:'Billing',plan:'Plan',notConnected:'Not connected',invitedUser:'Invited user',completion:'Completion',provider:'Provider',model:'Model',temporaryKey:'Temporary API key',runtime:'Runtime status',aiOperations:'AI operations',drafts:'Drafts',reports:'Reports',assets:'Assets',next:'Next step',continue:'Continue',complete:'Core setup is complete.'},
 fa:{title:'تنظیمات',sub:'حساب، فضای کاری، اعضا، هوش مصنوعی، مصرف و امنیت را مدیریت کنید.',account:'حساب',organization:'سازمان',brand:'تنظیمات برند',team:'تیم و نقش‌ها',setup:'چک‌لیست راه‌اندازی',ai:'ارائه‌دهنده AI',usage:'مصرف',security:'امنیت',save:'ذخیره تغییرات',saving:'در حال ذخیره…',name:'نام',email:'ایمیل',language:'زبان',timezone:'منطقه زمانی',orgName:'نام سازمان',mode:'نوع فضای کاری',owner:'یک برند / مالک',agency:'آژانس / چند برند',brandName:'نام برند',industry:'حوزه فعالیت',country:'کشور',invite:'دعوت عضو',role:'نقش',status:'وضعیت',disable:'غیرفعال‌کردن',enable:'فعال‌کردن',password:'تغییر رمز عبور',current:'رمز فعلی',nextPassword:'رمز جدید',confirm:'تکرار رمز جدید',change:'به‌روزرسانی رمز',providerHelp:'دسترسی‌های ارائه‌دهنده روی سرور مدیریت می‌شوند. کلید این فرم فقط برای تست استفاده می‌شود و ذخیره نخواهد شد.',test:'تست تنظیمات',export:'درخواست خروجی داده',delete:'درخواست حذف فضای کاری',manual:'این عملیات به‌صورت درخواست دستی ثبت می‌شود و فوری نیست.',saved:'تنظیمات ذخیره شد.',invited:'دعوت ثبت شد.',mismatch:'رمزهای جدید یکسان نیستند.',loading:'در حال بارگذاری تنظیمات…',retry:'تلاش دوباره',billing:'صورتحساب',plan:'پلن',notConnected:'متصل نیست',invitedUser:'کاربر دعوت‌شده',completion:'میزان تکمیل',provider:'ارائه‌دهنده',model:'مدل',temporaryKey:'کلید موقت API',runtime:'وضعیت اجرا',aiOperations:'عملیات هوش مصنوعی',drafts:'پیش‌نویس‌ها',reports:'گزارش‌ها',assets:'دارایی‌ها',next:'قدم بعدی',continue:'ادامه',complete:'راه‌اندازی اصلی کامل شده است.'},
 de:{title:'Einstellungen',sub:'Verwalten Sie Konto, Workspace, Team, KI, Nutzung und Sicherheit.',account:'Konto',organization:'Organisation',brand:'Markenstandards',team:'Team & Rollen',setup:'Setup-Checkliste',ai:'AI-Provider',usage:'Nutzung',security:'Sicherheit',save:'Änderungen speichern',saving:'Wird gespeichert…',name:'Name',email:'E-Mail',language:'Sprache',timezone:'Zeitzone',orgName:'Organisationsname',mode:'Workspace-Modus',owner:'Eine Marke / Owner',agency:'Agentur / mehrere Marken',brandName:'Markenname',industry:'Branche',country:'Land',invite:'Mitglied einladen',role:'Rolle',status:'Status',disable:'Deaktivieren',enable:'Aktivieren',password:'Passwort ändern',current:'Aktuelles Passwort',nextPassword:'Neues Passwort',confirm:'Neues Passwort bestätigen',change:'Passwort aktualisieren',providerHelp:'Provider-Zugänge werden auf dem Server verwaltet. Ein hier eingegebener Schlüssel wird nur getestet und nicht gespeichert.',test:'Konfiguration testen',export:'Datenexport anfordern',delete:'Workspace-Löschung anfordern',manual:'Dieser Vorgang wird als manuelle Anfrage erfasst und nicht sofort ausgeführt.',saved:'Einstellungen gespeichert.',invited:'Einladung erstellt.',mismatch:'Die neuen Passwörter stimmen nicht überein.',loading:'Einstellungen werden geladen…',retry:'Erneut versuchen',billing:'Abrechnung',plan:'Tarif',notConnected:'Nicht verbunden',invitedUser:'Eingeladener Benutzer',completion:'Fortschritt',provider:'Provider',model:'Modell',temporaryKey:'Temporärer API-Schlüssel',runtime:'Laufzeitstatus',aiOperations:'KI-Vorgänge',drafts:'Entwürfe',reports:'Berichte',assets:'Assets',next:'Nächster Schritt',continue:'Weiter',complete:'Die Kerneinrichtung ist abgeschlossen.'}
};

const faSetup:Record<string,[string,string]>={
 create_brand:['ساخت برند','اطلاعات پایه فضای کاری و برند را ثبت کنید.'],brand_pulse:['تکمیل پالس برند','مخاطب، لحن، قوانین و جایگاه برند را مشخص کنید.'],add_product:['افزودن محصول یا خدمت','یک پیشنهاد واقعی برای استفاده در محتوا ثبت کنید.'],choose_channels:['انتخاب کانال‌ها','کانال‌های اصلی انتشار را تعیین کنید.'],connect_approval:['اتصال مسیر تأیید','یک روش امن برای بررسی و تأیید محتوا فعال کنید.'],generate_week:['ساخت هفته اول','اولین برنامه محتوایی قابل ویرایش را بسازید.'],create_draft:['ساخت اولین پیش‌نویس','یک محتوای واقعی براساس اطلاعات برند تولید کنید.'],send_approval:['ارسال برای تأیید','پیش‌نویس را برای بازبینی بفرستید.'],publish:['انتشار اولین محتوا','چرخه محتوا را با انتشار یا زمان‌بندی کامل کنید.'],review_insight:['بررسی اولین بینش','نتیجه را ثبت کنید تا هفته بعد بهتر شود.']
};

function localizeStep(locale:string,step:any){if(locale!=='fa')return step;const pair=faSetup[String(step.id||'').toLowerCase()];return pair?{...step,title:pair[0],description:pair[1]}:step}
function localizeAlert(locale:string,alert:any){if(locale!=='fa')return alert;const key=(String(alert.id||'')+' '+String(alert.title||'')).toLowerCase();if(key.includes('approval'))return {...alert,title:'مسیر تأیید ناقص است',description:'یک لینک عمومی، تلگرام یا بله را برای تأیید محتوا تنظیم کنید.'};if(key.includes('brand'))return {...alert,title:'اطلاعات برند ناقص است',description:'پالس برند را تکمیل کنید تا خروجی‌ها دقیق‌تر شوند.'};return alert}

export function SettingsPanelV2({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const toast=useToast();const params=useSearchParams();const requested=(params.get('section')||params.get('tab')||'account') as Tab;
 const [tab,setTab]=useState<Tab>(tabs.includes(requested)?requested:'account');const [data,setData]=useState<Overview|null>(null);const [form,setForm]=useState<FormState>(empty);const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function load(){setError('');try{const result=localizeWorkspacePayload(locale,await api.get<Overview>('/settings/overview'));setData(result);setForm({...empty,name:result.user?.name||'',locale:result.user?.locale||locale,timezone:result.preferences?.default_timezone||'UTC',organization_name:result.organization?.name||'',organization_mode:result.organization?.mode||'owner',brand_name:result.brand?.name||'',industry:result.brand?.industry||'',country:result.brand?.country||'',brand_timezone:result.brand?.timezone||'UTC',primary_language:result.brand?.primary_language||locale,provider:String(result.ai_provider?.provider||'mock').toLowerCase(),model:result.ai_provider?.model||''})}catch(e:any){setError(e?.message||String(e))}}
 useEffect(()=>{load()},[]);
 function set<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>({...current,[key]:value}))}
 async function run(key:string,task:()=>Promise<unknown>,message=c.saved){setBusy(key);try{await task();toast(message);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 const canManage=!!data?.permissions.can_manage_team;
 const steps=useMemo(()=>localizeRequirementList(locale,data?.setup?.steps),[data,locale]);
 const alerts=useMemo(()=>deepLocalizeKnownCopy(locale,data?.alerts||[]),[data,locale]);
 const nextStep=steps.find((step:any)=>step.status!=='done');
 if(!data)return <div className="panel p-8"><h1 className="text-3xl font-black">{c.title}</h1><p className={`mt-3 ${error?'text-red-700':'muted'}`}>{error||c.loading}</p>{error&&<button className="btn mt-4" onClick={load}>{c.retry}</button>}</div>;
 return <div className="space-y-6">
  <section className="command-card p-6"><div className="flex flex-wrap items-start gap-3"><div><p className="badge">{data.organization?.name} · {data.brand?.name}</p><h1 className="mt-3 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-2">{c.sub}</p></div>{tab==='account'&&<Save busy={busy==='account'} c={c} action={()=>run('account',()=>api.patch('/settings/profile',{name:form.name,locale:form.locale,timezone:form.timezone}))}/>} {tab==='organization'&&<Save busy={busy==='organization'} disabled={!canManage} c={c} action={()=>run('organization',()=>api.patch('/settings/organization',{name:form.organization_name,mode:form.organization_mode}))}/>} {tab==='brand'&&<Save busy={busy==='brand'} c={c} action={()=>run('brand',()=>api.patch('/settings/brand-defaults',{name:form.brand_name,industry:form.industry,country:form.country,timezone:form.brand_timezone,primary_language:form.primary_language}))}/>}</div></section>
  <div className="flex gap-2 overflow-x-auto">{tabs.map(item=><button className={`chip whitespace-nowrap ${tab===item?'!border-blue-200 !bg-blue-50 !text-blue-700':''}`} onClick={()=>setTab(item)} key={item}>{c[item]}</button>)}</div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><section className="panel p-5 md:p-6">
   {tab==='account'&&<Grid><Field label={c.name} value={form.name} onChange={(value:string)=>set('name',value)}/><Field label={c.email} value={data.user.email} readOnly/><Select label={c.language} value={form.locale} options={[['en','English'],['fa','فارسی'],['de','Deutsch']]} onChange={(value:string)=>set('locale',value)}/><Field label={c.timezone} value={form.timezone} onChange={(value:string)=>set('timezone',value)}/></Grid>}
   {tab==='organization'&&<Grid><Field label={c.orgName} disabled={!canManage} value={form.organization_name} onChange={(value:string)=>set('organization_name',value)}/><Select label={c.mode} disabled={!canManage} value={form.organization_mode} options={[['owner',c.owner],['agency',c.agency]]} onChange={(value:string)=>set('organization_mode',value)}/><Read label={c.billing} value={data.organization?.billing_status||c.notConnected}/><Read label={c.plan} value={data.organization?.plan||c.notConnected}/></Grid>}
   {tab==='brand'&&<Grid><Field label={c.brandName} value={form.brand_name} onChange={(value:string)=>set('brand_name',value)}/><Field label={c.industry} value={form.industry} onChange={(value:string)=>set('industry',value)}/><Field label={c.country} value={form.country} onChange={(value:string)=>set('country',value)}/><Field label={c.timezone} value={form.brand_timezone} onChange={(value:string)=>set('brand_timezone',value)}/><Select label={c.language} value={form.primary_language} options={[['en','English'],['fa','فارسی'],['de','Deutsch']]} onChange={(value:string)=>set('primary_language',value)}/></Grid>}
   {tab==='team'&&<><div className="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[minmax(0,1fr)_14rem_auto]"><Field label={c.email} type="email" disabled={!canManage} value={form.invite_email} onChange={(value:string)=>set('invite_email',value)}/><Select label={c.role} disabled={!canManage} value={form.invite_role} options={data.roles.map((role:Role)=>[role.id,role.label])} onChange={(value:string)=>set('invite_role',value)}/><button className="btn self-end" disabled={!canManage||!form.invite_email||!!busy} onClick={()=>run('invite',()=>api.post('/settings/team/invite',{email:form.invite_email,role:form.invite_role}),c.invited)}>{c.invite}</button></div><div className="mt-5 overflow-x-auto"><table className="table"><thead><tr><th>{c.name}</th><th>{c.email}</th><th>{c.role}</th><th>{c.status}</th><th/></tr></thead><tbody>{data.team.map((member:Member)=><tr key={member.id}><td>{member.name||c.invitedUser}</td><td>{member.email}</td><td><select className="field min-w-40" disabled={!canManage||!!busy} value={member.role} onChange={event=>run(`member-${member.id}`,()=>api.patch(`/settings/team/${member.id}`,{role:event.target.value}))}>{data.roles.map((role:Role)=><option value={role.id} key={role.id}>{role.label}</option>)}</select></td><td><span className="badge">{statusLabel(locale,member.status)}</span></td><td>{canManage&&member.user_id!==data.user.id&&<button className="chip" disabled={!!busy} onClick={()=>run(`member-${member.id}`,()=>member.status==='disabled'?api.patch(`/settings/team/${member.id}`,{status:'active'}):api.delete(`/settings/team/${member.id}`))}>{member.status==='disabled'?c.enable:c.disable}</button>}</td></tr>)}</tbody></table></div></>}
   {tab==='setup'&&<><Read label={c.completion} value={`${data.setup.completion_percent}%`}/><div className="mt-5 space-y-2">{steps.map((step:any)=><Link className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 hover:bg-slate-50" href={`/${locale}${normalizeWorkspaceHref(step.action_href)}`} key={step.id}><span>{step.status==='done'?'✓':'→'}</span><span><b className="block">{step.title}</b><span className="muted text-xs">{step.description}</span></span><span className="badge ms-auto">{statusLabel(locale,step.status)}</span></Link>)}</div></>}
   {tab==='ai'&&<><p className="muted">{c.providerHelp}</p><Grid><Select label={c.provider} value={form.provider} options={['mock','openai','anthropic','gemini','custom']} onChange={(value:string)=>set('provider',value)}/><Field label={c.model} value={form.model} onChange={(value:string)=>set('model',value)}/><Field label={c.temporaryKey} type="password" value={form.temporary_key} onChange={(value:string)=>set('temporary_key',value)}/><Read label={c.runtime} value={`${data.ai_provider.provider} · ${statusLabel(locale,data.ai_provider.status)}`}/></Grid><button className="btn mt-5" disabled={busy==='ai'} onClick={()=>run('ai',()=>api.post('/settings/ai-provider/test',{provider:form.provider,model:form.model,api_key:form.temporary_key}),c.test)}>{c.test}</button></>}
   {tab==='usage'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Read label={c.aiOperations} value={data.usage.ai_credits_used}/><Read label={c.drafts} value={data.usage.drafts_count}/><Read label={c.reports} value={data.usage.reports_count}/><Read label={c.assets} value={data.usage.assets_count}/></div>}
   {tab==='security'&&<><h2 className="text-2xl font-black">{c.password}</h2><Grid><Field label={c.current} type="password" value={form.current_password} onChange={(value:string)=>set('current_password',value)}/><Field label={c.nextPassword} type="password" value={form.new_password} onChange={(value:string)=>set('new_password',value)}/><Field label={c.confirm} type="password" value={form.confirm_password} onChange={(value:string)=>set('confirm_password',value)}/></Grid><button className="btn mt-5" disabled={busy==='password'||form.new_password.length<8} onClick={()=>{if(form.new_password!==form.confirm_password)return toast(c.mismatch);run('password',()=>api.post('/settings/security/change-password',{current_password:form.current_password,new_password:form.new_password}),c.change)}}>{c.change}</button><div className="my-7 border-t border-slate-200"/><div className="grid gap-4 md:grid-cols-2"><RequestCard title={c.export} note={c.manual} action={()=>run('export',()=>api.post('/settings/export-data',{}))}/><RequestCard danger title={c.delete} note={c.manual} action={()=>confirm(c.manual)&&run('delete',()=>api.post('/settings/delete-workspace-request',{}))}/></div></>}
  </section><aside className="panel h-fit p-5 xl:sticky xl:top-24"><h2 className="text-xl font-black">{c.next}</h2><p className="muted mt-2 text-sm">{nextStep?.description||c.complete}</p><Link className="btn mt-4 w-full" href={`/${locale}${normalizeWorkspaceHref(nextStep?.action_href)}`}>{c.continue}</Link>{alerts.slice(0,4).map((alert:any)=><Link className="mt-3 block rounded-2xl bg-amber-50 p-3 text-sm text-amber-900" href={`/${locale}${normalizeWorkspaceHref(alert.href)}`} key={alert.id}><b>{alert.title}</b><p>{alert.description}</p></Link>)}</aside></div>
 </div>;
}

function Save({busy,disabled=false,c,action}:any){return <button className="btn ms-auto" disabled={busy||disabled} onClick={action}>{busy?c.saving:c.save}</button>}
function Grid({children}:any){return <div className="grid gap-4 md:grid-cols-2">{children}</div>}
function Field({label,value,onChange,type='text',readOnly=false,disabled=false}:any){return <label className="block text-sm font-bold">{label}<input className="field mt-2" type={type} value={value||''} readOnly={readOnly} disabled={disabled} onChange={event=>onChange?.(event.target.value)}/></label>}
function Select({label,value,options,onChange,disabled=false}:any){return <label className="block text-sm font-bold">{label}<select className="field mt-2" value={value} disabled={disabled} onChange={event=>onChange(event.target.value)}>{options.map((option:any)=>{const id=Array.isArray(option)?option[0]:option;const text=Array.isArray(option)?option[1]:option;return <option value={id} key={id}>{text}</option>})}</select></label>}
function Read({label,value}:any){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="muted text-sm">{label}</p><b className="mt-2 block text-2xl">{value??'—'}</b></div>}
function RequestCard({title,note,action,danger=false}:any){return <div className={`rounded-2xl border p-5 ${danger?'border-red-200 bg-red-50':'border-slate-200 bg-slate-50'}`}><b>{title}</b><p className="muted mt-2 text-sm">{note}</p><button className={`chip mt-4 ${danger?'border-red-200 !text-red-700':''}`} onClick={action}>{title}</button></div>}
