'use client';

import {useEffect, useMemo, useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {api} from '@/lib/api';
import {ErrorState, LoadingSkeleton, StatusBadge} from './shared-states';
import {useToast} from './ui/toast';

type Tab='account'|'organization'|'brand'|'team'|'setup'|'ai'|'usage'|'security';
type Member={id:number;name?:string;email:string;role:string;status:string;user_id?:number};
type Overview={user:any;organization:any;brand:any;team:Member[];roles:any[];setup:any;usage:any;ai_provider:any;preferences:any;alerts:any[];permissions:{can_manage_team:boolean}};

const copy:any={
 en:{title:'Settings',sub:'Manage account details, workspace defaults, people, AI runtime status, usage, and security.',tabs:{account:'Account',organization:'Organization',brand:'Brand defaults',team:'Team & roles',setup:'Setup checklist',ai:'AI provider',usage:'Usage',security:'Security'},save:'Save changes',saving:'Saving…',saved:'Settings saved.',name:'Name',email:'Email',language:'Preferred language',timezone:'Timezone',orgName:'Organization name',mode:'Workspace mode',owner:'Single brand / owner',agency:'Agency / multiple brands',billing:'Billing status',plan:'Plan',brandName:'Active brand name',industry:'Industry',country:'Country',primaryLanguage:'Primary language',invite:'Invite member',inviteEmail:'Member email',inviteRole:'Role',invited:'Invitation record created.',teamEmpty:'No team members yet.',role:'Role',status:'Status',disable:'Disable',enable:'Enable',removeConfirm:'Disable this team member?',setupCompletion:'Setup completion',next:'Next recommended action',providerTitle:'AI runtime configuration',providerHelp:'Production provider credentials are managed on the server. A key entered here is used only for this test request and is not stored.',provider:'Provider',model:'Model',temporaryKey:'Temporary API key',test:'Test configuration',notPersisted:'This page does not persist provider secrets. Update server environment variables for a permanent configuration.',operations:'AI operations',drafts:'Drafts',reports:'Reports',assets:'Assets',billingPlaceholder:'Billing and paid limits are not connected yet; no fake subscription state is shown.',password:'Change password',currentPassword:'Current password',newPassword:'New password',confirmPassword:'Confirm new password',changePassword:'Update password',passwordChanged:'Password updated.',passwordMismatch:'New passwords do not match.',export:'Request data export',delete:'Request workspace deletion',exportHelp:'Export delivery is currently a manual request, not an instant download.',deleteHelp:'Workspace deletion is queued for manual review and is not immediate.',requestSent:'Request recorded.',ownerOnly:'Only workspace owners can change this section.',retry:'Retry'},
 fa:{title:'تنظیمات',sub:'اطلاعات حساب، فضای کاری، اعضا، وضعیت AI، مصرف و امنیت را مدیریت کنید.',tabs:{account:'حساب کاربری',organization:'سازمان',brand:'تنظیمات برند',team:'تیم و نقش‌ها',setup:'چک‌لیست راه‌اندازی',ai:'ارائه‌دهنده AI',usage:'مصرف',security:'امنیت'},save:'ذخیره تغییرات',saving:'در حال ذخیره…',saved:'تنظیمات ذخیره شد.',name:'نام',email:'ایمیل',language:'زبان ترجیحی',timezone:'منطقه زمانی',orgName:'نام سازمان',mode:'نوع فضای کاری',owner:'یک برند / مالک',agency:'آژانس / چند برند',billing:'وضعیت پرداخت',plan:'پلن',brandName:'نام برند فعال',industry:'صنعت',country:'کشور',primaryLanguage:'زبان اصلی',invite:'دعوت عضو',inviteEmail:'ایمیل عضو',inviteRole:'نقش',invited:'رکورد دعوت ساخته شد.',teamEmpty:'هنوز عضوی وجود ندارد.',role:'نقش',status:'وضعیت',disable:'غیرفعال',enable:'فعال',removeConfirm:'این عضو غیرفعال شود؟',setupCompletion:'درصد تکمیل راه‌اندازی',next:'اقدام پیشنهادی بعدی',providerTitle:'تنظیمات اجرای هوش مصنوعی',providerHelp:'کلیدهای Production روی سرور مدیریت می‌شوند. کلیدی که اینجا وارد می‌شود فقط برای همین تست استفاده می‌شود و ذخیره نخواهد شد.',provider:'ارائه‌دهنده',model:'مدل',temporaryKey:'کلید موقت API',test:'تست تنظیمات',notPersisted:'این صفحه کلید ارائه‌دهنده را ذخیره نمی‌کند. برای تنظیم دائمی باید متغیرهای محیطی سرور به‌روزرسانی شوند.',operations:'عملیات AI',drafts:'پیش‌نویس‌ها',reports:'گزارش‌ها',assets:'فایل‌ها',billingPlaceholder:'صورتحساب و محدودیت پلن هنوز متصل نیست و وضعیت اشتراک جعلی نشان داده نمی‌شود.',password:'تغییر رمز عبور',currentPassword:'رمز فعلی',newPassword:'رمز جدید',confirmPassword:'تکرار رمز جدید',changePassword:'تغییر رمز',passwordChanged:'رمز عبور تغییر کرد.',passwordMismatch:'رمزهای جدید یکسان نیستند.',export:'درخواست خروجی داده',delete:'درخواست حذف فضای کاری',exportHelp:'ارسال خروجی فعلاً یک درخواست دستی است، نه دانلود فوری.',deleteHelp:'حذف فضای کاری برای بررسی دستی ثبت می‌شود و فوری نیست.',requestSent:'درخواست ثبت شد.',ownerOnly:'فقط مالک فضای کاری می‌تواند این بخش را تغییر دهد.',retry:'تلاش دوباره'},
 de:{title:'Einstellungen',sub:'Verwalten Sie Konto, Workspace, Team, AI-Laufzeitstatus, Nutzung und Sicherheit.',tabs:{account:'Konto',organization:'Organisation',brand:'Markenstandards',team:'Team & Rollen',setup:'Setup-Checkliste',ai:'AI-Provider',usage:'Nutzung',security:'Sicherheit'},save:'Änderungen speichern',saving:'Wird gespeichert…',saved:'Einstellungen gespeichert.',name:'Name',email:'E-Mail',language:'Bevorzugte Sprache',timezone:'Zeitzone',orgName:'Organisationsname',mode:'Workspace-Modus',owner:'Eine Marke / Owner',agency:'Agentur / mehrere Marken',billing:'Abrechnungsstatus',plan:'Plan',brandName:'Aktiver Markenname',industry:'Branche',country:'Land',primaryLanguage:'Primärsprache',invite:'Mitglied einladen',inviteEmail:'E-Mail des Mitglieds',inviteRole:'Rolle',invited:'Einladungsdatensatz erstellt.',teamEmpty:'Noch keine Teammitglieder.',role:'Rolle',status:'Status',disable:'Deaktivieren',enable:'Aktivieren',removeConfirm:'Dieses Teammitglied deaktivieren?',setupCompletion:'Setup-Fortschritt',next:'Nächste empfohlene Aktion',providerTitle:'AI-Laufzeitkonfiguration',providerHelp:'Produktionszugänge werden auf dem Server verwaltet. Ein hier eingegebener Schlüssel wird nur für diesen Test verwendet und nicht gespeichert.',provider:'Provider',model:'Modell',temporaryKey:'Temporärer API-Schlüssel',test:'Konfiguration testen',notPersisted:'Diese Seite speichert keine Provider-Schlüssel. Für eine dauerhafte Konfiguration müssen die Server-Umgebungsvariablen aktualisiert werden.',operations:'AI-Operationen',drafts:'Entwürfe',reports:'Berichte',assets:'Assets',billingPlaceholder:'Abrechnung und bezahlte Limits sind noch nicht verbunden; es wird kein falscher Abostatus angezeigt.',password:'Passwort ändern',currentPassword:'Aktuelles Passwort',newPassword:'Neues Passwort',confirmPassword:'Neues Passwort bestätigen',changePassword:'Passwort aktualisieren',passwordChanged:'Passwort aktualisiert.',passwordMismatch:'Die neuen Passwörter stimmen nicht überein.',export:'Datenexport anfordern',delete:'Workspace-Löschung anfordern',exportHelp:'Die Exportzustellung ist derzeit eine manuelle Anfrage, kein Sofortdownload.',deleteHelp:'Die Workspace-Löschung wird zur manuellen Prüfung vorgemerkt und erfolgt nicht sofort.',requestSent:'Anfrage erfasst.',ownerOnly:'Nur Workspace-Owner können diesen Bereich ändern.',retry:'Erneut versuchen'}
};
const tabs:Tab[]=['account','organization','brand','team','setup','ai','usage','security'];

export function SettingsPage({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const toast=useToast();const search=useSearchParams();
 const initial=(search.get('section')||search.get('tab')||'account') as Tab;
 const [tab,setTab]=useState<Tab>(tabs.includes(initial)?initial:'account');const [data,setData]=useState<Overview|null>(null);const [form,setForm]=useState<any>({});const [error,setError]=useState('');const [busy,setBusy]=useState('');
 async function load(){setError('');try{const result=await api.get<Overview>('/settings/overview');setData(result);setForm(current=>({...current,name:result.user?.name||'',locale:result.user?.locale||locale,timezone:result.preferences?.default_timezone||'UTC',organization_name:result.organization?.name||'',organization_mode:result.organization?.mode||'owner',brand_name:result.brand?.name||'',industry:result.brand?.industry||'',country:result.brand?.country||'',brand_timezone:result.brand?.timezone||result.preferences?.default_timezone||'UTC',primary_language:result.brand?.primary_language||locale,provider:(result.ai_provider?.provider||'mock').toLowerCase(),model:result.ai_provider?.model||'',temporary_key:'',invite_email:'',invite_role:'viewer',current_password:'',new_password:'',confirm_password:''}))}catch(e:any){setError(e?.message||String(e))}}
 useEffect(()=>{load()},[]);
 function set(key:string,value:any){setForm((current:any)=>({...current,[key]:value}))}
 async function perform(key:string,task:()=>Promise<any>,message=c.saved){setBusy(key);try{await task();toast(message);await load()}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function saveProfile(){await perform('profile',()=>api.patch('/settings/profile',{name:form.name.trim(),locale:form.locale,timezone:form.timezone}))}
 async function saveOrganization(){await perform('organization',()=>api.patch('/settings/organization',{name:form.organization_name.trim(),mode:form.organization_mode}))}
 async function saveBrand(){await perform('brand',()=>api.patch('/settings/brand-defaults',{name:form.brand_name.trim(),industry:form.industry.trim(),country:form.country.trim(),timezone:form.brand_timezone,primary_language:form.primary_language}))}
 async function invite(){if(!form.invite_email.trim())return;await perform('invite',()=>api.post('/settings/team/invite',{email:form.invite_email.trim().toLowerCase(),role:form.invite_role}),c.invited);set('invite_email','')}
 async function updateMember(member:Member,payload:any){await perform(`member-${member.id}`,()=>api.patch(`/settings/team/${member.id}`,payload))}
 async function disableMember(member:Member){if(!confirm(c.removeConfirm))return;await perform(`member-${member.id}`,()=>api.delete(`/settings/team/${member.id}`))}
 async function testProvider(){setBusy('ai');try{const result=await api.post<any>('/settings/ai-provider/test',{provider:form.provider,model:form.model,api_key:form.temporary_key});toast(result.message||result.status)}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 async function changePassword(){if(form.new_password!==form.confirm_password){toast(c.passwordMismatch);return}await perform('password',()=>api.post('/settings/security/change-password',{current_password:form.current_password,new_password:form.new_password}),c.passwordChanged);set('current_password','');set('new_password','');set('confirm_password','')}
 async function requestAction(path:string){setBusy(path);try{const result=await api.post<any>(path,{});toast(result.message||c.requestSent)}catch(e:any){toast(e?.message||String(e))}finally{setBusy('')}}
 if(error)return <ErrorState message={error} onRetry={load}/>;if(!data)return <LoadingSkeleton label="Loading settings…"/>;
 const canManage=!!data.permissions?.can_manage_team;
 return <div className="space-y-6">
  <section className="command-card p-6"><div className="flex flex-wrap items-start gap-3"><div><p className="badge">{data.organization?.name||'Workspace'} · {data.brand?.name||'Brand'}</p><h1 className="mt-3 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-2 max-w-3xl">{c.sub}</p></div>{tab==='account'&&<button className="btn ms-auto" disabled={!!busy} onClick={saveProfile}>{busy==='profile'?c.saving:c.save}</button>}{tab==='organization'&&<button className="btn ms-auto" disabled={!!busy||!canManage} onClick={saveOrganization}>{busy==='organization'?c.saving:c.save}</button>}{tab==='brand'&&<button className="btn ms-auto" disabled={!!busy} onClick={saveBrand}>{busy==='brand'?c.saving:c.save}</button>}</div></section>
  <div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(item=><button key={item} className={`chip whitespace-nowrap ${tab===item?'!border-blue-200 !bg-blue-50 !text-blue-700':''}`} onClick={()=>setTab(item)}>{c.tabs[item]}</button>)}</div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><section className="panel min-w-0 p-5 md:p-6">
   {tab==='account'&&<Section title={c.tabs.account}><div className="grid gap-4 md:grid-cols-2"><Field label={c.name} value={form.name} onChange={(v:string)=>set('name',v)}/><Field label={c.email} value={data.user.email} readOnly/><Select label={c.language} value={form.locale} options={['en','fa','de']} onChange={(v:string)=>set('locale',v)}/><Field label={c.timezone} value={form.timezone} onChange={(v:string)=>set('timezone',v)}/></div></Section>}
   {tab==='organization'&&<Section title={c.tabs.organization}>{!canManage&&<Notice>{c.ownerOnly}</Notice>}<div className="grid gap-4 md:grid-cols-2"><Field label={c.orgName} disabled={!canManage} value={form.organization_name} onChange={(v:string)=>set('organization_name',v)}/><Select label={c.mode} disabled={!canManage} value={form.organization_mode} options={[['owner',c.owner],['agency',c.agency]]} onChange={(v:string)=>set('organization_mode',v)}/><Read label={c.billing} value={data.organization?.billing_status||'not configured'}/><Read label={c.plan} value={data.organization?.plan||'Not connected'}/></div></Section>}
   {tab==='brand'&&<Section title={c.tabs.brand}><div className="grid gap-4 md:grid-cols-2"><Field label={c.brandName} value={form.brand_name} onChange={(v:string)=>set('brand_name',v)}/><Field label={c.industry} value={form.industry} onChange={(v:string)=>set('industry',v)}/><Field label={c.country} value={form.country} onChange={(v:string)=>set('country',v)}/><Field label={c.timezone} value={form.brand_timezone} onChange={(v:string)=>set('brand_timezone',v)}/><Select label={c.primaryLanguage} value={form.primary_language} options={['en','fa','de']} onChange={(v:string)=>set('primary_language',v)}/></div></Section>}
   {tab==='team'&&<Section title={c.tabs.team}>{!canManage&&<Notice>{c.ownerOnly}</Notice>}<div className="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[minmax(0,1fr)_14rem_auto]"><Field label={c.inviteEmail} type="email" disabled={!canManage} value={form.invite_email} onChange={(v:string)=>set('invite_email',v)}/><Select label={c.inviteRole} disabled={!canManage} value={form.invite_role} options={data.roles.map(role=>[role.id,role.label])} onChange={(v:string)=>set('invite_role',v)}/><button className="btn self-end" disabled={!canManage||!form.invite_email.trim()||!!busy} onClick={invite}>{busy==='invite'?'…':c.invite}</button></div><div className="mt-5 overflow-x-auto">{data.team.length?<table className="table"><thead><tr><th>{c.name}</th><th>{c.email}</th><th>{c.role}</th><th>{c.status}</th><th/></tr></thead><tbody>{data.team.map(member=><tr key={member.id}><td>{member.name||'Invited user'}</td><td>{member.email}</td><td>{canManage?<select className="field min-w-44" value={member.role} disabled={busy===`member-${member.id}`} onChange={event=>updateMember(member,{role:event.target.value})}>{data.roles.map(role=><option key={role.id} value={role.id}>{role.label}</option>)}</select>:member.role}</td><td><StatusBadge status={member.status}/></td><td className="text-end">{canManage&&member.user_id!==data.user.id&&(member.status==='disabled'?<button className="chip" disabled={!!busy} onClick={()=>updateMember(member,{status:'active'})}>{c.enable}</button>:<button className="chip border-red-200 !text-red-700" disabled={!!busy} onClick={()=>disableMember(member)}>{c.disable}</button>)}</td></tr>)}</tbody></table>:<p className="muted p-6 text-center">{c.teamEmpty}</p>}</div></Section>}
   {tab==='setup'&&<Section title={c.tabs.setup}><div className="rounded-2xl bg-blue-50 p-5"><p className="text-sm text-blue-800">{c.setupCompletion}</p><b className="mt-2 block text-4xl text-blue-950">{data.setup.completion_percent}%</b><div className="mt-4 h-2 overflow-hidden rounded-full bg-blue-100"><div className="h-full bg-blue-600" style={{width:`${data.setup.completion_percent}%`}}/></div></div><div className="mt-5 space-y-2">{data.setup.steps.map((step:any)=><Link className="flex items-center gap-3 rounded-2xl border border-slate-200 p-4 hover:bg-slate-50" href={`/${locale}${step.action_href}`} key={step.id}><span className={`grid h-9 w-9 place-items-center rounded-xl ${step.status==='done'?'bg-green-100 text-green-700':'bg-slate-100'}`}>{step.status==='done'?'✓':'→'}</span><span><b className="block">{step.title}</b><span className="muted text-xs">{step.description}</span></span><StatusBadge status={step.status}/></Link>)}</div></Section>}
   {tab==='ai'&&<Section title={c.providerTitle}><p className="muted mb-5">{c.providerHelp}</p><div className="grid gap-4 md:grid-cols-2"><Select label={c.provider} value={form.provider} options={['mock','openai','anthropic','gemini','custom']} onChange={(v:string)=>set('provider',v)}/><Field label={c.model} value={form.model} onChange={(v:string)=>set('model',v)}/><Field label={c.temporaryKey} type="password" value={form.temporary_key} onChange={(v:string)=>set('temporary_key',v)}/><div className="rounded-2xl bg-slate-50 p-4"><p className="text-sm font-bold">Runtime status</p><div className="mt-2 flex items-center gap-2"><StatusBadge status={data.ai_provider.status}/><span className="muted text-sm">{data.ai_provider.provider}{data.ai_provider.model?` · ${data.ai_provider.model}`:''}</span></div></div></div><Notice>{c.notPersisted}</Notice><button className="btn mt-5" disabled={busy==='ai'} onClick={testProvider}>{busy==='ai'?'…':c.test}</button></Section>}
   {tab==='usage'&&<Section title={c.tabs.usage}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label={c.operations} value={data.usage.ai_credits_used}/><Metric label={c.drafts} value={data.usage.drafts_count}/><Metric label={c.reports} value={data.usage.reports_count}/><Metric label={c.assets} value={data.usage.assets_count}/></div><Notice>{c.billingPlaceholder}</Notice></Section>}
   {tab==='security'&&<Section title={c.tabs.security}><h3 className="text-lg font-black">{c.password}</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label={c.currentPassword} type="password" value={form.current_password} onChange={(v:string)=>set('current_password',v)}/><Field label={c.newPassword} type="password" value={form.new_password} onChange={(v:string)=>set('new_password',v)}/><Field label={c.confirmPassword} type="password" value={form.confirm_password} onChange={(v:string)=>set('confirm_password',v)}/></div><button className="btn mt-4" disabled={busy==='password'||!form.current_password||form.new_password.length<8} onClick={changePassword}>{busy==='password'?'…':c.changePassword}</button><div className="my-7 border-t border-slate-200"/><div className="grid gap-4 md:grid-cols-2"><Action title={c.export} description={c.exportHelp} action={c.export} disabled={!!busy} onClick={()=>requestAction('/settings/export-data')}/><Action danger title={c.delete} description={c.deleteHelp} action={c.delete} disabled={!!busy} onClick={()=>confirm(c.deleteHelp)&&requestAction('/settings/delete-workspace-request')}/></div></Section>}
  </section><aside className="panel h-fit p-5 xl:sticky xl:top-24"><h2 className="text-xl font-black">Settings guide</h2><p className="muted mt-2 text-sm">{data.setup.steps.find((step:any)=>step.status!=='done')?.description||'Your core setup is complete.'}</p><Link className="btn mt-4 w-full" href={`/${locale}${data.setup.steps.find((step:any)=>step.status!=='done')?.action_href||'/app/dashboard'}`}>{c.next}</Link><div className="mt-5 space-y-3">{data.alerts?.slice(0,4).map((alert:any)=><Link className="block rounded-2xl bg-amber-50 p-3 text-sm text-amber-900" href={`/${locale}${alert.href||'/app/dashboard'}`} key={alert.id}><b>{alert.title}</b><p className="mt-1">{alert.description}</p></Link>)}</div></aside></div>
 </div>
}
function Section({title,children}:any){return <div><h2 className="text-2xl font-black">{title}</h2><div className="mt-5">{children}</div></div>}
function Field({label,value,onChange,type='text',readOnly=false,disabled=false}:any){return <label className="block text-sm font-bold">{label}<input className="field mt-2" type={type} value={value||''} readOnly={readOnly} disabled={disabled} onChange={event=>onChange?.(event.target.value)}/></label>}
function Select({label,value,options,onChange,disabled=false}:any){return <label className="block text-sm font-bold">{label}<select className="field mt-2" value={value||''} disabled={disabled} onChange={event=>onChange(event.target.value)}>{options.map((option:any)=>{const value=Array.isArray(option)?option[0]:option;const label=Array.isArray(option)?option[1]:option;return <option key={value} value={value}>{label}</option>})}</select></label>}
function Read({label,value}:any){return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p className="muted text-xs">{label}</p><b className="mt-2 block">{value||'—'}</b></div>}
function Metric({label,value}:any){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="muted text-sm">{label}</p><b className="mt-2 block text-3xl">{value??0}</b></div>}
function Notice({children}:any){return <p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{children}</p>}
function Action({title,description,action,onClick,danger=false,disabled=false}:any){return <div className={`rounded-2xl border p-5 ${danger?'border-red-200 bg-red-50':'border-slate-200 bg-slate-50'}`}><b>{title}</b><p className="muted mt-2 text-sm">{description}</p><button className={`chip mt-4 ${danger?'border-red-200 !text-red-700':''}`} disabled={disabled} onClick={onClick}>{action}</button></div>}
