import Link from 'next/link';
import {statusLabel, tx} from '@/lib/i18n';

export function LoadingSkeleton({label,locale='en'}:{label?:string;locale?:string}){const text=label||tx(locale,'common.loading')||'Loading…';return <div className="panel p-6"><div className="h-6 w-48 animate-pulse rounded bg-slate-200"/><div className="mt-4 grid gap-3 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl bg-slate-100"/>)}</div><p className="muted mt-4">{text}</p></div>}
export function ErrorState({title,message,onRetry,locale='en'}:{title?:string;message?:string;onRetry?:()=>void;locale?:string}){return <div className="panel border-red-100 bg-red-50 p-6 text-red-900"><h2 className="text-2xl font-black">{title||tx(locale,'common.error')||'Error'}</h2><p className="mt-2">{message||tx(locale,'errors.generic')}</p>{onRetry&&<button className="btn mt-4" onClick={onRetry}>{tx(locale,'actions.retry')||'Retry'}</button>}</div>}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center"><b>{title}</b><p className="muted mt-2">{description}</p></div>}
export function AccessDenied({locale,message}:{locale:string;message?:string}){return <div className="panel p-8"><span className="badge badge-warn">403</span><h1 className="mt-4 text-3xl font-black">{tx(locale,'admin.accessDenied')||'Access denied'}</h1><p className="muted mt-2">{message||tx(locale,'admin.noAccess')||tx(locale,'errors.permission')}</p><Link className="btn mt-5" href={`/${locale}/app/dashboard`}>{tx(locale,'admin.backDashboard')||'Back to dashboard'}</Link></div>}
export function StatusBadge({status,locale='en'}:{status:string;locale?:string}){const normalized=String(status||'unknown').replaceAll('-','_').toLowerCase();const bad=['failed','error','danger','suspended','disabled','down'];const good=['healthy','active','connected','done','success','approved','published'];return <span className={bad.includes(normalized)?'badge badge-warn':good.includes(normalized)?'badge badge-success':'badge'}>{statusLabel(locale,normalized)}</span>}
export function KpiCard({label,value,helper}:{label:string;value:any;helper?:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="muted text-sm">{label}</p><b className="mt-2 block text-2xl">{value}</b>{helper&&<p className="muted mt-1 text-xs">{helper}</p>}</div>}
