'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {LanguageSwitcher} from './language-switcher';
import {api,TOKEN_KEY} from '@/lib/api';

const copy:any={
 en:{title:'Create your Smarbiz workspace',sub:'Start with a real workspace and continue into guided Brand Pulse setup.',name:'Your name',organization:'Organization / brand',email:'Work email',language:'Primary language',password:'Password',confirm:'Confirm password',consent:'I confirm that I am authorized to create and manage this workspace and accept responsible use of the service.',submit:'Create workspace',loading:'Creating workspace…',existing:'Already have an account?',login:'Sign in',mismatch:'Passwords do not match.',weak:'Use at least 8 characters, including a letter and a number.',invalid:'Enter a valid email address.',consentRequired:'Confirm authorization and responsible use before continuing.',strength:['Too short','Basic','Good','Strong'],badge:'Guided workspace setup',journey:['Workspace','Brand Pulse','First week'],resultTitle:'Your first usable result',resultText:'A private workspace, saved brand context, an editable content calendar, and real approval links.',signupFailed:'Could not create the workspace. Try another email.',missingToken:'The signup response did not include a session token.'},
 fa:{title:'فضای کاری اسماربیز را بساز',sub:'یک فضای واقعی ایجاد کن و سپس راه‌اندازی هدایت‌شده پالس برند را ادامه بده.',name:'نام شما',organization:'سازمان / برند',email:'ایمیل کاری',language:'زبان اصلی',password:'رمز عبور',confirm:'تکرار رمز عبور',consent:'تأیید می‌کنم مجاز به ساخت و مدیریت این فضای کاری هستم و از سرویس مسئولانه استفاده می‌کنم.',submit:'ساخت فضای کاری',loading:'در حال ساخت فضای کاری…',existing:'از قبل حساب داری؟',login:'ورود',mismatch:'رمزها یکسان نیستند.',weak:'حداقل ۸ کاراکتر شامل حرف و عدد وارد کن.',invalid:'ایمیل معتبر وارد کن.',consentRequired:'قبل از ادامه، مجوز و استفاده مسئولانه را تأیید کن.',strength:['خیلی کوتاه','پایه','خوب','قوی'],badge:'راه‌اندازی هدایت‌شده فضای کاری',journey:['فضای کاری','پالس برند','هفته اول'],resultTitle:'اولین خروجی قابل استفاده تو',resultText:'یک فضای کاری خصوصی، اطلاعات ذخیره‌شده برند، تقویم محتوای قابل ویرایش و لینک‌های واقعی تأیید.',signupFailed:'ساخت فضای کاری انجام نشد. یک ایمیل دیگر را امتحان کن.',missingToken:'پاسخ ثبت‌نام شامل نشست کاربری نبود.'},
 de:{title:'Smarbiz-Workspace erstellen',sub:'Starten Sie mit einem echten Workspace und fahren Sie mit dem geführten Brand-Pulse-Setup fort.',name:'Ihr Name',organization:'Organisation / Marke',email:'Geschäftliche E-Mail',language:'Primärsprache',password:'Passwort',confirm:'Passwort bestätigen',consent:'Ich bestätige, dass ich berechtigt bin, diesen Workspace zu erstellen und zu verwalten, und den Dienst verantwortungsvoll nutze.',submit:'Workspace erstellen',loading:'Workspace wird erstellt…',existing:'Sie haben bereits ein Konto?',login:'Anmelden',mismatch:'Die Passwörter stimmen nicht überein.',weak:'Verwenden Sie mindestens 8 Zeichen mit einem Buchstaben und einer Zahl.',invalid:'Geben Sie eine gültige E-Mail-Adresse ein.',consentRequired:'Bestätigen Sie Berechtigung und verantwortungsvolle Nutzung.',strength:['Zu kurz','Basis','Gut','Stark'],badge:'Geführte Workspace-Einrichtung',journey:['Workspace','Brand Pulse','Erste Woche'],resultTitle:'Ihr erstes nutzbares Ergebnis',resultText:'Ein privater Workspace, gespeicherter Markenkontext, ein bearbeitbarer Content-Kalender und echte Freigabelinks.',signupFailed:'Workspace konnte nicht erstellt werden. Versuchen Sie eine andere E-Mail-Adresse.',missingToken:'Die Registrierungsantwort enthielt kein Sitzungstoken.'}
};

export function SignupScreen({locale}:{locale:string}){
 const c=copy[locale]||copy.en;const router=useRouter();const [form,setForm]=useState({name:'',organization_name:'',email:'',preferred_language:locale,password:'',confirm:'',consent:false});const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 useEffect(()=>{if(localStorage.getItem(TOKEN_KEY))router.replace(`/${locale}/app/dashboard`)},[locale,router]);
 const strength=useMemo(()=>{const password=form.password;let score=0;if(password.length>=8)score++;if(/[A-Za-z]/.test(password)&&/\d/.test(password))score++;if(password.length>=12&&/[^A-Za-z0-9]/.test(password))score++;return score},[form.password]);
 function set(key:string,value:any){setForm(current=>({...current,[key]:value}));setError('')}
 async function submit(event:React.FormEvent){event.preventDefault();const email=form.email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email)){setError(c.invalid);return}if(form.password!==form.confirm){setError(c.mismatch);return}if(form.password.length<8||!/[A-Za-z]/.test(form.password)||!/\d/.test(form.password)){setError(c.weak);return}if(!form.consent){setError(c.consentRequired);return}setLoading(true);try{const result=await api.post<any>('/auth/signup',{name:form.name.trim(),organization_name:form.organization_name.trim(),email,password:form.password,preferred_language:form.preferred_language,locale:form.preferred_language});if(!result.access_token)throw new Error(c.missingToken);localStorage.setItem(TOKEN_KEY,result.access_token);localStorage.setItem('smarbiz_email',result.user.email);localStorage.setItem('smarbiz_role','owner');router.replace(`/${locale}/onboarding`)}catch(e:any){setError(e?.message||c.signupFailed)}finally{setLoading(false)}}
 return <main className="auth-page grid min-h-screen place-items-center p-5" dir={locale==='fa'?'rtl':'ltr'}><div className="absolute end-5 top-5"><LanguageSwitcher locale={locale}/></div><section className="grid w-full max-w-6xl gap-6 lg:grid-cols-[1fr_.9fr]"><div className="command-card relative overflow-hidden p-8"><Link href={`/${locale}`} className="flex items-center gap-3"><span className="logo-mark">S</span><b>Smarbiz</b></Link><span className="badge mt-8">{c.badge}</span><h1 className="mt-5 text-4xl font-black md:text-5xl">{c.title}</h1><p className="muted mt-3 max-w-xl text-lg">{c.sub}</p><div className="mt-8 grid gap-3 sm:grid-cols-3">{c.journey.map((title:string,index:number)=><Step key={title} icon={String(index+1)} title={title}/>)}</div><div className="mt-8 rounded-[2rem] border border-white/60 bg-white/80 p-5 shadow-sm"><b>{c.resultTitle}</b><p className="muted mt-2">{c.resultText}</p></div></div><form onSubmit={submit} className="card p-6 md:p-8"><h2 className="text-2xl font-black">{c.submit}</h2>{error&&<p role="alert" className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label={c.name} value={form.name} autoComplete="name" onChange={(value:string)=>set('name',value)}/><Field label={c.organization} value={form.organization_name} autoComplete="organization" onChange={(value:string)=>set('organization_name',value)}/><Field label={c.email} type="email" value={form.email} autoComplete="email" onChange={(value:string)=>set('email',value)}/><label className="text-sm font-bold">{c.language}<select className="field mt-2" value={form.preferred_language} onChange={event=>set('preferred_language',event.target.value)}><option value="en">English</option><option value="de">Deutsch</option><option value="fa">فارسی</option></select></label><Field label={c.password} type="password" value={form.password} autoComplete="new-password" onChange={(value:string)=>set('password',value)}/><Field label={c.confirm} type="password" value={form.confirm} autoComplete="new-password" onChange={(value:string)=>set('confirm',value)}/></div><div className="mt-3"><div className="flex gap-1">{[1,2,3].map(level=><span key={level} className={`h-1.5 flex-1 rounded-full ${strength>=level?'bg-blue-600':'bg-slate-200'}`}/>)}</div><p className="muted mt-1 text-xs">{c.strength[strength]}</p></div><label className="mt-5 flex items-start gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm"><input className="mt-1" type="checkbox" checked={form.consent} onChange={event=>set('consent',event.target.checked)}/><span>{c.consent}</span></label><button className="btn mt-6 w-full" disabled={loading}>{loading?c.loading:c.submit}</button><p className="muted mt-4 text-center text-sm">{c.existing} <Link className="font-bold text-blue-700" href={`/${locale}/auth/login`}>{c.login}</Link></p></form></section></main>
}
function Field({label,type='text',value,onChange,autoComplete}:any){return <label className="text-sm font-bold">{label}<input required className="field mt-2" type={type} value={value} autoComplete={autoComplete} onChange={event=>onChange(event.target.value)}/></label>}
function Step({icon,title}:any){return <div className="rounded-2xl border border-slate-200 bg-white p-4"><span className="grid h-8 w-8 place-items-center rounded-xl bg-blue-50 font-black text-blue-700">{icon}</span><b className="mt-3 block">{title}</b></div>}
