from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text, JSON, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base

class TimestampMixin:
    created_at: Mapped[str] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[str] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
class User(Base, TimestampMixin):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String,unique=True,index=True); password_hash:Mapped[str]=mapped_column(String); name:Mapped[str]=mapped_column(String); avatar_url:Mapped[str|None]=mapped_column(String,nullable=True); locale:Mapped[str]=mapped_column(String,default='en'); timezone:Mapped[str]=mapped_column(String,default='UTC'); is_active:Mapped[bool]=mapped_column(Boolean,default=True); is_super_admin:Mapped[bool]=mapped_column(Boolean,default=False); last_login_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Plan(Base):
    __tablename__='plans'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String); price_monthly:Mapped[float]=mapped_column(Numeric,default=0); currency:Mapped[str]=mapped_column(String,default='EUR'); limits_json:Mapped[dict]=mapped_column(JSON,default=dict); features_json:Mapped[dict]=mapped_column(JSON,default=dict); active:Mapped[bool]=mapped_column(Boolean,default=True)
class Organization(Base, TimestampMixin):
    __tablename__='organizations'; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[str]=mapped_column(String); slug:Mapped[str]=mapped_column(String,unique=True); mode:Mapped[str]=mapped_column(String,default='owner'); plan_id:Mapped[int|None]=mapped_column(ForeignKey('plans.id'),nullable=True); billing_status:Mapped[str]=mapped_column(String,default='trial'); owner_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id')); suspended_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True)
class OrganizationMember(Base):
    __tablename__='organization_members'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int]=mapped_column(ForeignKey('organizations.id')); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); role:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default='active'); invited_by:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); invited_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); accepted_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Brand(Base, TimestampMixin):
    __tablename__='brands'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int]=mapped_column(ForeignKey('organizations.id')); name:Mapped[str]=mapped_column(String); slug:Mapped[str]=mapped_column(String,index=True); website_url:Mapped[str|None]=mapped_column(String,nullable=True); industry:Mapped[str]=mapped_column(String,default='general'); country:Mapped[str]=mapped_column(String,default='DE'); timezone:Mapped[str]=mapped_column(String,default='Europe/Berlin'); primary_language:Mapped[str]=mapped_column(String,default='de'); additional_languages:Mapped[list]=mapped_column(JSON,default=list); description:Mapped[str]=mapped_column(Text,default=''); status:Mapped[str]=mapped_column(String,default='onboarding')
class BrandDNA(Base, TimestampMixin):
    __tablename__='brand_dna'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id'),unique=True); voice_json:Mapped[dict]=mapped_column(JSON,default=dict); visual_json:Mapped[dict]=mapped_column(JSON,default=dict); compliance_json:Mapped[dict]=mapped_column(JSON,default=dict); channel_rules_json:Mapped[dict]=mapped_column(JSON,default=dict); cta_library_json:Mapped[dict]=mapped_column(JSON,default=dict); forbidden_words_json:Mapped[dict]=mapped_column(JSON,default=dict)
class BrandMemoryNote(Base):
    __tablename__='brand_memory_notes'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); note:Mapped[str]=mapped_column(Text); source_type:Mapped[str]=mapped_column(String); source_id:Mapped[str|None]=mapped_column(String,nullable=True); confidence_score:Mapped[float]=mapped_column(Numeric,default=.75); accepted_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); rejected_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); auto_generated:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ContentPillar(Base):
    __tablename__='content_pillars'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); name:Mapped[str]=mapped_column(String); description:Mapped[str]=mapped_column(Text); weight:Mapped[float]=mapped_column(Numeric,default=1); active:Mapped[bool]=mapped_column(Boolean,default=True)
class ProductService(Base, TimestampMixin):
    __tablename__='product_services'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); type:Mapped[str]=mapped_column(String); name:Mapped[str]=mapped_column(String); description:Mapped[str]=mapped_column(Text); price:Mapped[float|None]=mapped_column(Numeric,nullable=True); currency:Mapped[str]=mapped_column(String,default='EUR'); stock_status:Mapped[str]=mapped_column(String,default='available'); landing_page_url:Mapped[str|None]=mapped_column(String,nullable=True); risk_category:Mapped[str]=mapped_column(String,default='low'); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)

class Persona(Base, TimestampMixin):
    __tablename__='personas'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); name:Mapped[str]=mapped_column(String); segment:Mapped[str]=mapped_column(String,default=''); description:Mapped[str]=mapped_column(Text,default=''); pains:Mapped[list]=mapped_column(JSON,default=list); desires:Mapped[list]=mapped_column(JSON,default=list); objections:Mapped[list]=mapped_column(JSON,default=list); preferred_channels:Mapped[list]=mapped_column(JSON,default=list); language:Mapped[str]=mapped_column(String,default='en')
class BrandRule(Base, TimestampMixin):
    __tablename__='brand_rules'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); category:Mapped[str]=mapped_column(String,default='voice'); title:Mapped[str]=mapped_column(String); description:Mapped[str]=mapped_column(Text,default=''); severity:Mapped[str]=mapped_column(String,default='info'); applies_to_channel:Mapped[str|None]=mapped_column(String,nullable=True); is_active:Mapped[bool]=mapped_column(Boolean,default=True)
class ChannelAccount(Base, TimestampMixin):
    __tablename__='channel_accounts'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); provider:Mapped[str]=mapped_column(String); account_name:Mapped[str]=mapped_column(String); account_identifier:Mapped[str]=mapped_column(String); connection_status:Mapped[str]=mapped_column(String,default='mock_connected'); capabilities_json:Mapped[dict]=mapped_column(JSON,default=dict); credentials_encrypted_json:Mapped[dict]=mapped_column(JSON,default=dict); token_expires_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); last_sync_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True)
class CalendarItem(Base, TimestampMixin):
    __tablename__='calendar_items'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); campaign_id:Mapped[int|None]=mapped_column(nullable=True); title:Mapped[str]=mapped_column(String); description:Mapped[str]=mapped_column(Text); scheduled_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); timezone:Mapped[str]=mapped_column(String,default='UTC'); status:Mapped[str]=mapped_column(String,default='planned'); goal:Mapped[str]=mapped_column(String,default='awareness'); funnel_stage:Mapped[str]=mapped_column(String,default='top'); content_type:Mapped[str]=mapped_column(String,default='post'); channels_json:Mapped[list]=mapped_column(JSON,default=list); language:Mapped[str]=mapped_column(String,default='en'); persona_id:Mapped[int|None]=mapped_column(nullable=True); pillar_id:Mapped[int|None]=mapped_column(nullable=True); product_service_id:Mapped[int|None]=mapped_column(nullable=True); offer_id:Mapped[int|None]=mapped_column(nullable=True); cta:Mapped[str]=mapped_column(String,default='Learn more'); risk_score:Mapped[float]=mapped_column(Numeric,default=.1); created_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); assigned_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True)
class ContentDraft(Base, TimestampMixin):
    __tablename__='content_drafts'; id:Mapped[int]=mapped_column(primary_key=True); calendar_item_id:Mapped[int|None]=mapped_column(ForeignKey('calendar_items.id'),nullable=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); channel:Mapped[str]=mapped_column(String); content_type:Mapped[str]=mapped_column(String); language:Mapped[str]=mapped_column(String); title:Mapped[str]=mapped_column(String); body:Mapped[str]=mapped_column(Text); hashtags_json:Mapped[list]=mapped_column(JSON,default=list); media_asset_ids_json:Mapped[list]=mapped_column(JSON,default=list); status:Mapped[str]=mapped_column(String,default='draft_ready'); current_version_id:Mapped[int|None]=mapped_column(nullable=True); brand_fit_score:Mapped[float]=mapped_column(Numeric,default=.86); compliance_score:Mapped[float]=mapped_column(Numeric,default=.9); ai_provider:Mapped[str]=mapped_column(String,default='mock'); ai_model:Mapped[str]=mapped_column(String,default='deterministic-v1'); created_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True)
class ContentVersion(Base):
    __tablename__='content_versions'; id:Mapped[int]=mapped_column(primary_key=True); draft_id:Mapped[int]=mapped_column(ForeignKey('content_drafts.id')); version_number:Mapped[int]=mapped_column(Integer); title:Mapped[str]=mapped_column(String); body:Mapped[str]=mapped_column(Text); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); ai_generated:Mapped[bool]=mapped_column(Boolean,default=True); prompt_id:Mapped[int|None]=mapped_column(nullable=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ApprovalRequest(Base, TimestampMixin):
    __tablename__='approval_requests'; id:Mapped[int]=mapped_column(primary_key=True); draft_id:Mapped[int]=mapped_column(ForeignKey('content_drafts.id')); requested_by_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); assigned_to_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); public_token_hash:Mapped[str]=mapped_column(String,index=True); status:Mapped[str]=mapped_column(String,default='pending'); expires_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True)
class ApprovalAction(Base):
    __tablename__='approval_actions'; id:Mapped[int]=mapped_column(primary_key=True); approval_request_id:Mapped[int]=mapped_column(ForeignKey('approval_requests.id')); user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); action:Mapped[str]=mapped_column(String); comment:Mapped[str|None]=mapped_column(Text,nullable=True); revision_prompt:Mapped[str|None]=mapped_column(Text,nullable=True); version_id:Mapped[int|None]=mapped_column(ForeignKey('content_versions.id'),nullable=True); save_to_memory:Mapped[bool]=mapped_column(Boolean,default=True); source_channel:Mapped[str]=mapped_column(String,default='in_app'); source_message_id:Mapped[str|None]=mapped_column(String,nullable=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ScheduledPost(Base, TimestampMixin):
    __tablename__='scheduled_posts'; id:Mapped[int]=mapped_column(primary_key=True); draft_id:Mapped[int]=mapped_column(ForeignKey('content_drafts.id')); channel_account_id:Mapped[int]=mapped_column(ForeignKey('channel_accounts.id')); scheduled_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); status:Mapped[str]=mapped_column(String,default='scheduled'); provider_post_id:Mapped[str|None]=mapped_column(String,nullable=True); assisted_publish_url:Mapped[str|None]=mapped_column(String,nullable=True); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); retry_count:Mapped[int]=mapped_column(Integer,default=0)
class PublishedPost(Base):
    __tablename__='published_posts'; id:Mapped[int]=mapped_column(primary_key=True); draft_id:Mapped[int]=mapped_column(ForeignKey('content_drafts.id')); channel_account_id:Mapped[int]=mapped_column(ForeignKey('channel_accounts.id')); provider_post_id:Mapped[str]=mapped_column(String); public_url:Mapped[str]=mapped_column(String); published_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now()); status:Mapped[str]=mapped_column(String,default='published'); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class InsightSnapshot(Base):
    __tablename__='insight_snapshots'; id:Mapped[int]=mapped_column(primary_key=True); published_post_id:Mapped[int]=mapped_column(ForeignKey('published_posts.id')); captured_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now()); metrics_json:Mapped[dict]=mapped_column(JSON,default=dict); normalized_scores_json:Mapped[dict]=mapped_column(JSON,default=dict)
class WeeklyReport(Base):
    __tablename__='weekly_reports'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); week_start:Mapped[str]=mapped_column(String); week_end:Mapped[str]=mapped_column(String); summary:Mapped[str]=mapped_column(Text); insights_json:Mapped[dict]=mapped_column(JSON,default=dict); recommendations_json:Mapped[dict]=mapped_column(JSON,default=dict); generated_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())

class Campaign(Base, TimestampMixin):
    __tablename__='campaigns'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int]=mapped_column(ForeignKey('organizations.id')); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); name:Mapped[str]=mapped_column(String); goal:Mapped[str|None]=mapped_column(String,nullable=True); description:Mapped[str]=mapped_column(Text,default=''); offer:Mapped[str|None]=mapped_column(String,nullable=True); target_audience:Mapped[str|None]=mapped_column(String,nullable=True); start_date:Mapped[str|None]=mapped_column(String,nullable=True); end_date:Mapped[str|None]=mapped_column(String,nullable=True); status:Mapped[str]=mapped_column(String,default='draft'); channels_json:Mapped[list]=mapped_column(JSON,default=list); content_pillars_json:Mapped[list]=mapped_column(JSON,default=list); budget:Mapped[float|None]=mapped_column(Numeric,nullable=True); owner_user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True)
class CampaignPlanItem(Base, TimestampMixin):
    __tablename__='campaign_plan_items'; id:Mapped[int]=mapped_column(primary_key=True); campaign_id:Mapped[int]=mapped_column(ForeignKey('campaigns.id')); title:Mapped[str]=mapped_column(String); channel:Mapped[str]=mapped_column(String,default='general'); content_type:Mapped[str]=mapped_column(String,default='post'); brief:Mapped[str]=mapped_column(Text,default=''); suggested_date:Mapped[str|None]=mapped_column(String,nullable=True); status:Mapped[str]=mapped_column(String,default='idea'); linked_content_draft_id:Mapped[int|None]=mapped_column(ForeignKey('content_drafts.id'),nullable=True); linked_calendar_item_id:Mapped[int|None]=mapped_column(ForeignKey('calendar_items.id'),nullable=True)

class AuditLog(Base):
    __tablename__='audit_logs'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int|None]=mapped_column(ForeignKey('brands.id'),nullable=True); user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); action:Mapped[str]=mapped_column(String); target_type:Mapped[str]=mapped_column(String); target_id:Mapped[str|None]=mapped_column(String,nullable=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); ip_address:Mapped[str|None]=mapped_column(String,nullable=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class JobLog(Base):
    __tablename__='job_logs'; id:Mapped[int]=mapped_column(primary_key=True); job_type:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int|None]=mapped_column(ForeignKey('brands.id'),nullable=True); payload_json:Mapped[dict]=mapped_column(JSON,default=dict); result_json:Mapped[dict]=mapped_column(JSON,default=dict); error_message:Mapped[str|None]=mapped_column(Text,nullable=True); started_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); finished_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class FeatureFlag(Base):
    __tablename__='feature_flags'; id:Mapped[int]=mapped_column(primary_key=True); key:Mapped[str]=mapped_column(String); enabled:Mapped[bool]=mapped_column(Boolean,default=True); scope_type:Mapped[str]=mapped_column(String,default='global'); scope_id:Mapped[str|None]=mapped_column(String,nullable=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)

class SetupChecklistItem(Base, TimestampMixin):
    __tablename__='setup_checklist_items'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); key:Mapped[str]=mapped_column(String); label:Mapped[str]=mapped_column(String); status:Mapped[str]=mapped_column(String,default='pending'); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class Asset(Base, TimestampMixin):
    __tablename__='assets'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); name:Mapped[str]=mapped_column(String); asset_type:Mapped[str]=mapped_column(String,default='metadata_only'); url:Mapped[str|None]=mapped_column(String,nullable=True); description:Mapped[str]=mapped_column(Text,default=''); tags_json:Mapped[list]=mapped_column(JSON,default=list); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
class ManualMetric(Base, TimestampMixin):
    __tablename__='manual_metrics'; id:Mapped[int]=mapped_column(primary_key=True); brand_id:Mapped[int]=mapped_column(ForeignKey('brands.id')); source:Mapped[str]=mapped_column(String,default='manual'); metric_date:Mapped[str]=mapped_column(String); metrics_json:Mapped[dict]=mapped_column(JSON,default=dict)

class AIUsageLog(Base):
    __tablename__='ai_usage_logs'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int|None]=mapped_column(ForeignKey('brands.id'),nullable=True); user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); provider:Mapped[str]=mapped_column(String); model:Mapped[str]=mapped_column(String); operation:Mapped[str]=mapped_column(String); input_tokens:Mapped[int]=mapped_column(Integer,default=0); output_tokens:Mapped[int]=mapped_column(Integer,default=0); cost_estimate:Mapped[float]=mapped_column(Numeric,default=0); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class ConnectorEvent(Base):
    __tablename__='connector_events'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int|None]=mapped_column(ForeignKey('brands.id'),nullable=True); provider:Mapped[str]=mapped_column(String); event_type:Mapped[str]=mapped_column(String); external_id:Mapped[str|None]=mapped_column(String,nullable=True); payload_json:Mapped[dict]=mapped_column(JSON,default=dict); processed_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[str]=mapped_column(DateTime(timezone=True),server_default=func.now())
class MessagingConsent(Base):
    __tablename__='messaging_consents'; id:Mapped[int]=mapped_column(primary_key=True); organization_id:Mapped[int|None]=mapped_column(ForeignKey('organizations.id'),nullable=True); brand_id:Mapped[int|None]=mapped_column(ForeignKey('brands.id'),nullable=True); user_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); channel:Mapped[str]=mapped_column(String); phone_number:Mapped[str|None]=mapped_column(String,nullable=True); chat_id:Mapped[str|None]=mapped_column(String,nullable=True); consent_status:Mapped[str]=mapped_column(String,default='pending'); consent_source:Mapped[str]=mapped_column(String,default='manual'); consented_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); revoked_at:Mapped[str|None]=mapped_column(DateTime(timezone=True),nullable=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict)
