'use client';
import {useState} from 'react';import {Modal} from '@/components/ui/modal';import {Tabs} from '@/components/ui/tabs';import {useToast} from '@/components/ui/toast';import {Sparkline} from '@/components/charts/sparkline';import {calendar,integrations} from './demo-data';
export function ModulePage({kind}:{kind:string}){const toast=useToast();const [tab,setTab]=useState('Week');const [modal,setModal]=useState('');const [filter,setFilter]=useState('all');
 if(kind==='calendar')return <Shell title="Calendar" actions={<><button className="btn" onClick={()=>toast('Week generated')}>Generate week</button><button className="chip" onClick={()=>setModal('Add idea')}>Add idea</button><button className="chip" onClick={()=>toast('Week regenerated')}>Regenerate week</button></>}><Tabs tabs={['Week','Month','Kanban','List']} value={tab} onChange={setTab}/><Filters setFilter={setFilter}/><div className="grid gap-4 md:grid-cols-2">{calendar.map(i=><Card key={i.title} title={i.title} meta={`${i.time} · ${i.channels} · ${i.status} · ${i.goal}`} onClick={()=>setModal(i.title)}/>)}</div><DemoModal modal={modal} setModal={setModal}/></Shell>;
 if(kind==='content-studio')return <Shell title="Content Studio"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="card space-y-3"><textarea className="field min-h-40" placeholder="Describe campaign, offer, audience and tone…"/><select className="field"><option>Demo Brand</option></select><select className="field"><option>Instagram + Telegram + Bale + LinkedIn</option></select><select className="field"><option>English / German / Persian</option></select><button className="btn w-full" onClick={()=>toast('Generated 5 localized platform drafts')}>Generate</button></section><section className="card"><h2 className="text-2xl font-black">Generated drafts</h2>{['Instagram','Telegram','Bale','LinkedIn','Google Business'].map(p=><Card key={p} title={`${p} preview`} meta="Caption, hashtags, compliance score, version history" onClick={()=>setModal(p)}/>)}</section></div><DemoModal modal={modal} setModal={setModal}/></Shell>;
 if(kind==='approvals')return <Shell title="Approvals"><input className="field mb-4" placeholder="Search approvals"/><Tabs tabs={['pending','approved','rejected','changes requested']} value={tab} onChange={setTab}/><div className="grid gap-4 md:grid-cols-3">{['Skin clinic carousel','Telegram sale copy','LinkedIn security post'].map(x=><Card key={x} title={x} meta="Pending client approval · mobile preview ready" onClick={()=>setModal(x)}/>)}</div><DemoModal modal={modal} setModal={setModal} approval/></Shell>;
 if(kind==='integrations')return <Shell title="Integrations"><div className="grid gap-4 md:grid-cols-3 xl:grid-cols-4">{integrations.map((x,i)=><div className="card" key={x}><h3 className="text-xl font-black">{x}</h3><p className="muted mt-2">Publish · analytics · approvals · assisted publishing</p><span className="badge mt-3">{i%3?'connected':'assisted publishing'}</span><div className="mt-4 flex gap-2"><button className="chip" onClick={()=>setModal(`${x} credentials`)}>Connect</button><button className="chip" onClick={()=>toast(`${x} test succeeded`) }>Test</button><button className="chip" onClick={()=>setModal(`${x} settings`)}>Settings</button></div></div>)}</div><DemoModal modal={modal} setModal={setModal}/></Shell>;
 const maps:any={campaigns:['Launch campaign','Retention campaign','Local SEO campaign'],assets:['Hero photo','Product reel','Logo pack'],analytics:['Overview KPIs','Channel performance','Best posts table'],['brand-dna']:['Voice rules','Content pillars','Forbidden words','Memory notes'],reports:['Weekly report','Campaign report','Agency client report'],settings:['Organization settings','Team roles','AI provider settings','Danger zone']};
 return <Shell title={kind.replace('-',' ').replace(/\b\w/g,m=>m.toUpperCase())} actions={<button className="btn" onClick={()=>setModal('Create / edit')}>Create</button>}><div className="grid gap-4 md:grid-cols-3">{(maps[kind]||[]).map((x:string)=><Card key={x} title={x} meta="Interactive controls, filters, tables and safe demo actions" onClick={()=>setModal(x)}/>)}</div><section className="card mt-6"><h2 className="text-2xl font-black">Performance and recommendations</h2><Sparkline/><p className="muted">Manual entries, exports, toggles and settings persist locally for the SaaS demo.</p></section><DemoModal modal={modal} setModal={setModal}/></Shell>}
function Shell({title,children,actions}:{title:string;children:React.ReactNode;actions?:React.ReactNode}){return <div className="space-y-6"><div className="flex flex-wrap gap-3"><h1 className="text-4xl font-black">{title}</h1><div className="ms-auto flex gap-2">{actions}</div></div>{children}</div>}
function Filters({setFilter}:{setFilter:(v:string)=>void}){return <div className="my-4 grid gap-2 md:grid-cols-4">{['channel','status','language','content type'].map(x=><select className="field" key={x} onChange={e=>setFilter(e.target.value)}><option>{x}: all</option><option>Instagram</option><option>Telegram</option><option>fa</option></select>)}</div>}
function Card({title,meta,onClick}:{title:string;meta:string;onClick:()=>void}){return <div className="card"><h3 className="text-xl font-black">{title}</h3><p className="muted mt-2">{meta}</p><button className="chip mt-4" onClick={onClick}>Open</button></div>}
function DemoModal({modal,setModal,approval=false}:{modal:string;setModal:(v:string)=>void;approval?:boolean}){const toast=useToast();return <Modal open={!!modal} onClose={()=>setModal('')} title={modal}><textarea className="field min-h-32" placeholder="Tell AI what to change" defaultValue="Realistic demo detail drawer with platform preview, metadata, comments and actions."/><label className="mt-3 flex gap-2"><input type="checkbox" defaultChecked/> Save learning to Brand Memory</label><div className="mt-4 flex flex-wrap gap-2"><button className="btn" onClick={()=>{toast(approval?'Approved':'Saved');setModal('')}}>Approve / Save</button><button className="chip" onClick={()=>toast('Rejected')}>Reject</button><button className="chip" onClick={()=>toast('Changes requested')}>Request changes</button></div></Modal>}
